### ISSUE TITLE
Can update data more easier?

### ISSUE THREAD

**Issue by mqliutie** [nosqlclient/nosqlclient#104]
I select a collection and execute  there will have the result  :

![image](https://cloud.githubusercontent.com/assets/11795518/15573685/4a2af8fc-237b-11e6-9403-b4602fcfbd46.png)

So, can I modify password directly？ I have tried to change the value of password， but it's value not modified.
I can do it like this
![image](https://cloud.githubusercontent.com/assets/11795518/15573766/c0e87d16-237b-11e6-8074-ac7f7415d206.png)

I think it is better to be able to directly modify instead of `updateOne`.

**Comment by rsercano** [comment]
Hello,

that's definitely in queue. Can you have a look at **Easy Edit** section, maybe it can be more helpful for you.

Cheers
