### ISSUE TITLE
File Management download fails

### ISSUE THREAD

**Issue by yoshiya8** [nosqlclient/nosqlclient#105]
When I click on the "Download" icon for a GridFS file (on the file management  tab). A new window pops up, but says:

Not Connected!  Route not Found

This is a very consistent problem 

Platform is Windows 64 bit distribution (run from .exe)

Thank you
![capture](https://cloud.githubusercontent.com/assets/12764363/15582770/a957b4cc-2340-11e6-9f4c-6b6a2f029d81.PNG)

**Comment by rsercano** [comment]
Thanks for the feedback, I'll have a look at it asap. 

Cheers

**Comment by rsercano** [comment]
Hello, I've checked the portable and it works perfectly (I've re-downloaded portable from 1.2.1 release)

![123](https://cloud.githubusercontent.com/assets/3640368/15586350/94002a4a-238c-11e6-9b5b-52491cde3098.png)

Mongoclient manages download by redirecting you a new page with route `/download` and some query parameters such as file Id, bucket name etc. I really can't reproduce your situation, are you behind a proxy, or do you have something special in your computer to manage local servers ? 

Additionally you can go `localhost:11237` to manage **Mongoclient** from browser, try to go there and see if it works.

**Comment by yoshiya8** [comment]
My machine is behind a proxy, I am running mongod on another server on my side of the proxy and mongoclient from localhost. Thanks for the port number I was wanting to try the browser approach.

I tried out the browser approach and I get the same problem there... but I am getting some insight into the problem since I can now see the URL... I will have to anonymize the contents of the URL with XXX to prevent divulging a hint about our content, but I think it will be ok...

http://localhost:11237/download/z5qcwaTqPzxK3kcKp/fs/devel/evaluations/xxx/xxx/infiles/xxx/574600f95f2342463a2c7eb5

It looks like the path contains our GridFS filename in it (/devel/evaluations/xxx/xxx/infiles/xxx) - in our case, the GridFS filename was a full linux path containing '/' characters.  I am pretty sure this causing havoc with the final URL that MongoClient is generating.

You may want to encode the bucket and filename in the path (possibly query parameters) because these pathological cases can do some pretty nasty things.

On my side, I told my coworker to stop using full paths in the GridFS filenames yesterday afternoon - but the old data is still there!

**Comment by rsercano** [comment]
I definitely understand the problem now, will fix this by sending these parameters to download route with another way. (maybe I can use headers)  

Thanks for sharing. 

Best

**Comment by yoshiya8** [comment]
You're welcome, thank you for providing this excellent client
