### ISSUE TITLE
Inifintely repeating toastr server status error

### ISSUE THREAD

**Issue by drdamour** [nosqlclient/nosqlclient#107]
in my enterprise i'm given credentials that don't allow for the serverstatus : 1 command on admin.  as such when i connect and am on the mongoclient's "database stats" tab i get infinite toastr notifications of an error.

**Comment by rsercano** [comment]
Oh yeah, thanks for reminding this. Currently you can simply disable database statistics from the settings to prevent this behavior. Nevertheless I will fix this.
