### ISSUE TITLE
Issue connecting to a Mongo server through an ssh tunnel on a mac

### ISSUE THREAD

**Issue by nwillia2** [nosqlclient/nosqlclient#109]
Hi,

I'm currently trying to connect to a mongo server using the ssh tunnel option, but when I attempt to connect, the button just shows a spinner forever.

I'm using key based authentication for the ssh part, and have manually entered the path to my key file:
/Users/MyUsername/.ssh/id_rsa

I've also tried copying this file to my desktop and using the file picker to select it.

Then in the connection 'hostname' I'm using "locahost", as that's what it is after the ssh tunnel.

Could you tell me how I access the log files for this application on my mac please? That may give me some clues as to why it's not working. I've been through the source to try and work out where the log files live, but thought it maybe best to ask the experts!

Thanks a lot,

Neil

**Comment by rsercano** [comment]
Hello Neil,

thanks for trying mongoclient, currently there's no way to see log details in distributions, meteor has some issues with electron and for each release I have to build mongoclient manually at every platform. It's really annoying and couldn't have a chance to find a way to transport logs currently. You can try to [compile as a web application](https://github.com/rsercano/mongoclient/wiki#31-compile-from-source-browser-edition) and try it like that, then you'll able to see logs.

Apart from that, you shouldn't write file path manually, you have to pick it from file dialog, I'm able to connect via SSH tunnel currently.

You have to write hostname, port, authentication etc like you are on localhost as you mentioned. And make sure your SSH port and username is correct. 

Btw how big is your key file ? Maybe there's something wrong with the upload process.

Cheers,

**Comment by nwillia2** [comment]
Thanks for the reply, I'll try and set it up locally to see if the logs are spitting anything out.

**Comment by mjdavies** [comment]
Hi Sercan

I work with Neil and I'm wondering if we're getting something wrong with the key files.

We can connect fine via ssh, using the id_rsa key, but I've had a read around some issue some others have mentioned using a .pem file.

Here's my key details

-rw-------    1 mjdavies  staff   1675 21 Jul  2015 id_rsa
-rw-r--r--    1 mjdavies  staff    415 21 Jul  2015 id_rsa.pub

I'm having the same issue as Neil.

We just add the contents of users .ssh/id_rsa.pub file to the authorized_keys file on the remote server, and use a non standard port with only key access, no logins allowed.

I'm wondering if it's our setup that is causing an issue.

Thanks for helping

Matt

**Comment by rsercano** [comment]
Hello Matt,

as far as I know, if you are able to connect via terminal there should be no problem to connect via Mongoclient as well. I'll investigate this further as soon as possible.

p.s. Please don't forget to setup SSH and mongodb properties properly on mongoclient (such as port, host etc)

Your setup seems correct by the way.

Cheers

**Comment by mjdavies** [comment]
Bit more info from the server.

The auth.log is saying this when I'm trying to connect.

Connection closed by CLIENTIP [preauth]

It happens almost immediately, and I think means the client didn't send any authentication.

I think you may be right and we're filling in our connection properties incorrectly.

Is there any chance you could take some screen grabs, with secure bits removed of course, of your setup that is connecting properly over and ssh tunnel?

Failing that, are there any docs on how to set it up?

I realise this should be really simple, and most of the field names speak for themselves, but once you start hitting a problem you then start questioning all of them.

The screen grabs could even be the docs if you haven't got any already.

Thanks again Sercan, we're really looking forward to using the product, looks like it's exactly what we need.

Matt

**Comment by rsercano** [comment]
Hello Matt,

I've rechecked my SSH connection details, and I've realized I'm using password instead of key file while connecting via SSH. With password there's no problem, but there's a bug for the key file usages, I'm now checking it.

Here's how I've configured my details (**using key file and failed with error: Error: All configured authentication methods failed, will fix this until then you can use password authentication for SSH**):
1. I've configured my connection details like I'm in that server:

![2](https://cloud.githubusercontent.com/assets/3640368/15739117/d485baf4-28ae-11e6-98c2-4575bfc98d7d.png)
1. Then I've configured my MongoDB authentication details, again like I'm in that server:

![3](https://cloud.githubusercontent.com/assets/3640368/15739128/e297a22e-28ae-11e6-9c6e-f839880c71e0.png)
1. And finally I've configured my SSH connection details:

![1](https://cloud.githubusercontent.com/assets/3640368/15739141/ee555b24-28ae-11e6-8668-74d0f643c538.png)

If you have a chance to login with password, try it like this and it will work, as I mentioned I'll fix the key file error.

Cheers

**Comment by rsercano** [comment]
Hello,

ssh key file issue is fixed in the current active source code. If you have a chance to compile it as a web application you can use this feature now. I'll release 1.2.2 soon, after that you'll be able to use this on portables as well.

Cheers

**Comment by nwillia2** [comment]
Thanks very much Sercan, we'll try it out.

**Comment by nwillia2** [comment]
Hi Sercan,

I've just cloned your master branch to run it as a web app, and I'm getting the following error when trying to make the connection as before:

```
mongoclient[master]$ meteor --port 3000
[[[[[ ~/Local_Sites/mongoclient ]]]]]         

=> Started proxy.                             
=> Meteor 1.3.2.4 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
I20160602-20:39:07.780(1)? info: [connect] mongodb://localhost:27017/ssot connectTimeoutMS=3000, socketTimeoutMS=5000, ssl=false, sslValidate=false
W20160602-20:39:07.786(1)? (STDERR) 
W20160602-20:39:07.786(1)? (STDERR) events.js:72
W20160602-20:39:07.786(1)? (STDERR)         throw er; // Unhandled 'error' event
W20160602-20:39:07.786(1)? (STDERR)               ^
W20160602-20:39:07.786(1)? (STDERR) Error: listen EADDRINUSE
W20160602-20:39:07.786(1)? (STDERR)     at errnoException (net.js:905:11)
W20160602-20:39:07.786(1)? (STDERR)     at Server._listen2 (net.js:1043:14)
W20160602-20:39:07.786(1)? (STDERR)     at listen (net.js:1065:10)
W20160602-20:39:07.786(1)? (STDERR)     at net.js:1147:9
W20160602-20:39:07.786(1)? (STDERR)     at asyncCallback (dns.js:68:16)
W20160602-20:39:07.786(1)? (STDERR)     at Object.onanswer [as oncomplete] (dns.js:121:9)
=> Exited with code: 8
```

it looks as if the tunnel is conflicting with my local running mongodb instance. If I kill my local mongodb server, it works.

I tried to play around in the source to see if I could fix this (be able to connect to a mongodb server even when a local instance is running on that default port), using the localPort option of tunnel-ssh:

https://www.npmjs.com/package/tunnel-ssh#remap-remote-port-to-localhost

But I couldn't get it to work.

It's not such a big deal closing my local instance, but thought I'd mention it incase it was an easy fix :).

Thanks very much for your quick response on this, I'll look forward to trying this out on our servers.

Neil

**Comment by rsercano** [comment]
Hello Neil,

in **methods_common.js** there's a connect function, ,in there you can try this out, I'll try to implement it as well.

Cheers
