### ISSUE TITLE
Unziping the Windows x64 installer fails

### ISSUE THREAD

**Issue by sherry-ummen** [nosqlclient/nosqlclient#110]
Whenever I try to download the app from https://github.com/rsercano/mongoclient/releases/download/1.2.1/windows-portable-x64.zip and try to unzip it . I get error "Compressed folder is invalid"

**Comment by rsercano** [comment]
Hello, please try with 7zip or winrar, default windows archiver fails to unzip it. 
duplicate of #81

**Comment by sherry-ummen** [comment]
Thanks that worked :+1:
