### ISSUE TITLE
Please allow to connect to the Server without specifying which database to connect to

### ISSUE THREAD

**Issue by sherry-ummen** [nosqlclient/nosqlclient#111]
Hi,

First of all mongoclient looks so super cool. Awesome work!

I am using MongoChef and Robomongo, both allow you to connect to the server and then it gives a list of databases in that server and by clicking through each database you can perform actions to it.

This is not the case with mongoclient, I have to specify the name of the database which is not very intuitive.

Any plans to have it the way Robomongo or Mongochef shows up the list of database in a server?

Thanks

**Comment by rsercano** [comment]
Hello,

of course it's in the queue. Issue #31 is related with this. I'm planning to add this feature soon but currently struggling with my marriage :)

Thanks for your kind opinions, they really matter. 

Cheers
