### ISSUE TITLE
Certificate based connecting and x509 authentication does not work

### ISSUE THREAD

**Issue by hongbizi** [nosqlclient/nosqlclient#112]
Firstly thanks for the great software.

When I try to use my cetificates for connection in mongoclient with server ssl mode: requireSSL the server log says:

2016-06-03T10:27:39.124+0300 I NETWORK  [initandlisten] connection accepted from 192.168.2.43:46516 #45893 (1 connection now open)
2016-06-03T10:27:39.126+0300 I NETWORK  [conn45893] AssertionException handling request, closing client connection: 17189 The server is configured to only allow SSL connections

When I set  server ssl mode: preferSSL, connection succeeds but mongoclient does not authenticate with client certificate. 

Am I doing some thing wrong or is there an issue with certificate based connecting an authentication?

This is my connection authentication view. Key is not encrypted thus no passphrase:
![image](https://cloud.githubusercontent.com/assets/19725645/15772111/dfae8220-2977-11e6-80f9-7ed1e907290c.png)

**Comment by rsercano** [comment]
Hello,

first of all, thanks for your kind opinions. 

Which distribution are you using ? If you have a chance to compile mongoclient as a web application, please do and share the error logs.

Otherwise what error do you get on error notification ?

Cheers

**Comment by rsercano** [comment]
Hello again,

I've realized a minor bug in the code and fixed now, could you please try again with the active source code ?

_(you have to compile as a web application to test it)_

Cheers

**Comment by hongbizi** [comment]
Hi There,

I'm using Ubuntu trusty.

Application logs on console:

=> App running at: http://localhost:3000/
I20160603-11:46:25.078(3)? info: [connect] mongodb://sandbox:27017/hubitor connectTimeoutMS=3000, socketTimeoutMS=5000, ssl=false, sslValidate=true
W20160603-11:46:25.084(3)? (STDERR) error:  MongoError: server sandbox:27017 timed out
W20160603-11:46:25.085(3)? (STDERR)     at [object Object].<anonymous> (/opt/mongoclient/mongoclient-1.2.1/.meteor/local/isopacks/npm-container/npm/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:436:40)
W20160603-11:46:25.085(3)? (STDERR)     at [object Object].emit (events.js:98:17)
W20160603-11:46:25.085(3)? (STDERR)     at [object Object].<anonymous> (/opt/mongoclient/mongoclient-1.2.1/.meteor/local/isopacks/npm-container/npm/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:144:10)
W20160603-11:46:25.085(3)? (STDERR)     at [object Object].g (events.js:180:16)
W20160603-11:46:25.086(3)? (STDERR)     at [object Object].emit (events.js:98:17)
W20160603-11:46:25.086(3)? (STDERR)     at Socket.<anonymous> (/opt/mongoclient/mongoclient-1.2.1/.meteor/local/isopacks/npm-container/npm/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:172:12)
W20160603-11:46:25.086(3)? (STDERR)     at Socket.g (events.js:180:16)
W20160603-11:46:25.086(3)? (STDERR)     at Socket.emit (events.js:95:17)
W20160603-11:46:25.087(3)? (STDERR)     at TCP.close (net.js:466:12)

Server log:

2016-06-03T11:46:24.871+0300 I NETWORK  [initandlisten] connection accepted from 192.168.2.43:46562 #31 (1 connection now open)
2016-06-03T11:46:24.895+0300 I NETWORK  [conn31] AssertionException handling request, closing client connection: 17189 The server is configured to only allow SSL connections

**Comment by hongbizi** [comment]
OK,

I will. Let you know the result in a few minutes.

**Comment by hongbizi** [comment]
Compiled as web app.

Exactly same result as previously.

I'm not sure if it is related but list of connections in UI indicates following.

Use Ssl: False
Certificate Auth: True

**Comment by rsercano** [comment]
No it's not related, I'll investigate this further.

**Comment by rsercano** [comment]
By the way did you try to set all timeouts to 0 from settings menu before connecting?

**Comment by hongbizi** [comment]
Just did and no effect. Logs are same.

It fails immediately after pressing connect.

**Comment by rsercano** [comment]
Oh okay, I'll have a look at this issue as soon as I get some free time.

**Comment by hongbizi** [comment]
Sorry,

I was a bit sloppy. The applicationi log on console is slightly different now as follows (server log remains same):

=> App running at: http://localhost:3000/
I20160603-16:25:52.164(3)? info: [connect] mongodb://sandbox:27017/hubitor connectTimeoutMS=4000, socketTimeoutMS=5000, ssl=false, sslValidate=true
W20160603-16:25:52.449(3)? (STDERR) error:  MongoError: server sandbox:27017 received an error {"name":"MongoError","message":"write EPIPE"}
W20160603-16:25:52.450(3)? (STDERR)     at [object Object].<anonymous> (/opt/mongoclient/mongoclient-master/.meteor/local/isopacks/npm-container/npm/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:213:40)
W20160603-16:25:52.450(3)? (STDERR)     at [object Object].g (events.js:180:16)
W20160603-16:25:52.450(3)? (STDERR)     at [object Object].emit (events.js:98:17)
W20160603-16:25:52.450(3)? (STDERR)     at [object Object].<anonymous> (/opt/mongoclient/mongoclient-master/.meteor/local/isopacks/npm-container/npm/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:119:12)
W20160603-16:25:52.451(3)? (STDERR)     at [object Object].g (events.js:180:16)
W20160603-16:25:52.451(3)? (STDERR)     at [object Object].emit (events.js:98:17)
W20160603-16:25:52.451(3)? (STDERR)     at Socket.<anonymous> (/opt/mongoclient/mongoclient-master/.meteor/local/isopacks/npm-container/npm/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:151:49)
W20160603-16:25:52.451(3)? (STDERR)     at Socket.g (events.js:180:16)
W20160603-16:25:52.451(3)? (STDERR)     at Socket.emit (events.js:95:17)
W20160603-16:25:52.452(3)? (STDERR)     at onwriteError (_stream_writable.js:239:10)

**Comment by rsercano** [comment]
Hi again,

I guess I've fixed the issue, could you please try again with the active source code ?

Let me know if you encounter any issue.

Cheers

**Comment by hongbizi** [comment]
Great,

Thanks, Unfortunately I'm away from my laptop until tomorrow.

Once possible I will let you know how it is working.

**Comment by hongbizi** [comment]
Hi Again,

It connects now perfectly. However it does not do x509 authentication and as such fails on fetching the information.

Best Regards

**Comment by rsercano** [comment]
Hello,

nice to hear that, I'll check x509 authentication for the next release.

But you are able to use mongoclient now, right ?

Cheers

**Comment by hongbizi** [comment]
Great,

I suppose it is not trivial unless you add a username field to the connection dialog. 

Thanks

**Comment by hongbizi** [comment]
...meaning this dialog.

![image](https://cloud.githubusercontent.com/assets/19725645/15804500/4ec1c612-2b13-11e6-9f75-3ab5a883ad09.png)

**Comment by rsercano** [comment]
Let's keep this discussion on [gitter](https://gitter.im/rsercano/mongoclient) :)
