### ISSUE TITLE
x509 Authentication

### ISSUE THREAD

**Issue by rsercano** [nosqlclient/nosqlclient#113]

**Comment by hongbizi** [comment]
You could use this to set the username.

x509.getSubject(cert)
Parse certificate with x509.parseCert and return the subject.

const x509 = require('x509');
var subject = x509.getSubject(__dirname + '/certs/nodejitsu.com.crt');
/*
subject = { countryName: 'US',
  postalCode: '10010',
  stateOrProvinceName: 'NY',
  localityName: 'New York',
  streetAddress: '902 Broadway, 4th Floor',
  organizationName: 'Nodejitsu',
  organizationalUnitName: 'PremiumSSL Wildcard',
  commonName: '*.nodejitsu.com' }
*/

**Comment by rsercano** [comment]
Hello,

as a temporary solution, now Mongoclient requests a username if you want a x509 username. Your solution is way better but currently I'm in windows and having some trouble with npm and cant install npm packages properly. 

Could you please try and see if it's working ?

Thanks & Cheers

**Comment by hongbizi** [comment]
Still does not authenticate.

Authentication db should be $external. I'm not sure if the app picks up the username from the dialog.

2016-06-05T13:25:12.353+0300 I NETWORK  [initandlisten] connection accepted from 192.168.2.43:55526 #48 (3 connections now open)
2016-06-05T13:25:12.365+0300 I ACCESS   [conn48] Unauthorized: not authorized on hubitor to execute command { listCollections: true, filter: {}, cursor: {} }

**Comment by hongbizi** [comment]
It clears the fields in standard authentication type when setting certs and saving.

**Comment by rsercano** [comment]
Actually you should pick standard or certificate authentication, both is not applicable. But I guess we need an authentication DB option while connecting via certificate.

**Comment by hongbizi** [comment]
In that case how is the username determined?

**Comment by rsercano** [comment]
There should be a new checkbox named as Use x509, and when you check it a new textbox appears in certificate tab.

Here: 

![2](https://cloud.githubusercontent.com/assets/3640368/15804915/459b8c30-2b22-11e6-9115-1a877bb6076a.png)

Are you sure, you are using the newest source code ?

**Comment by hongbizi** [comment]
I see. thanks.

I did download the master branch but I will do it again to make sure.

**Comment by rsercano** [comment]
Please let me know, if it works for you, I'm planning to make a release today.

**Comment by hongbizi** [comment]
Works great.

Thanks:-)

**Comment by rsercano** [comment]
Finally I'm glad it works :) Thanks for your feedback !
