### ISSUE TITLE
Regex in find()

### ISSUE THREAD

**Issue by rithvikvibhu** [nosqlclient/nosqlclient#114]
Currently, it isn't possible to use regex in selector when querying find in a collection. I know it works in mongo shell, just need to allow it to pass through. Something like this:

``` js
{"name": /abc/i}
```

**Comment by rsercano** [comment]
Yeah, that's an enhancement for the next releases, but currently you can use it like:

``` js
{ "name": { "$regex": "(?i)a(?-i)cme" } }
```

**Comment by rithvikvibhu** [comment]
Thanks! It works. Should I close the issue or wait for the next release?

**Comment by rsercano** [comment]
Let's just leave this here for further reference :)

**Comment by rsercano** [comment]
This's so much effort to solve, current implementation in 2.0.0 supports all restrictions of `$regex`. So `$regex`is way to go for now.
