### ISSUE TITLE
Docker image is huge

### ISSUE THREAD

**Issue by haswalt** [nosqlclient/nosqlclient#117]
The docker image is currently giant considering what's included in it.

Expect a PR with a new Dockerfile soon :)

**Comment by rsercano** [comment]
Indeed, I would gladly accept this :)

**Comment by zapaz** [comment]
hi, seems there is a good proposition here  :
https://github.com/spidercpsf/mongoclient
https://hub.docker.com/r/giangndm/mongoclient/

**Comment by rsercano** [comment]
Hi, thanks trying this one: https://github.com/spidercpsf/mongoclient, but as far as I know, that's an ancient project `FROM meteorhacks/meteord:onbuild`

**Comment by zapaz** [comment]
just replace meteorhacks with kadirahq to get last version with meteor 1.4 :
https://github.com/kadirahq/meteord

but there is a better way: you can build your app, then create a small image from an official node image, as you can see here : 
  https://github.com/markoshust/docker-meteor/blob/master/Dockerfile

Just add  in your bundled directory a Dockerfile with only :
`FROM markoshust/meteor`
then :
`docker build -t mongoclient/mongoclient:latest .`
`docker push mongoclient/mongoclient:latest`

**Comment by rsercano** [comment]
gotta try automated build with `FROM markoshust/meteor` thanks

**Comment by rsercano** [comment]
No chance:

> Step 1 : FROM markoshust/meteor
> [91m# Executing 2 build triggers...
> [0mStep 1 : ADD . /opt/app
> Step 1 : RUN cd /opt/app/programs/server   && ([ -f package.json ] || npm init -f)   && npm i --loglevel=silent --unsafe-perm
>  ---> Running in b41c136997a7
> [91m/bin/sh: 1: cd: can't cd to /opt/app/programs/server
> [0mRemoving intermediate container 255fdeb9dcf2
> Removing intermediate container b41c136997a7
> The command '/bin/sh -c cd /opt/app/programs/server   && ([ -f package.json ] || npm init -f)   && npm i --loglevel=silent --unsafe-perm' returned a non-zero code: 2

**Comment by zapaz** [comment]
Did you 'meteor build' first ?

You can try this, in your app directory :

```
meteor build /tmp --directory
cd /tmp/bundle
echo 'FROM markoshust/meteor' > Dockerfile
docker build -t mongoclient/mongoclient:latest .
docker push mongoclient/mongoclient:latest
```

**Comment by rsercano** [comment]
It's an automated build on hub, I don't want to do any manual push, but it's not working with mentioned docker file :(

**Comment by rsercano** [comment]
since no help comes out, closing this for now
