### ISSUE TITLE
Advanced replica set, shard support 

### ISSUE THREAD

**Issue by rsercano** [nosqlclient/nosqlclient#12]
This is a further feature, and this issue is just a commit tracker.

**Comment by GbalsaC** [comment]
@rsercano 
Loving MongoClient, best Meteor Tool to monitor a Meteor App Cluster. 
In my setup, I'm looking to configure Sharding using Mongo 3.2 (I'm using Meteor 1.4) and was wondering if this is supported in MongoClient and which issues/considerations might I face using this tool as my monitoring UI?

**Comment by rsercano** [comment]
Hello @GbalsaC 

thank you so much for your great opinions :) But Mongoclient is not a meteor specific application, you can monitor any MongoDB setup with Mongoclient, it's written in MeteorJS.

Mongoclient version 2.0.0 is about to be released in **two weeks**. It will come with huge changes, for example it'll come with an additional edition (Enterprise) which will be paid version. But the community version (Mongoclient you know) will never change. Enterprise version comes with special features such as saving chart datas, emails for monitoring, (ram, cpu etc.. alerts) shard/replica management and more... 

There'll be a brief documentation as soon as it gets released, you can reach this documentation even now from this repo: [mongoclient-docs](https://github.com/mongoclient/mongoclient-docs) (Download the repo and open **index.html** in your browser)

We're already using **Mongoclient** for managing, monitoring our production MongoDB deployments in my company and I know there're a lot of companies that doing same thing. So I'll suggest you to read that documentation, and use [docker](https://hub.docker.com/r/mongoclient/mongoclient/) which will isolate Mongoclient from your server and lets you to use it without thinking about damages that Mongoclient can cause on your server (which I've never encountered)

Mongoclient supports connecting replica sets/sharded clusters. And supports **MongoDB 2.6 to 3.4** version range

**Comment by GbalsaC** [comment]
Excellent News!
I'm implementing my own cluster in DigitalOcean, for the sole reason of latency between AWS and Digital Ocean, since my other accessible option was MongoDB Atlas.
I'm pretty sure I'll be using Mongoclient 2.0 as admin interface for my cluster as a practical alternative to Mongo Compass.
Thanks for the excellent work and I'll be waiting for the enterprise version :)

**Comment by rsercano** [comment]
Thank you so much @GbalsaC :)

**Comment by rsercano** [comment]
Version 2.0.0 has been released
