### ISSUE TITLE
Allow us to query with impure JSON

### ISSUE THREAD

**Issue by saikojosh** [nosqlclient/nosqlclient#125]
- Allow us to query without the opening and closing **{** and **}**.
- Allow us to query without needing to quote our property names e.g. "my_field" and "$or".
- Allow us to quote values with **'** as well as **"** in queries.

I want to be able to copy and paste source code straight into the query field with minimal changes. Impure JSON can easily be converted to pure JSON with a regular expression.

**Comment by rsercano** [comment]
That's a nice idea and definitely in the queue. As soon as I get some free time after my marriage I will focus more on these, also I would like to have pull request for these :)
