### ISSUE TITLE
Can't save dump path

### ISSUE THREAD

**Issue by blocklogic-au** [nosqlclient/nosqlclient#126]
Using MongoClient on a mac with the mac portable download version 1.2.2 [here](https://github.com/rsercano/mongoclient/releases/)

I cannot seem to get the dump feature to work. Would report a background process was taking a dump, but never completes. I found the setting to update the dump path, but changing that to a path that exists and saving doesn't save the path.

Cheers
Ben

**Comment by blocklogic-au** [comment]
creating the default directory and making it world writable works fine

**Comment by rsercano** [comment]
Thanks for feedback, I will have a look at this whenever I get some free time.
