### ISSUE TITLE
Add healthcheck to mongoclient

### ISSUE THREAD

**Issue by DrSmirnov** [nosqlclient/nosqlclient#128]
I'm currently deploying mongoclient via marathon. Therefore it would be great to have a simple healthcheck endpoint within the application. As I'm not familiar with meteor.js I'm not sure if my approach is correct. I just created a file at lib/routers/healthcheck.js and added:

```
Router.route('/healthcheck', function() {
    this.response.statusCode = 200;
    this.response.end("Server is up and running");
}, { where: "server" });
```

Would be nice if you could add this to the code base. But I haven't tried yet if this is still working with BasicAuth enabled.

**Comment by rsercano** [comment]
Hi there again, 

you can create a pull request and I will evaluate it, and your approach seems okay for me at first glance.

Cheers
