### ISSUE TITLE
Mongodb-Restore throws the error: missing root option  on centos7.x and centos6.x platform

### ISSUE THREAD

**Issue by zqr688** [nosqlclient/nosqlclient#131]
# Hi ,The error information:

> info: [restoreDump] mongodb://localhost:27017/mongoclient _id=oLP2vBc39rZmn2hRr, filePath=/root/myDumps//mongoclient_1467707978272.tar, date=Tue Jul 05 2016 16:39:38 GMT+0800 (CST), connectionName=localhost, connectionId=A95cNc2TfmmpvZH2z, sizeInBytes=4608, status=In Progress
> **error: [restoreDump] Error: missing root option**
> **at restore (/opt/tests/bundle/programs/server/npm/npm-container/node_modules/mongodb-restore/index.min.js:212:30)**
>     **at [object Object].Meteor.methods.restoreDump (server/mongodb/methods_dump_restore.js:14:1)**
>     **at maybeAuditArgumentChecks (livedata_server.js:1698:12)**
>     **at livedata_server.js:708:19**
>     **at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)**
>     **at livedata_server.js:706:40**
>     **at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)**
>     **at livedata_server.js:704:46**
>     **at tryCallTwo (/opt/tests/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)**
>     **at doResolve (/opt/tests/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)**

Message from syslogd@meteor at Jul  5 17:34:28 ...
 kernel:BUG: soft lockup - CPU#0 stuck for 30s! [node:44784]

**Is it a bug? And how to deal with it**

**Comment by rsercano** [comment]
Hello there, thanks for the feedback Mongoclient uses a npm package for dump/restore, I'll have a look at this asap.

Cheers

**Comment by zqr688** [comment]
OK, Thanks!

**Comment by rsercano** [comment]
If you have a chance to try again could you please try with latest source of mongoclient ?
