### ISSUE TITLE
Mongoclient.exe File is detected as Virus...

### ISSUE THREAD

**Issue by Nigel20** [nosqlclient/nosqlclient#132]
**Mongoclient.exe** File is being deteced as Virus by **Bkav** Antivirus ,must be a false positive. 

Just informing you.

Heres the link:

https://www.virustotal.com/en/file/5602c297a2e8c1d0d3e123502cf0806b09091528958fd16674f73454bb53b8fb/analysis/1468237522/

**Comment by rsercano** [comment]
Hi there,

thanks for the feedback, will take a look asap.

Cheers

**Comment by Nigel20** [comment]
Sure .. no problem

**Comment by rsercano** [comment]
That's too much effort to solve currently for further reference: https://github.com/atom/atom/issues/3927 and https://github.com/electron/electron/issues/4485
