### ISSUE TITLE
UI issue with JSONEditor

### ISSUE THREAD

**Issue by Alex-Werner** [nosqlclient/nosqlclient#133]
Hi, I have an issue with JSONEditor, making the client to go to databaseStats. 
This happens when I try to use a functionnality of jsonEditor (sort, type, apprends or insert) but work with duplicate. 
Another issue is that the contextMenu is too small to make all fit in it (by width) and too small to display all option (by height).

**Comment by rsercano** [comment]
Hello thanks for the feedback, which distribution are you using and at which resolution ?

**Comment by Alex-Werner** [comment]
Hi, 
I created this issues to reference the pull-request and for project management purpose (history of modification and reason of them).
I'm using Windows x64 10.1 at 1920x1080
