### ISSUE TITLE
Authorization not working

### ISSUE THREAD

**Issue by mohandutt134** [nosqlclient/nosqlclient#135]
Hi,
following this https://github.com/rsercano/mongoclient/wiki#…
I installed the mongoclient web app on my ubuntu server but when I open the home page that is http://localhost:8000/mongoclient, I get "Route Not Found' in front of me. When I go to dashboard, I get the connection setting which were save previously but no authorisation.

Can someone help me If I am missing something or is this a real issue.

Thanks

**Comment by rsercano** [comment]
Hello there if you haven't set root_url environment url then the base url is localhost:<port>, secondly if you want to enable authorization you need to set path variables correctly. Can you please double check ?

**Comment by rsercano** [comment]
Please reopen if you can't solve it.
