### ISSUE TITLE
Bug: Couldn't find a template named "databaseStats" or "databaseStats". Are you sure you defined it?

### ISSUE THREAD

**Issue by kevincaradant** [nosqlclient/nosqlclient#139]
![image](https://cloud.githubusercontent.com/assets/6093175/17202970/d6592004-549c-11e6-87d9-6bd96567e90a.png)

After the launch with meteor. I get this error. I haven't any dashboard :/ but the rest of the application works well .

Any idea ? Thank you :)

I'm running under centOs 6

**Comment by kevincaradant** [comment]
I close this issue because Unfortunately my environnement system for the test is finally destroyed. I hadn't enough time to find the solution but clearly, that seems to be a problem of rights. If you think this issue have to be reopened, you can, but i can't test so i closed it ;)

**Comment by rsercano** [comment]
Hi there,

that's the only bug report about that, if you encounter this again, please kindly reopen it :)

Cheers
