### ISSUE TITLE
Cannot connect through SSH

### ISSUE THREAD

**Issue by hailq** [nosqlclient/nosqlclient#140]
Does the ssh connection feature work? I cannot connect via SSH

**Comment by rsercano** [comment]
Hello of course it works, could you please compile from source and share the logs ?

Thanks & Cheers

**Comment by hailq** [comment]
I try and it keeps saying error "ehostunreach" .

**Comment by rsercano** [comment]
Are you behind a proxy or a firewall ? Or does your server  ?

**Comment by hailq** [comment]
I can connect normally using ssh, and i also can connect via ssh to mongo by other applications.

**Comment by rsercano** [comment]
Could you please try to compile mongoclient from source and share the logs ? 

Here's the section you should follow: https://github.com/rsercano/mongoclient/wiki#31-compile-from-source-browser-edition

**Comment by rsercano** [comment]
Please reopen if you get the logs or reproduce this
