### ISSUE TITLE
replica set?

### ISSUE THREAD

**Issue by RDevet** [nosqlclient/nosqlclient#144]
Is replica set supported?
For example:
rs0/host01:27017,host02:27017

**Comment by rsercano** [comment]
Hello, sure it's. Just use URL connection with all hostnames and ports.

**Comment by RDevet** [comment]
This is the structure of my URL but it is not working:
mongodb://username:password@host-01:27017,host-02:27017,host-03:27017/mydb?authSource=mydb&ssl=true

**Comment by rsercano** [comment]
What exact error do you get ?

**Comment by RDevet** [comment]
I get this error:
"Couldn't connect: no valid seed servers in list"

**Comment by rsercano** [comment]
Hi there again,

it's not about mongoclient, I guess you are trying to connect a secondary replica set, please research it on the web,  you need to modify your url a bit more regarding secondary replica set connection. 

You can search with this error: "**no valid seed servers in list**" which directly comes from mongodb.
