### ISSUE TITLE
Database Stats button didn't work

### ISSUE THREAD

**Issue by GabMgt** [nosqlclient/nosqlclient#146]
Second issue: In the web UI the button "Database Stats" didn't work for me. Zero logs when I click on. Is it a future feature?

Thank you very much!

**Comment by rsercano** [comment]
Not really, please carefully read the text under **Welcome** header. There should be some explanation.

**Comment by GabMgt** [comment]
I am not sure of what you meant. This "welcome header" ? 
"Couldn't find a template named "databaseStats" or "databaseStats". Are you sure you defined it?"

**Comment by rsercano** [comment]
Oh I see, than which distribution are you using ?

**Comment by GabMgt** [comment]
I'm using Ubuntu 16.04 x64 with Docker 1.11.2.

And the MongoDB version is 3.2.6

**Comment by rsercano** [comment]
I suspect that, that can be about root url, are you behind a proxy ? or are you using mongoclient as a different url than root url ? (not like: localhost:3000)

**Comment by GabMgt** [comment]
Nope, I see this message on: http://127.0.0.1:3000/

PS: I didn't modified the docker container

**Comment by rsercano** [comment]
When you use F12 developer console, do you see any error ?

**Comment by GabMgt** [comment]
Yes, two errors:

```
16:46:22.586 The connection to ws://127.0.0.1:3000/sockjs/333/8zgu964r/websocket was interrupted while the page was loading.1 ddp-client.js:1363:14
16:46:22.586 The connection to wss://ws.pusherapp.com/app/a809f5e48a0842a3c967?protocol=7&client=js&version=3.0.0&flash=false was interrupted while the page was loading.1 pace.min.js:2:6616
```

**Comment by GabMgt** [comment]
I just noticed that the stats works on Chrome. I was using Firefox since that moment.

**Comment by rsercano** [comment]
Thanks for the information, I'll try to reproduce this issue

**Comment by rsercano** [comment]
Couldn't reproduce on any browser, if you encounter that again please re-open this with the details
