### ISSUE TITLE
[Feature request] data explorer

### ISSUE THREAD

**Issue by GabMgt** [nosqlclient/nosqlclient#147]
Hello, mongoclient doesn't have a feature to explore the data. Like Mongo Management Studio, you should create a collection explorer or just  add an automatic cursor when the user get too many results, example:

When I create a request like db.collection.find({}) if it returns to many results, a paginator appears on the bottom of the page.

Thank you very much.

**Comment by rsercano** [comment]
Indeed, thanks for feedback, that points #66  already. I'm going to close this as duplicate :)
