### ISSUE TITLE
new collections are not added

### ISSUE THREAD

**Issue by ghost** [nosqlclient/nosqlclient#152]
Hi

I had a problem extracting the zip file of windows 64bit. I reported about it in its own older issue. I was told to try and work with it despite the error. so it is working but when creating a new collection it says the collection is created but I don't see it in the list of collections.

Not sure if it's relevant to the extraction problem or not.

**Comment by ghost** [comment]
OK, I deleted the data folder completely and restarted the server and now it's ok, sorry for the troubles. I can't seem to delete my own post.

**Comment by rsercano** [comment]
Hello, no problem at all, you can raise a new issue as soon as you encounter anything :)
