### ISSUE TITLE
null values on array, trigger internal server error

### ISSUE THREAD

**Issue by neshte** [nosqlclient/nosqlclient#153]
https://github.com/rsercano/mongoclient/blob/master/server/mongodb/helper.js#L163

If I have a null value on my record, and I query a find that results in this record being returned, this line on the server tries to call .toString() of null and it triggers an error.

maybe changing that condition to:

``` javascript
if (objectID.isValid(obj[property][i])) {  
    obj[property][i] = obj[property][i];  
}else if(objectID.isValid(obj[property][i].toString())){
    obj[property][i] = obj[property][i].toString();
}else{
    convertObjectIDsToString(obj[property][i]);
}
```

have not tested it.

**Comment by rsercano** [comment]
Thank you so much for feedback, will take care of this asap

**Comment by rsercano** [comment]
Hi again,

I couldn't reproduce this issue. Here's the related screenshot:

![1](https://cloud.githubusercontent.com/assets/3640368/17829885/f1601ff8-66c4-11e6-8572-8e36439994a0.png)

**Comment by rsercano** [comment]
Also there's a control at upper of the specified line:

`if (obj.hasOwnProperty(property) && obj[property] != null) {
`

**Comment by stalmok** [comment]
I can confirm that the issue is still there. It's when a null value is in the array.

On line 163, it's calling `toString` on `obj[property][i]`, which is not checked for `null` values.

**Comment by rsercano** [comment]
Oh I see, will check that. Thank you

**Comment by neshte** [comment]
Yes, sorry, is just if the null value is inside an array, that was my situation, I've just updated the issue name, changing nullValue: null to nullValue: [null] should trigger the exception...
