### ISSUE TITLE
could not unzip on windows 7

### ISSUE THREAD

**Issue by romberli** [nosqlclient/nosqlclient#155]
i downloaded the windows-portable-x64.zip, 
when i tried to unzip this, it turned out that the directory and file longger than 260 characters,
is there any solution?

**Comment by romberli** [comment]
sorry, it's low version of winrar problem,i've fix this issue, 
sorry to disturb you.

**Comment by rsercano** [comment]
Hello,

no problem at all, I'm glad your issue is fixed.

duplicate of #81
