### ISSUE TITLE
Icon on mac os

### ISSUE THREAD

**Issue by satanworker** [nosqlclient/nosqlclient#157]
At first, thanks a lot for such an awesome app, but icon on osx has opacity on eyes and it loks a bit crippy :)
here is a gif, may be it was design decision if so, just close the issue
![aug-25-2016 02-09-55](https://cloud.githubusercontent.com/assets/11026240/17951220/28ec4d64-6a69-11e6-870c-18b83af80039.gif)

**Comment by rsercano** [comment]
Hello, thanks for your kind opinions. I need to fill his eyes with white color, thanks for reminding this :)
