### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ericandrewlewis** [nosqlclient/nosqlclient#158]
Hi, thanks for making this :smile: 

I'm a linux user running Linux Mint 18 with Cinnamon.

I can download the linux distribution of the app and run it from my terminal (`./Mongoclient`).

Is there a preferred place I should put this on my hard drive? How can I make my system aware that it is an application, so I can find it from my Cinnamon desktop application's menu?

**Comment by rsercano** [comment]
Hello,

thanks for your kind opinions :) But there's no need to install Mongoclient to execute, and adding it as a menu object is not about Mongoclient.

Have a look at here: http://askubuntu.com/questions/232053/how-to-add-a-shortcut-to-a-command-to-the-cinnamon-menu

Cheers

**Comment by ericandrewlewis** [comment]
Okay cool, I'll probably put it in `/opt/` and add it to my menu as in the link you shared. Thanks!
