### ISSUE TITLE
Strange behaviour on saving string "BVB|Dortmund"

### ISSUE THREAD

**Issue by sebastian-heinz** [nosqlclient/nosqlclient#159]
Hello, not sure what happens but 

I have following document in my mongoDb:

[
{
    "_id": "57c501ef97d3d283a5602651",
    "companyId": "Test"
  }
]

I then

1) Execute find query
2) edit companyId value to string "BVB|Dortmund" and click save.
3) Execute find query, companyId is now "4256427c446f72746d756e64"

**Comment by rsercano** [comment]
Hello,

thanks for the feedback, have you tried with unchecking top checkbox (Convert valid ObjectIDs checkbox) ?

Cheers

**Comment by rsercano** [comment]
I've tried this, and if you unecheck right upper checkbox which makes the valid object id conversion, it will be okay. I guess **BVB|Dortmund** is a valid object ID :)

**Comment by amihajlovski** [comment]
I have the same problem with mongoose. Can you tell me what is the setting that should be set for disabling this behaviour?

**Comment by rsercano** [comment]
@amihajlovski 

Unfortunately I'm not using mongoose, mongoclient uses native mongodb nodejs driver, and current version has fix for this issue without a checkbox. See breaking changes inside of mongoclient latest version.

**Comment by amihajlovski** [comment]
​​
Can you tell me what happens when checkbox is checked and not? What is the difference?

**Comment by rsercano** [comment]
Before 1.3.0 Mongoclient was using **automatic BSON conversion**, from 1.3.0 now uses **extended json** Therefore there're no checkboxes in newer versions, but for the older ones, there're 2 checkboxes to control **ISODate** and **ObjectId** conversions.

So, you shouldn't see any checkboxes in [1.5.0](https://github.com/rsercano/mongoclient/releases/latest)
