### ISSUE TITLE
1.3.0 Windows Portable Client Does Not Start in Windows 10

### ISSUE THREAD

**Issue by ghost** [nosqlclient/nosqlclient#161]
Twice I downloaded and unpacked the files (to the root of my drive because Windows was complaining when I tried to unpack to my desktop about the path being too long!), restarted my PC, and has yet to load when tried with/without admin privileges and in even compatibility mode.

1.2.2 works perfectly fine (without the fact that something's fucked with the way the ZIP file is built, as Window's built in unpacker has issues, but with 7zip it worked fine) and started the first time I ran the executable.

**Comment by rsercano** [comment]
Hello, thanks for the feeback, will have a look at this asap.

**Comment by rsercano** [comment]
Confirmed, it hangs during meteor's internal mongodb startup somehow, will try to fix this today.

**Comment by rsercano** [comment]
Could you please retry, it should be fixed now, added SSL dlls.

**Comment by ghost** [comment]
Works perfectly! Thanks so much for the quick fix. Sorry I wasn't on yesterday to confirm.
