### ISSUE TITLE
start mongoclient with runtime environment PORT

### ISSUE THREAD

**Issue by jiangytcn** [nosqlclient/nosqlclient#162]
Is it possible to start mongoclient with port obtained from runtime environment ?
what i want to do is pushing the mongoclient as an app to Bluemix

**Comment by rsercano** [comment]
Hi,

as you know Mongoclient is a meteorJS application, I assume you want to obtain port from environment variables. 
Unfortunately, **meteorJS** doesn't offer an environment variable to startup application from given port, you have to provide `--port` argument. But that can be easily set by a small script by fetching environment variable and starting **Mongoclient** from that fetched port.

Cheers

**Comment by jiangytcn** [comment]
roger that 👍
