### ISSUE TITLE
how to run a raw query?

### ISSUE THREAD

**Issue by jcollum** [nosqlclient/nosqlclient#164]
I've got an aggregation that I am running in RoboMongo: 

```
db.getCollection('appts').aggregate([
  {
    $match:{
      'UpdatedOn':{$gt:new Date('2016-02-01'), $lt:new Date('2016-02-29')},
      // 'ClientID': '187119',
      'Charges':{$gt:0}
    }
  },
  {
    $group:{
       _id: {ClientID: '$ClientID'}, 
      // _id: null, 

      ChargesTotal:{$sum:'$Charges'}
    }
  }
]);
```

Works fine. But when I grab the aggregation array (everything inside the call to `aggregate`) and paste it into the aggregate query window in this tool, all I get is an error about "Broken JSON boolean" near `$gt:new Date('2016-02-01'),`.

I'd like to open a query file and run it rather than having to reformat my aggregation to fit a new format. Is there a way to do that with this tool? Even copy-paste would be OK, but less than ideal.

**Comment by rsercano** [comment]
You don't need to execute a raw query in mongoclient that's the idea. You can just type your date like: "2016-02-29 00:00:00" this format is specified under selectors.  And just type it like a string. As well as your object IDs should be strings these are automatically converted into objectID objects. You can disable this auto convert by right upper corner checkboxes.

**Comment by jcollum** [comment]
I see. I would prefer to be able to use the raw query though, since I need a query that I can also run via my node.js code. Just a suggestion.

**Comment by rsercano** [comment]
I understand your concerns, that's not a bad idea. But Mongoclient currently uses nodejs native mongodb driver, and unfortunately mongodb doesn't support such a feature. In older versions of mongodb there was an `eval` command but it's deprecated since **3.2**
