### ISSUE TITLE
how to import data to my database using mongoclient

### ISSUE THREAD

**Issue by jiangytcn** [nosqlclient/nosqlclient#165]
Hi, 

I deployed the master branch of Mongoclient which built from scratch.
As i cannot reach to the DB, but mongoclient could.So i want using mongoclient to import the initial datas into the DB. So the question is , what the data format the mongoclient support ?

**Comment by rsercano** [comment]
Hello,

by version 1.3.0, you should be able to use impure JSON objects/arrays as well as fully valid JSON objects/arrays. Therefore:

```
{
  "myKey": "213",
  "myOtherKey": true,
  "mySecondKey": 123
}
```

```
{
  myKey: "213",
  myOtherKey: true,
  mySecondKey: 123
}
```

These are both should supported for insertMany query.

**Comment by jiangytcn** [comment]
Can i using database restore, as there are much collections

**Comment by rsercano** [comment]
Unfortunately current restore operation only supports Mongoclient's dump function, but you can give it a shot. It's experimental currently.

**Comment by jiangytcn** [comment]
Ok, but what the format is it ? a single tar ball is ok ?

**Comment by rsercano** [comment]
You have to extract it first, then you should enter a database dump entry to mongoclient's internal database manually. That's a hard job to do if you are not relevant to it.

**Comment by jiangytcn** [comment]
@rsercano let us clarify the workflow
1. using mongodump to dump the initial data
2. upload the tar package of the database above
3. update mongoclient internal dump collections point the the tar package created above
4. import the dummy dump

But for now , i ran into an issue, which shows import status `error`

> 2016-09-01T14:10:52.97+0800 [App/0]      ERR error: [restoreDump] Error: missing root option
> 2016-09-01T14:10:52.97+0800 [App/0]      ERR     at restore (/home/vcap/app/.meteor/heroku_build/app/programs/server/npm/node_modules/mongodb-restore/index.min.js:212:30)
> 2016-09-01T14:10:52.97+0800 [App/0]      ERR     at [object Object].restoreDump (server/mongodb/methods_dump_restore.js:14:13)
> 2016-09-01T14:10:52.97+0800 [App/0]      ERR     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
> 2016-09-01T14:10:52.97+0800 [App/0]      ERR     at packages/ddp-server/livedata_server.js:711:19
> 2016-09-01T14:10:52.97+0800 [App/0]      ERR     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
> 2016-09-01T14:10:52.97+0800 [App/0]      ERR     at packages/ddp-server/livedata_server.js:709:40
> 2016-09-01T14:10:52.97+0800 [App/0]      ERR     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
> 2016-09-01T14:10:52.97+0800 [App/0]      ERR     at packages/ddp-server/livedata_server.js:707:46
> 2016-09-01T14:10:52.97+0800 [App/0]      ERR     at Session.method (packages/ddp-server/livedata_server.js:681:23)
> 2016-09-01T14:10:52.97+0800 [App/0]      ERR     at packages/ddp-server/livedata_server.js:551:43
> 2016-09-01T14:11:04.22+0800 [App/0]      OUT info: [getFileInfos] fs

**Comment by rsercano** [comment]
I'll be able to check this after work, @jiangytcn. If you have a chance to use insertMany please do so, otherwise I'll try to present you a workaround.

**Comment by jiangytcn** [comment]
Okay, i suppose you mean`insertMany` in a collection, right?
as i have 70 collections, a little bit annoying :(
