### ISSUE TITLE
I need example about dealing with dates

### ISSUE THREAD

**Issue by hishambakr** [nosqlclient/nosqlclient#169]
Many thanks for great product.
I am new to mongodb and spent all the day trying to delete records older than a month from my remote database using mongoclient but I failed.

Appreciate your support by giving an example about deleting records older than a month.

my database records look like:

{
  "_id": "002NhoeFyS",
  "enclosureUrl": "http://pbs.twimg.com/media/CftS-mpWsAAgvUB.jpg",
   "isBodyExist": false,
 "published": "2016-04-10 23:24:34",
  "enclosureType": "image/jpeg",
  "url": "http://goo.gl/zwnsrf",
  "_updated_at": "2016-04-11 10:29:42",
  "readCount": 3,
  "_created_at": "2016-04-10 23:25:16"
}

**Comment by rsercano** [comment]
Hello, 

as I've explained this on [here](https://github.com/rsercano/mongoclient/wiki/Frequently-Asked-Questions#2-how-mongoclient-interprets-objectids-and-isodates-) you need to write your query as string for dates. Mongoclient automatically converts valid formats to ISODate objects.

In your situation, your selector on delete query should be like:
for Mongoclient 1.2.2 and older versions:
`{"_created_at":{"$lte":"2016-08-04 00:00:00"}}`

for 1.30, above would work and:
`{_created_at:{$lte:"2016-08-04 00:00:00"}}`

These date formats are specified under selectors. 

Cheers
