### ISSUE TITLE
Pointer cursor on hover over links

### ISSUE THREAD

**Issue by janniks** [nosqlclient/nosqlclient#173]
Please think about adding `cursor: pointer` to all items in the UI that are clickable. Without this, it can be confusing what is a button and what is not.

Thank you,

**Comment by rsercano** [comment]
Hello,

thanks for the feedback, will check this.

Cheers

**Comment by rsercano** [comment]
Hi there, 

it seems like all buttons have this property. Would you mind to reopen this just in case you find a button or a link which's missing the property ?
