### ISSUE TITLE
Mongoclient web application auth problem

### ISSUE THREAD

**Issue by webbipage** [nosqlclient/nosqlclient#174]
Hello I just build a mongoclient on my web server, but I wanna protect this app so that another people can't access it. Don't know how to have a right configuration so that to make the authentication works. Seems I can't set MONGOCLIENT_AUTH to 'true' or it doesn't works because I can login to the web application with no username and password entered. My mongodb is secured but I just don't want another people can use this app on my server. How can I tackle this problem? Thank you.

**Comment by webbipage** [comment]
It is solved because I forgot to add ' to the begin and the end of the username and password in startup.js. Thank you so much.

**Comment by rsercano** [comment]
@ireaas1 Hello, I'm glad your issue is fixed, don't hesitate to re-open this in any case :) 

Cheers
