### ISSUE TITLE
OS X binary shows version as 0.35.6, for version 1.3.0

### ISSUE THREAD

**Issue by ajmas** [nosqlclient/nosqlclient#177]
OS X binary shows version as 0.35.6, even though the release link indicates it should be 1.3.0. The version file also indicates 0.35.6. Files dates are 30 August 2016.

This should probably be addressed, since it is likely to cause confusion during support requests.

**Comment by rsercano** [comment]
Hello, 

you're absolutely right. The mentioned version is the electron version, I'm planning to put an about section in desktop portables will plan this to next release.

Thanks,
Cheers
