### ISSUE TITLE
Ask password on connect

### ISSUE THREAD

**Issue by techninja1008** [nosqlclient/nosqlclient#179]
A nice to have feature would be if on a connection at least one of the fields in the authentication tab is filled in, but not all of them, when you connect it asks for the others, but **does not save them**

**Comment by rsercano** [comment]
Hello,

I couldn't get your point, do you want mongoclient to save missing information on connections even user doesn't fill them ?

**Comment by techninja1008** [comment]
Sorry, I meant that if you try to connect to a database with authentication
info only partially filled in, it prompts you for missing data, but doesn't
save said data.

**Comment by rsercano** [comment]
I'm sorry but still can't get it, could you please kindly provide a screenshot to demonstrate what you mean ?

**Comment by rsercano** [comment]
Unfortunately (as far as I understand) mongoclient can't save missing filled connection information which can cause unexpected errors.
