### ISSUE TITLE
Where are settings stored?

### ISSUE THREAD

**Issue by manast** [nosqlclient/nosqlclient#180]
Hello,

I am running mongoclient from a docker container, it works well and everything, but everytime I restart the container the settings are cleaned. How can I configure the container so that the settings are stored in a external volume?

**Comment by rsercano** [comment]
Hi there,

settings are being stored in meteor's local mongodb. You can start mongoclient with exporting mongodb_url and it'll connect another one which can be an external mongodb.

`export MONGO_URL=mongodb://localhost:27017/your_db`

But it's strange that it's being cleaned, will check this. Are your connections getting reseted too ?

Cheers

**Comment by Darkheir** [comment]
Same here.

When the docker container is stopped and restarted the connections are still present, but if I remove the container then the data will also be removed (it makes sense).

The usual way to keep the data is to declare a volume in the Dockerfile. This way the data is persisted even if the container is removed and recreated.

Here's an example from MongoDB official Dockerfile

```Dockerfile
...
VOLUME /data/db /data/configdb
...
```

Source: https://github.com/docker-library/mongo/blob/b37a4891feffeafb77febd2833d96b59cf28d6a8/3.0/Dockerfile

**Comment by rsercano** [comment]
Thank you so much for the explanation, I'm kind of newbie on docker, and would like to accept a PR, help from anyone who knows better.

**Comment by Darkheir** [comment]
No problem, I can help you! The thing is I'm not a Javascript developer so I will need some help! 

Do you know where the mongo database is currently stored on the disk ? 
Or do you know the url that is used to access it ?

**Comment by rsercano** [comment]
Of course, actually meteorjs starts a mongodb process internally, and keeps this in it's build. But mongodb can be externalized. Default url is: `127.0.0.1:3001/meteor`

**Comment by Darkheir** [comment]
Ok so may be we could mount a volume on  `/opt/mongoclient/.meteor/local/` or `/opt/mongoclient/.meteor/local/`if it must be persisted when the container is recreated. Another way would be to specify to meteor where it should store the mongo data and mount this volume.

**Comment by rsercano** [comment]
Maybe it would be better to keep mongodb as an external service and start. And then 
`export MONGO_URL=mongodb://localhost:27017/meteor`

this is what meteor checks before starting, but actually I'm struggling to do that.

**Comment by Darkheir** [comment]
Ok so maybe we should extend the MongoDB docker image instead of Debian.

I will try to do it next week if I have the time.

**Comment by rsercano** [comment]
Thank you !!
