### ISSUE TITLE
:latest docker image seems to be broken

### ISSUE THREAD

**Issue by manast** [nosqlclient/nosqlclient#181]
Hello,

I updated to the latest mongoclient docker image and when the container starts I get this error:

```
[[[[[ /opt/mongoclient ]]]]]

=> Started proxy.
=> Started MongoDB.

Unable to resolve some modules:

  "matches-selector" in
/opt/mongoclient/node_modules/component-closest/index.js (web.browser)
  "query" in /opt/mongoclient/node_modules/component-matches-selector/index.js
(web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save matches-selector query

=> Started your app.

=> App running at: http://localhost:3000/
```

for some reason it is not accepting any connections, it worked with an older version. It would be great if you could actually tag the images, so that we can use the stable ones or rollback if we find issues...

**Comment by rsercano** [comment]
Hello,

I'm actually trying to keep this image updated and stable, since it's bound to master branch.
Now checking this, sorry for the inconvenience. 

Cheers

**Comment by rsercano** [comment]
Hi there, 

clipboardjs was causing this issue, and I've removed it. It was a dependency for mongoclient because of usermanagement section external links. 

I'll try to find a workaround for this later.

Could you please retry as soon as docker hub finishes build ?

Cheers
