### ISSUE TITLE
Autocomplete feature for selectors doesn't work

### ISSUE THREAD

**Issue by guodage** [nosqlclient/nosqlclient#185]
installed by docker
I have enabled Autocomplete feature for selectors in setting and the collection has only 1 document.
But I can't see autocomplete either in Chrome or Safari. 
I like mongoclient, autocomplete make the world better.

**Comment by rsercano** [comment]
Hello,

thanks for the feedback, gotta check that.

Cheers

**Comment by rsercano** [comment]
Please re-pull docker hub after a few minutes. (As soon as automated build finishes.)
