### ISSUE TITLE
Cannot access from outside

### ISSUE THREAD

**Issue by ghost** [nosqlclient/nosqlclient#186]
Hi there, i've just fired up a brand new ubuntu docker droplet and installed the docker Distribution.
i started it on the Server, but i cannot Access it via http://ip-address:3000 from anywhere outside on my browser any suggestions?

**Comment by rsercano** [comment]
Hello,

did you bind port with -p command ? What exact command did you execute to start docker image ?

**Comment by ghost** [comment]
i used this command: _docker run -d -p 3000:3000 mongoclient/mongoclient_
the port is open but i cannot Access it.
i found there is aproblem that there is no dbfolder/path for mongodb...
where can i find the mongodb.conf? it usually is in /etc/mongodb.conf but i don't know where to find it in docker

**Comment by rsercano** [comment]
Can you please start without -d switch and see what's wrong  with it ?

**Comment by ghost** [comment]
okay, so the Output is following:
`
root@dockerserver:~# docker run -p 3000:3000 mongoclient/mongoclient
[[[[[ /opt/mongoclient ]]]]]

=> Started proxy.
=> Started MongoDB.`
it stays right like this now for about 5 minutes and is not accessible from outside.
should i create a temporary user in the docker Group for you to check it out?

**Comment by ghost** [comment]
Uh, ist running now...don't know it why but i've set up a new droplet and now it works :)

**Comment by rsercano** [comment]
At first run it take a while since meteor setups some stuff, I'm glad your issue has fixed.
