### ISSUE TITLE
distinct query doesn't seem to work with selector.

### ISSUE THREAD

**Issue by jmbldwn** [nosqlclient/nosqlclient#187]
"distinct" query with no selector returns 4 results:
https://www.dropbox.com/s/7emhqi9ygcom8g2/Screenshot%202016-10-14%2015.51.47.png?dl=0

Add a selector, and no results:
https://www.dropbox.com/s/ctfqw1wgv2c8ora/Screenshot%202016-10-14%2015.52.45.png?dl=0

This is independent of whether the field being queried is in the selector:
https://www.dropbox.com/s/5j1sknfcfz1e9yw/Screenshot%202016-10-14%2015.53.45.png?dl=0

Any ideas?

**Comment by rsercano** [comment]
Hello,

thanks for the feedback, gotta check that asap.

**Comment by rsercano** [comment]
It seems like working in my case:

**findOne:**
![1](https://cloud.githubusercontent.com/assets/3640368/19410106/335b4fd8-92ec-11e6-92a8-c733faa9604c.PNG)

**distinct:**
![2](https://cloud.githubusercontent.com/assets/3640368/19410107/33603fa2-92ec-11e6-9c99-0cb66d8328a7.PNG)

**Comment by jmbldwn** [comment]
I finally realized it was interpreting the hex string as an ObjectID.  This field isn't an ObjectId (it isn't necessarily hex) so I was blindly ignoring the advice you put right under the selector entry. :-)

I guess there's no way for you to know if it needs to be an ObjectID.  Other tools like MongoHub force me to put ObjectID() around the hex string if that's what it is.

Deselecting the checkbox made it work for me.

By the way, I came to find out that this type of query (distinct with a selector) isn't leveraging indexes and is terribly inefficient.  I couldn't find in the mongoclient UI a place to run a command and get back the "stats" field, so to debug this I had to log into my mongodb container directly to figure out what was going on.

Is there a way to get "stats" back from a query?

**Comment by rsercano** [comment]
Oh I see, unfortunately currently you can only **setProfilingLevel** and see what's going on, other than that I can plan this feature for the next release. (**explain** command)

Thanks for your feedback

**Comment by jmbldwn** [comment]
Happy to help.  Great tool.  Thanks for making it!

On Oct 15, 2016, at 10:07 AM, Sercan Özdemir <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh I see, unfortunately currently you can only setProfilingLevel and see what's going on, other than that I can plan this feature for the next release.

Thanks for your feedback

**Comment by rsercano** [comment]
Thanks for your kind opinions, really appreciated :)
