### ISSUE TITLE
Cannot update queried documents without ObjectID checkbox marked

### ISSUE THREAD

**Issue by Cazra** [nosqlclient/nosqlclient#198]
I'm running into a problem where I can't update documents from a query unless the checkbox for interpretting ObjectID strings is checked. If it's checked, then I can update them just fine, but if it's unchecked, it doesn't update the documents when I click save.

**Comment by rsercano** [comment]
Hello there,

that's the default behaviour of mongoclient, I guess you are using an object ID query for your selector, so you need to convert it to objectID which means you MUST check right upper corner checkbox.
