### ISSUE TITLE
Modifying a document may break it

### ISSUE THREAD

**Issue by manast** [nosqlclient/nosqlclient#201]
First of all, thanks for a great product that is nice and easy to use. It works quite well for the most part. However I am having a very annoying issue that I think is related to some kind of auto type conversion feature.
The problem happens when I edit a document, it seems that it is automatically changing the type for values that look like ObjectIds. For example, I have a field that should have a string, it has a value like this: 580895f56614c0060078a38f
As soon as I edit _any_ field in that document, that value gets saved and converted to an ObjectId, so my queries stop working... and I cannot find any way to actually change that value back to a string at least not with mongoclient.

There are 2 major issues here as far as I can see:
1) When I modify 1 field in a document it should ONLY modify that field when saving, not re-saving the whole document.
2) It should not do any automatic conversions of types, and surely not in a invisible way for the user.

Finally it would be nice to show the type of every field, it took me a lot of time to understand that my string was converted to an ObjectId...

**Comment by rsercano** [comment]
Hello,

thank you so much for your kind opinions. You're right about type conversion. 

But to clarify it, which version and portable (osx, linux, windows) are you using ? Or are you using current master branch as a web application ?
Secondly, are you using **save** button under `find` query or are you using `updateMany` query or `easy edit` ?

Apart from that, you can disable automatic **objectID and ISODate** conversion from right upper corner checkboxes. 

I'm planning to show types for fields soon but probably wont be in next release.

**Comment by manast** [comment]
We are using the web version, taken from docker hub 2 or 3 weeks ago, I can give you the version number later if it is important.
I was using the save button after doing a find.
I did not know about updateMany or easy edit actually, I have to check those out.

**Comment by rsercano** [comment]
Thanks for the feedback, gotta find a way to clarify type conversion asap.
