### ISSUE TITLE
Problem with ssh tunnel connection: Can't find npm module 'tunnel-ssh'

### ISSUE THREAD

**Issue by zarej** [nosqlclient/nosqlclient#205]
Ive downloaded linux version from: https://github.com/rsercano/mongoclient/releases/download/1.3.0/linux-portable-x64.zip

When I try to connect to database using ssh tunnel I got response:

Error inside the Async.runSync: Can't find npm module 'tunnel-ssh'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?

**Comment by rsercano** [comment]
Hello,

thanks for the feedback, gotta check this asap.

**Comment by rsercano** [comment]
Hello,

tried this, and it's working for me. Could you please kindly share your error logs ?

**Comment by rsercano** [comment]
Hello, 

please try with latest version (1.4.0) portable. I've fixed this issue.

**Comment by lopugit** [comment]
Where can you download that latest version?

I'm getting the same error when cloning the git repo and running meteor
