### ISSUE TITLE
Disconnect when Meteor application reloads

### ISSUE THREAD

**Issue by LoriKarikari** [nosqlclient/nosqlclient#223]
Hi,

I've been using Robomongo for a while but I want to switch to Mongoclient.
I'm using Mongoclient with a Meteor application and everything works fine until I edit some server side code and the app has to reload. Robomongo reconnects but Mongoclient loses connection and when I try to reconnect manually it keeps loading, so I have to restart the whole application to reconnect. It would be nice if it reconnects like Robomongo.

Thanks

**Comment by rsercano** [comment]
Hello,

could you please kindly share which distribution and version are you using ?
Also what exactly do you mean by **editing server side code**, are you editing mongoclient's code  ?

**Comment by rsercano** [comment]
Please re-open this issue with specific details.
