### ISSUE TITLE
Can't start app with docker

### ISSUE THREAD

**Issue by alfirin** [nosqlclient/nosqlclient#228]
When I create the application via docker, there is this error, and the application can't start:

```
$ docker run -p 3000:3000 mongoclient/mongoclient      

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local
```

**Comment by rsercano** [comment]
Hello thanks for the feedback, 

I guess as of new meteor version --unsafe-perm flag is not working anymore. Gotta check this asap.

**Comment by rsercano** [comment]
In the meantime could you please try latest stable docker version ?

`docker pull mongoclient/mongoclient:1.4.0`

and run as usual.

**Comment by rsercano** [comment]
https://github.com/meteor/meteor/issues/7959#issuecomment-259711382
