### ISSUE TITLE
The mongoclient docker container is running in dev mode

### ISSUE THREAD

**Issue by waterfoul** [nosqlclient/nosqlclient#231]
It would be fairly trivial to change the docker file to deploy using a production meteor setup, You would only require people to setup their own mongodb for the storage of settings (which most people will have anyway). For now I've just mounted these two files into the container and I have it running in prod mode with ssl

run.sh

```
    #!/bin/sh
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash

    dnf install -y make gcc-c++

    export NVM_DIR="/root/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

    nvm install stable

    set -xe

    dir=$(pwd)

    cd $dir
    /usr/local/bin/meteor build /build --architecture os.linux.x86_64 --unsafe-perm

    cd /build
    tar -xf mongoclient.tar.gz
    cd bundle
    (cd programs/server && npm install --production && npm install tunnel-ssh)

    cd /config
    npm install http-proxy
    node /config/proxy.js &

    cd /build/bundle
    export PORT=80
    node main.js
```

proxy.js

```
var httpProxy = require('http-proxy');

httpProxy.createProxyServer({
  target: 'http://localhost',
  ssl: {
    key: fs.readFileSync('/certs/privkey.pem', 'utf8'),
    cert: fs.readFileSync('/certs/fullchain.pem', 'utf8')
  }
}).listen(443);
```

I'm only recommending that you move the container to prod mode, although enabling ssl too would be a bonus. To update the container you would need to:
1. Add node, make, and gcc-c++ to the list of things installed
2. Add `RUN /usr/local/bin/meteor --unsafe-perm build /build --architecture os.linux.x86_64`
4. Add `WORKDIR /build`
3. Add `RUN tar -xf mongoclient.tar.gz`
3. Add `RUN cd /build/bundle/production/server && npm install`
4. Add `WORKDIR /build/bundle`
5. Change CMD to ["/path/to/node", "main.js"]
6. Update the documentation to add the environment variables for MONGO_URL and ROOT_URL to the docker commandline

This may not result in the cleanest setup so it might be better to just convert the container to use a node base. If you switch to the node base you should also be able to just add a pre-built bundle tar, run production/server && npm install and set the cmd

**Comment by rsercano** [comment]
Hello,

I'm not an export on docker, I would like to keep another branch for this version, and for your version could you please kindly raise a pull request for master ? I would gladly accept it.
