### ISSUE TITLE
"Route not found" issue when adding path to ROOT_URL

### ISSUE THREAD

**Issue by aalaesar** [nosqlclient/nosqlclient#237]
Hello
I am using Mongoclient as a boundled node.js application (using meteor build)
(The application is built using the meteor version installed by the meteor installation script which is 1.4.2.3 as this moment)
As mongoclient is intended to be used behind a reverse proxy, the environment variable ROOT_URL have been set with "ROOT_URL='http://localhost/mongoclient' aka **domain/path**
(tests using address translation do not work)
The other environment variable are also defined properly and work well.

However, when using the root URL, mongoclient loads and show a "route not found' error message.
![image](https://cloud.githubusercontent.com/assets/18649249/20434033/662e48dc-ada6-11e6-8d1d-fbab12e31310.png)

No previously defined connections to mongo db  are available in the **connect menu.**

![image](https://cloud.githubusercontent.com/assets/18649249/20434076/8f1ad81e-ada6-11e6-98ef-7d15668d0083.png)

When clicking on the **Go to Dashboard**, the URL appears to be changed to `http://localhost/databaseStats` and mongoclient  works properly.
The configured connections are again available.

![image](https://cloud.githubusercontent.com/assets/18649249/20434303/889bdec4-ada7-11e6-81a0-c5c034d7910a.png)

Accessing directly
`http://localhost/` or `http://localhost/databaseStats` 
or `http://localhost/mongoclient/databaseStats` return a 404 error
(this is an expected behaviour :+1: )
![image](https://cloud.githubusercontent.com/assets/18649249/20434445/19a087b2-ada8-11e6-88a6-f2744173f6a8.png)
![image](https://cloud.githubusercontent.com/assets/18649249/20434011/4bbe588e-ada6-11e6-87b4-58387453ff7f.png)

The health check works also as intended :`http://localhost/mongoclient/healthcheck` :+1: 
![image](https://cloud.githubusercontent.com/assets/18649249/20434561/9502e710-ada8-11e6-9607-f68a1f46a0f1.png)

When changing ROOT_URL to a simplier url like `http://localhost/`, mongodb works fine.

![image](https://cloud.githubusercontent.com/assets/18649249/20434676/401938ca-ada9-11e6-90e9-4aa437cc8d35.png)
This behaviour have been observed both is **javascript** mode and **websocket** mode
This is an issue as it is not suitable for production use.

Regards,
Aal.

**Comment by rsercano** [comment]
Thanks for the detailed explanation, gotta findout what's the issue

**Comment by rsercano** [comment]
It seems like, iron router have this issue. [#563](https://github.com/iron-meteor/iron-router/issues/563), [#154](https://github.com/iron-meteor/iron-router/issues/154) 

Gotta try to find a workaround or pass to flow:router

**Comment by rsercano** [comment]
Hello @aalaesar,

could you please kindly try again, I've moved to flowrouter from ironrouter, and please notify me if you encounter any issue. 

Thanks

**Comment by aalaesar** [comment]
hello @rsercano 
I have rebuilt the application using branch master and tested with the same environment.
the issue has disapeared and urls are properly used.

![image](https://cloud.githubusercontent.com/assets/18649249/20534419/71e6f7a8-b0e1-11e6-94b8-03fbfe36fef4.png)

Thank you for your very quick and efficient support :+1:

I see you added the 1.5.0 milestone for this issue.

is it going to be released soon ?
If it's not the case, will you add an intermediate version ? (1.4.1 )

Best regards
Aalaesar.

**Comment by rsercano** [comment]
I'm glad your issue is gone @aalaesar, unfortunately I've added some features to be planned for 1.5.0 and not planning to do any bugfix release soon. Are you using docker ? If not can you keep using master branch ? Soon (probably at mid december) I'm planning to release 1.5.0 

Cheers
