### ISSUE TITLE
Cannot check the text while the sidebar collapsed (Firefox & Chrome).

### ISSUE THREAD

**Issue by yuchting** [nosqlclient/nosqlclient#252]
![qq 20161204222319](https://cloud.githubusercontent.com/assets/1817716/20866787/6262c1f2-ba70-11e6-9823-122addc94636.png)
![qq 20161204222326](https://cloud.githubusercontent.com/assets/1817716/20866788/62c35738-ba70-11e6-9095-d3937daff82f.png)

I found the same problem in mobile phone browser(Chrome). In my opinion, it must show the detail text instead of a single icon.

**Comment by rsercano** [comment]
Thanks for the feedback, that was in my mind but just forgot about it, gotta fix that.

**Comment by rsercano** [comment]
That's already fixed by solving #247, but there's no sidebar anymore, when you hide it, it disappears completely in the master branch,
