### ISSUE TITLE
Error running mongoclient on Manjaro

### ISSUE THREAD

**Issue by ivoribeiro** [nosqlclient/nosqlclient#254]
error while running mongoclient on Manjaro 

symbol SSLv3_client_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference

**Comment by rsercano** [comment]
Hello

thanks for the feedback, going to check that.

**Comment by rsercano** [comment]
Hello again,

I've checked that, by installing Manjaro to my virtual machine and it worked like a charm. I guess issue is related with you. Could you please try to install openssl ? (just to try)

Cheers

**Comment by ivoribeiro** [comment]
Thank you for your response i already tried that but  no sucess.

Error:
``
 ivoribeiro@ivo-manjaro  ~/Packages/Mongoclient-linux-x64  ./Mongoclient
INFO  electrify:index:  initializing
INFO  electrify:plugins:  use  mongodb
INFO  electrify:plugins:  use  nodejs
INFO  electrify:plugins:  use  socket
INFO  electrify:index:  start
INFO  electrify:plugins:  start
INFO  electrify:plugins:mongodb:  starting mongo...
/home/ivoribeiro/Packages/Mongoclient-linux-x64/resources/app/bin/mongod: /usr/lib/libcrypto.so.1.0.0: no version information available (required by /home/ivoribeiro/Packages/Mongoclient-linux-x64/resources/app/bin/mongod)
/home/ivoribeiro/Packages/Mongoclient-linux-x64/resources/app/bin/mongod: /usr/lib/libssl.so.1.0.0: no version information available (required by /home/ivoribeiro/Packages/Mongoclient-linux-x64/resources/app/bin/mongod)
/home/ivoribeiro/Packages/Mongoclient-linux-x64/resources/app/bin/mongod: /usr/lib/libssl.so.1.0.0: no version information available (required by /home/ivoribeiro/Packages/Mongoclient-linux-x64/resources/app/bin/mongod)
/home/ivoribeiro/Packages/Mongoclient-linux-x64/resources/app/bin/mongod: relocation error: /home/ivoribeiro/Packages/Mongoclient-linux-x64/resources/app/bin/mongod: symbol SSLv3_client_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference``

**Comment by rsercano** [comment]
Could you please download non-ssl **mongod** binary and replace this:
`/home/ivoribeiro/Packages/Mongoclient-linux-x64/resources/app/bin/mongod`
with this mongod binary: 
`https://www.mongodb.com/dr/fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.4.0.tgz/download`

Just in case of it doesn't work you can try previous versions here 
`https://www.mongodb.org/dl/linux/x86_64?_ga=1.181000807.1371539762.1480172894`

**Comment by ivoribeiro** [comment]
It worked :) but why ?

**Comment by rsercano** [comment]
Probably meteor's mongod instance was needed an openssl binary which you don't have, but it's not needed for mongoclient since it's not using SSL while connecting to its own mongodb. I'm glad it worked :)
