### ISSUE TITLE
Configurable live chat

### ISSUE THREAD

**Issue by yuchting** [nosqlclient/nosqlclient#268]
Although I don't whether is suitable to move ***.nudgespot.com** js files into project(I'm not good at JavaScript and web programming), but in China or some other counties, it's hard to load those js file:

If possible, please open a option to close those special function, it's bad user experience to get loading cycle always rounding again and again.

![qq 20161231203858](https://cloud.githubusercontent.com/assets/1817716/21577587/73274338-cf9b-11e6-951d-1990fc685a36.png)

**Comment by rsercano** [comment]
It's coming for live chat, but I'm planning to do this live chat configurable just for the reasons that you've mentioned, will keep this ticket for making it configurable, thanks for the feedback.

**Comment by yuchting** [comment]
What I want to say is Live chat is good feature, and if you want to keep good connection with users, there is no any other way better than it.

Or could your resolve loading problem firstly? Move it into user's own project static files? And then consider that make it configurable (can be closed).

Thanks for your attention!

**Comment by rsercano** [comment]
Thanks for explanation, you're right I'm going to make it possible for next release
