### ISSUE TITLE
Windows Not Saving Dump Path

### ISSUE THREAD

**Issue by itotallyrock** [nosqlclient/nosqlclient#273]
I've recorded a short gif where I change the local dump path then save.  After which I leave and goto another screen and come back and it will be back to the default value.

![mongoclientbug](https://cloud.githubusercontent.com/assets/3466882/21747105/d9ac617a-d521-11e6-946e-f3c911baf264.gif)

This isn't just visual because after dumping it dumps in the default location even if the target folder exists.  

I'm running 1.5.0 on Windows 10 64bit, if I need to supply any more information to help track down this bug I will try to add.

**Comment by itotallyrock** [comment]
I also want to say I saw something similar to #126 however their issue seemed to deal more with creating the dump itself rather than saving the path (at least to my reading).  And they were using a different platform.

**Comment by rsercano** [comment]
Hi there @itotallyrock 

could you please also specify are you using distribution or compiling as a web application ?
Is this effect only dump path, or can't you save other settings as well ?

**Comment by itotallyrock** [comment]
I'm using the windows portable distribution, and other settings save just not the dump path.

**Comment by rsercano** [comment]
Alright, thanks for the feedback gotta check that.

**Comment by rsercano** [comment]
Thanks for the feedback, it's resolved in master branch and will put into next release
