### ISSUE TITLE
Layout problem when the collections name is too long 

### ISSUE THREAD

**Issue by mighty-potato** [nosqlclient/nosqlclient#285]
When the collection name for example meteor_accounts_loginServiceConfiguration the left layout in the collection get messy 
[![Screen Shot 2017-01-19 at 2.06.02 PM.png](https://s29.postimg.org/dz388m7w7/Screen_Shot_2017_01_19_at_2_06_02_PM.png)](https://postimg.org/image/t7t5me1kj/)

**Comment by rsercano** [comment]
Hello @lastday4you 

thanks for the feedback gotta check that asap.

**Comment by rsercano** [comment]
I've moved Add and Drop collection buttons to context menu to fix this issue, which make UI more readable.
