### ISSUE TITLE
1.5.0 windows portable won't run

### ISSUE THREAD

**Issue by genewitch** [nosqlclient/nosqlclient#288]
A JavaScript error occured in the main process

Uncaught Exception:
Error: Cannot find module 'electrify'
at [...] module.js
![mongoclient](https://cloud.githubusercontent.com/assets/3182020/22182041/910105c6-e060-11e6-9169-769447ab7023.png)

**Comment by rsercano** [comment]
Hello,

thanks for the feedback, that seems interesting, would you mind re-downloading latest binary and try again, it seems to be working for me

**Comment by rsercano** [comment]
Hi again @genewitch 

I tried this in a few windows machines, and it seems to be working without an issue. If you encounter this again after downloading new binary, please re-open this issue
