### ISSUE TITLE
Update destroyed my collection(s).

### ISSUE THREAD

**Issue by gcperrin** [nosqlclient/nosqlclient#289]
Writing an update to mongo, after the write my collection was still there (only _id remained) but totally blown away. Steer clear if working on a live db, at least until this repository is being driven by a test framework with untested features removed from the UI. Log below for reference.

![screen shot 2017-01-22 at 6 18 07 pm](https://cloud.githubusercontent.com/assets/488909/22188130/3f063a42-e0cf-11e6-995a-97aed726dc5c.png)
 ##

It blew away a totally different collection in the DB as well...this collection had a similar schema if that helps, i.e. it contained a 'currentCounter.22' also, but was not operated on during the update. For reference the values all already existed...I was just updating one due to the application restarting.

**Comment by gcperrin** [comment]
![screen shot 2017-01-22 at 6 34 33 pm](https://cloud.githubusercontent.com/assets/488909/22188334/74077984-e0d1-11e6-86bb-758ea31ee780.png)

**Comment by rsercano** [comment]
Hello @gcperrin 

I really don't get what you mean ?! You're trying to insert many an empty array or updating one, and what error happens ?!

> after the write my collection was still there (only _id remained) but totally blown away.

Did `deleteMany` responsible from this ?

> It blew away a totally different collection in the DB as well

That's actually not possible, it executes every command on that you've selected from left side.

Did you pull latest from docker or a tag ? Could you please make a clear statement of issue ?

**Comment by gcperrin** [comment]
Apologies I'll reiterate.

My dist was built from scratch yesterday, cloned directly from the repository, and run with Meteor.

I created a query to return some values from my collection, using the mongoclient UI (under the 'collections' tab) . Upon return of this query, I edited one of the values in the collection, and hit 'save' in the UI. The commands from updateOne to the error are all internal calls made by the application and not intentional.

URLs visited appear to be /browseCollection and /editDocument from my history.

> That's actually not possible, it executes every command on that you've selected from left side.

I know we'd all love to think this but I'm just telling you what happened. I dug into your source a bit and again it's totally unspec'd with no testing automation. Without such it's hard to justify any absolutes in terms of what the software may (or may not) do.

I could honestly re-create the scenario if you're dedicated to a patch...I just don't have time in the next two weeks or I'd investigate myself...the tool (besides this hiccup) seems to have a solid future.

**Comment by rsercano** [comment]
Thanks for the feedback, as a single core developer it's hard to write tests, and keep updating new features, as soon as possible writing tests is the next step of my development.

I'll try to reproduce issue, if there's one I would like to fix it, furthermore if you get a chance to reproduce please keep me up to date, so I can fix it.

Thanks again.

**Comment by gcperrin** [comment]
Of course, I understand how these things go -- I've made it a personal goal to try & jump and help once this critical period with my job subsides. I'll try and get some sort of re-creation with more screenshots and a sample of the collection schema...if there is any way to up the debug log verbosity that might lead to a clue for you?

**Comment by rsercano** [comment]
Unfortunately current log level can't be changed, actually there shouldn't be something that hasn't been logged, when you click **Save** from `find` query, it internally executes 3 queries if necessary. `deleteMany`, `updateOne` and `insertMany`, maybe there's something wrong with the delete query, I'll check and write it down here.

Thanks for your understanding

**Comment by rsercano** [comment]
I tried a few use-cases and realized a few things:

- After saving, changes wasn't being determined correctly, fixed.
- Was unnecessarily querying database for delete, insert even there's no insert/delete, fixed.

Apart from these, I couldn't reproduce this

**Comment by gcperrin** [comment]
I'll attempt to reproduce in the next 48 hours. Will capture more screen shots and include an example schema, as well as relevant mongod daemon logs.

**Comment by rsercano** [comment]
That would be great @gcperrin thank you so much !

**Comment by rsercano** [comment]
@gcperrin please reopen if you can find out something.
