### ISSUE TITLE
Typo in installation behaviour

### ISSUE THREAD

**Issue by realflash** [nosqlclient/nosqlclient#297]
In https://github.com/rsercano/mongoclient/wiki#31-compile-from-source-browser-edition step 4, the command `meteor npm install` is given. I think this should be `npm install`.

**Comment by rsercano** [comment]
Hello @realflash 

thanks for this, but I guess both is applicable, here's the [doc](https://guide.meteor.com/using-npm-packages.html#installing-npm)

**Comment by realflash** [comment]
That didn't work for me, which is what made me consider that maybe it was a mistake and switch to npm install. But perhaps that was an issue local to me.

In any case, I got so bored of waiting for an hour for meteor to "update the package cache" and start building things that I canned the whole lot and switched to admin-mongo. Is meteor really required for mongoclient to run (rather than build)? I'm looking to access from a web browser and have it run on the mongo server.

**Comment by rsercano** [comment]
@realflash why don't you use docker ? https://hub.docker.com/r/mongoclient/mongoclient/

Apart from that, you can build mongoclient and use an external mongodb (meteor needs mongodb) and just use node without meteor. (https://guide.meteor.com/deployment.html)

**Comment by realflash** [comment]
I couldn't run adminmongo due to syntax errors in the current code, so I'm back, and I have successfully deployed via docker. I can't connect to my DB, though - where's the log file?

**Comment by rsercano** [comment]
@realflash 

just run without -d flag and here you go. If you get timeout issues, try to set timeouts to 0 at settings.

**Comment by realflash** [comment]
Achieved the same thing with docker logs and found the port typo that was causing me a problem. Thanks very much.

**Comment by rsercano** [comment]
@realflash I'm glad your issue is fixed
