### ISSUE TITLE
Shell TextArea too small

### ISSUE THREAD

**Issue by kdeconinck** [nosqlclient/nosqlclient#310]
## Expected Behavior
The TextArea in which you can enter a command is too small.
It's fine for small queries such as a find, but for very large queries, such as Aggregation Queries, queries with multiple $or and/or $and operator(s) are not readable once they are splitted over multiple lines.

**Comment by rsercano** [comment]
Hello @kevin-de-coninck this's fixed with #292, you can use latest docker image or wait next release for it, thanks for the feedback
