### ISSUE TITLE
Consider relative domain/path when building other paths 

### ISSUE THREAD

**Issue by hamburml** [nosqlclient/nosqlclient#311]
## Expected Behavior

I started mongoclient as docker service and the reverse proxy forwards to it when url was `https://sub.domain.de/mongoclient`. The UI should load all files relative from this path.

## Current Behavior
UI tries to load files from `https://sub.domain.de/packages/underscore.js` which isn't working because it must be  `https://sub.domain.de/mongoclient/packages/underscore.js`.

## Your Environment

* Mongoclient version used: 1.5.0
* Environment name (e.g. chrome 39, portable, docker): chrome 56, docker 1.13.1, Docker Flow: Proxy & Docker Flow: Swarm-Listener & Docker Flow: Let's Encrypt

**Comment by rsercano** [comment]
Hello @hamburml ,

did you try setting `ROOT_URL` environment variable as [described here](https://github.com/rsercano/mongoclient/wiki#311-base-url-path)

**Comment by hamburml** [comment]
@rsercano Thanks, that worked! Sorry, haven't tried the wiki.

**Comment by rsercano** [comment]
@hamburml soon I'm going to write a brief documentation (not to wiki) I'M glad your issue is fixed.
