### ISSUE TITLE
Let users extend the size of the left column

### ISSUE THREAD

**Issue by derroman** [nosqlclient/nosqlclient#317]
If you have collection names, which are pretty long (> 30 characters) the names break strangely in the list of collections on the left side
## Expected Behavior
It would be great if one could extend the size of the left column where the collection names are
## Current Behavior
name of collection breaks, drop button is difficult to reach
## Possible Solution
let users extend the size of the left column

## Steps to Reproduce (for bugs)
1. create a collection name with more than 30 characters
2. watch the result

## Your Environment

* Mongoclient version used: 1.5.0
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): Ubuntu 16.04 64bit LTS

**Comment by rsercano** [comment]
Hello @derroman 

thanks for the feedback as a simple and quick fix I've implemented #285 but it would be really great to extend left size as you mentioned. I'll try to implement this for next release.

**Comment by derroman** [comment]
Thanks! I really appreciate your work in MongoClient! Looking forward for version 2! :)
