### ISSUE TITLE
The demo on the website is broken.

### ISSUE THREAD

**Issue by snarlynarwhal** [nosqlclient/nosqlclient#324]
Demo on site doesn't work. It just hangs there attempting to connect with a blank blue webpage.

**Comment by rsercano** [comment]
Hello @snarlynarwhal 

thanks for reminding this, I'm going to deploy a proper version of demo, currently it isn't a proper deployment (a direct meteor call instead of a build) and have issues. 

Gotta fix that soon, thanks again

**Comment by snarlynarwhal** [comment]
Okay - going to download a windows build in the meantime to check it out. :)

**Comment by rsercano** [comment]
I strongly recommend docker build which has newest features :)

**Comment by rsercano** [comment]
Fixed @snarlynarwhal you can check now.

**Comment by thewizarodofoz** [comment]
the demo page is broken again

**Comment by rsercano** [comment]
@thewizarodofoz thanks a lot for notifying just re-built it.
