### ISSUE TITLE
How to preconfigure a connection to MongoDB?

### ISSUE THREAD

**Issue by artiommft** [nosqlclient/nosqlclient#327]
Hi,

This is an usage question as I couldn't find any information in wiki that could answer it.

Is there any way to preconfigure in advance a MongoDB connection?
Our team members are using identical settings for the dev environment, so I am investigating whether it is possible to build a custom docker image of `mongoclient` that contains a default MongoDB connection or maybe to pass it as an environment variable. Is that possible at all?

Unfortunately, I am not familiar with MeteorJS and I am not sure where to start to add such functionality...

Thank you,
Artiom

**Comment by rsercano** [comment]
Hello @artiommft 

Thanks for your interest on mongoclient, unfortunately currently there's no such feature to add preconfigured connections to mongoclient.

But I can suggest a workaround to you, **mongoclient** internally uses mongodb, therefore there's a data path for this mongodb, you can simply keep this path outside of your `docker` container and give it to anyone else you want, and just run `docker` via `-v `flag with the path. 

Mongoclient's data path is `/data/db`, let me know if it works, I would like to add this feature to mongoclient for the next major release.

**Comment by artiommft** [comment]
Hi,

Thank you for your response - the solution with external `/data/db/` volume works, but an emtpy MongoClient database takes ~200MB of disk space - and including this into download would be too much.

I will explore other available options meanwhile - was thinking about adding an environment variable like `DEFAULT_CONNECTION_URL` that would be inserted/updated in DB on startup if it is present - this functionality may reside in the same place where you do the migrations from old connections format (please let me know if there is a better place for this). I will keep this issue open while I try this approach.

**Comment by rsercano** [comment]
That's pretty much what I think after your issue :) after [this line](https://github.com/rsercano/mongoclient/blob/master/server/imports/internal/startup.js#L138) at startup you can [follow here](https://github.com/rsercano/mongoclient/blob/master/server/imports/internal/internal_methods.js#L159) to insert into `Connections` collection.

Let me know if you need anything else to know, hopefully I'm going to write a brief documentation for the next major release. (2.x)

**Comment by artiommft** [comment]
Thank you for instructions - I submitted the PR above. It adds the functionality I require - please let me know in the PR whether you will merge it or not - so I know whether to use your docker image or I need to build my own one.
