### ISSUE TITLE
Switch DB not working while using URL type of connections

### ISSUE THREAD

**Issue by artiommft** [nosqlclient/nosqlclient#329]
Using latest source code or latest docker image - the collections are not displayed making it impossible to explore the data stored in the server.

How to reproduce:
Launch app and connect to a server, click on "Collections" section

Expected result:
Collections section should expand and show the collections available in selected database.

Actual result:
The section aparently expands but does not display any collections.

Note: I noticed that if I add a new collection - it is added to the list and stays there forever. It looks like the functionality "refresh collections" does not work.

Do you have any hints where to look for implementation of "refresh collections" function?

**Comment by rsercano** [comment]
Hello @artiommft 

I just pulled latest docker image and started without `-v flag` (just to reproduce this issue), then created my connection and successfully connected, afterwards I'm able to use mongoclient as usual.

Are you sure you've wrote your **DB name** correctly ? You can check your DB name from upper left corner, and switch to another database by `More -> Switch Database `option from right upper corner.

Adding new collection means you're creating a new collection on your database, therefore why should it disappear ? I've also tried `Refresh collections` and it seems to be working.

**Comment by artiommft** [comment]
Here is what I am trying to do:
1. connect to a DB server using an url like "mongodb://localhost:32768" - it connects successfuly and uses the database "admin" by default, but no collections are displayed in the right-hand side menu
2. right-click the "Collections" item -> "Create collection" -> use name "test" -> collection is created and added to the right-hand side menu, now it contains only one item "test"
3. Switch the database to another one which I checked via command line that it has a few collections -> but the menu on the right does not refresh and stays the same with one item "test".

Is there anything I can look for in meteor logs when I run the app via `meteor --port 3000` from source code?

btw, I am using MongoDB v3.4.2

when you tested from your side- were you able to list existing collections in a database? does it refresh the collections list when you switch the database?

**Comment by rsercano** [comment]
Oh, now I understood exact issue, apparently when using URL connection switch database not working, I'm currently trying to fix it asap. Thanks for the feedback

**Comment by artiommft** [comment]
Thank you for help :)

**Comment by rsercano** [comment]
Hello @artiommft 

I guess its fixed, you can pull latest mongoclient from docker in half an hour and start using without this bug.

Thanks again.

**Comment by artiommft** [comment]
I can confirm it is working now - thank you very much.
