### ISSUE TITLE
DB name doesn't support the "@" char when configuring a connection

### ISSUE THREAD

**Issue by kattunga** [nosqlclient/nosqlclient#330]
When configuring a connection I can't use DB names that contains the @ character.

I have a server with hundred of DB's and all of them has the names in the format "xxxx@xxx"

When trying to connect to any of this databases I get the error 

"Couldn't connect: failed to connect to server [xxx:27017] on first connect"

@ is a valid char for DB names in mongoDb.

**Comment by rsercano** [comment]
Hello @kattunga 

thanks for the feedback, are you using URL connections or filling DB name in connections ?
Also could you please point out the documentation from mongodb to follow how to escape @ char in url.

p.s. I'm not able to connect to mongodb via shell:

```
C:\Users\Sercan>mongo mongodb://localhost:27017/asd@asd
MongoDB shell version v3.4.2
connecting to: mongodb://localhost:27017/asd@asd
2017-03-09T22:30:46.768+0300 I NETWORK  [thread1] getaddrinfo("asd") failed: Bilinen böyle bir ana bilgisayar yok.
2017-03-09T22:30:46.768+0300 E QUERY    [thread1] Error: couldn't initialize connection to host asd, address is invalid :
```

```
C:\Users\Sercan>mongo mongodb://localhost:27017/asd
MongoDB shell version v3.4.2
connecting to: mongodb://localhost:27017/asd
MongoDB server version: 3.4.2
Server has startup warnings:
2017-03-09T22:18:12.734+0300 I CONTROL  [initandlisten]
2017-03-09T22:18:12.734+0300 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-03-09T22:18:12.737+0300 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-03-09T22:18:12.739+0300 I CONTROL  [initandlisten]
2017-03-09T22:18:13.128+0300 I STORAGE  [initandlisten]
2017-03-09T22:18:13.128+0300 I STORAGE  [initandlisten] ** WARNING: mongod started without --replSet yet 1 documents are present in local.system.replset
2017-03-09T22:18:13.130+0300 I STORAGE  [initandlisten] **          Restart with --replSet unless you are doing maintenance and  no other clients are connected.
2017-03-09T22:18:13.130+0300 I STORAGE  [initandlisten] **          The TTL collection monitor will not start because of this.
2017-03-09T22:18:13.132+0300 I STORAGE  [initandlisten]
```

**Comment by kattunga** [comment]
I'm filling DB name in connections.

It works in shell this way:

![screenshot at 2017-03-09 18 55 30](https://cloud.githubusercontent.com/assets/2139720/23772593/4170a00c-04fa-11e7-92cc-b473be2bcae0.png)

**Comment by rsercano** [comment]
@kattunga thanks for the example, gotta check that

**Comment by rsercano** [comment]
Hİ @kattunga 
could you please type `show dbs` on mongo shell and share your output here ?

**Comment by rsercano** [comment]
I'm not able to connect as you described unfortunately: 

```
sercan@aytws08:~/applications/mongodb-linux-x86_64-ubuntu1604-3.4.2/bin$ ./mongo localhost/asd@asd
MongoDB shell version v3.4.2
connecting to: mongodb://localhost/asd@asd
2017-03-10T11:24:51.222+0100 I NETWORK  [thread1] getaddrinfo("asd") failed: Name or service not known
2017-03-10T11:24:51.222+0100 E QUERY    [thread1] Error: couldn't initialize connection to host asd, address is invalid :
connect@src/mongo/shell/mongo.js:237:13
@(connect):1:6
exception: connect failed

```

**Comment by kattunga** [comment]
I upgrade client to 3.4 and I found what I suspected.
With client 3.4 I can't use db with @ in connection string.
I can connect to server and then switch to db.
so this is not a MongoClient issue.

The problem with mongoclient is that it force me to set dbname in connections, other client tools not. Actually I can work with robomongo and compass without any problem.

**Comment by rsercano** [comment]
I see, @kattunga thanks for the feedback. If you [check here](https://www.mongodb.com/support-policy) MongoDB is not supporting 2.6 anymore, so that Mongoclient too. I'm closing this for now.

**Comment by kattunga** [comment]
I'm using 3.4 version. And @ is still a valid char for db names.
The only point where is not supported is in the connection string, where is db name is optional.
You can still connect to the server and then switch to any database with @ in its name.
This way works any other db manager.

May be mongoclient could do the same when connecting.

**Comment by rsercano** [comment]
oh I see, @kattunga thanks nodejs only supports URL type connections, so I'm actually merging whole connection options and creating URL at the end. 

[Here's the resource of nodejs](http://mongodb.github.io/node-mongodb-native/2.2/tutorials/connect/)

I actually wonder how can you connect via 3.4 mongo shell with URL, are you escaping @ char ?

**Comment by kattunga** [comment]
no, I'm connecting to the server and then switch to the database

![screenshot at 2017-03-10 11 01 45](https://cloud.githubusercontent.com/assets/2139720/23797953/13b44af6-0581-11e7-9ac5-3c0c1c39ebc9.png)

**Comment by kattunga** [comment]
I think it can be done this way:

```javascript
  // Set up the connection to the local db
  var mongoclient = new MongoClient(new Server("localhost", 27017), {native_parser: true});

  // Open the connection to the server
  mongoclient.open(function(err, mongoclient) {

    // Get the db with @
    var db = mongoclient.db("database@name");

```

**Comment by rsercano** [comment]
@kattunga thanks for the details, yeah then that's the only way to achieve this. I'm going to check and fix that asap. 

Thanks again.

**Comment by rsercano** [comment]
This is fixed in current master branch, you can pull via docker if you wish @kattunga But unfortunately  some features such as schema analyze, database dump/restore is not available for databases which have @ in their names, since URL is a must for these features.
