### ISSUE TITLE
OSX-portable not working

### ISSUE THREAD

**Issue by bitk0der** [nosqlclient/nosqlclient#332]
Latest osx-portable 1.5.0 release don't show any window, OSX 10.12.3, in menu available only QUIT. 1.3.0 version works properly.

**Comment by rsercano** [comment]
Thanks for the feedback, @bitk0der I'm currently working on 2.0.0 (a major update) and it can take a few more weeks to release it until then I have no time to fix it, but I strongly recommend you to use a docker build, so that you can easily check new features in the meantime

**Comment by bitk0der** [comment]
@rsercano, thank you for your reply, i'll try to use web version until version 2.

**Comment by rsercano** [comment]
Hello @bitk0der version 2.0.0 is released
