### ISSUE TITLE
Could not load worker TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by HLFH** [nosqlclient/nosqlclient#342]
## Expected Behavior
Get the table view. Related to https://github.com/mongoclient/mongoclient/issues/66

## Current Behavior
In JS Console, you get the issue:
Could not load worker TypeError: Cannot read property 'split' of undefined
related to `modules.js` file.

## Possible Solution
Fix it and add a _Table_ option.
![whereistable](https://cloud.githubusercontent.com/assets/2359059/24750727/d21edb9e-1abe-11e7-875c-4780a0c64544.png)

## Steps to Reproduce (for bugs)
1. Connect to the best WebUI for MongoDB
2. Admire how this solution is perfect
3. Make a connection
4. Go to /browseCollection
5. Choose a Collection, make a `find` query.
6. Execute
8. Oh! An error in the JS console!

## Context
I would like the table view for my collections.
**The JS error could be unrelated to what I desire the most.**

## Your Environment
* Mongoclient version used: master (jedi)
* Environment name: server
* Operating System and version: Ubuntu 16.04
* MongoDB version: 3.4.3

**Comment by rsercano** [comment]
Hi again @HLFH,

thank you so much for the feedback and your great opinions :) But as a design decision I've never implemented a table view and not thinking to add one, in my opinion it's redundant to show a json structure in table view.

The options that you've mentioned comes from JSONEditor which Mongoclient is being used right now. These options are just like helpers. You can always edit your data for `find` queries and press **Save** button. Mongoclient automatically will detect changes and do save for you :)

**Comment by HLFH** [comment]
Thank you for your great design decision. I did not know you were using JSONEditor.

And do you have any idea about the JS issue (with the steps to reproduce above):
> Could not load worker TypeError: Cannot read property 'split' of undefined

**Comment by rsercano** [comment]
As far as I remember it was a warning that comes from JSONEditor, but I'm going to check again, thank you :)

**Comment by rsercano** [comment]
Hi @HLFH 

I tried to follow up stack trace but no chance, this warning comes internally from meteorjs and can be ignore-able for now. 

If you encounter anything breaks something, re-open this with the details please. 

Thank you so much.

**Comment by HLFH** [comment]
Related to: https://github.com/josdejong/jsoneditor/issues/402
