### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by HLFH** [nosqlclient/nosqlclient#343]
Hi @rsercano 

I can't edit the wiki. Maybe you should add an init section.
It is for `systemd`:

You have to change here _MYUSERNAME_, _MYPASSWORD_, _MYPORT_ and probably the value of `WorkingDirectory`.

```systemd
[Unit]
Description=MongoDB management tool
After=network-online.target

[Service]
User=mongoclient
Group=mongoclient
WorkingDirectory=/srv/http/mongoclient/
Environment=MONGOCLIENT_AUTH=true
Environment=MONGOCLIENT_USERNAME=MYUSERNAME
Environment=MONGOCLIENT_PASSWORD=MYPASSWORD
ExecStart=/usr/local/bin/meteor --port MYPORT

[Install]
WantedBy=multi-user.target
```

**Comment by rsercano** [comment]
Hi @HLFH 

as soon as I get some spare time, I would like to examine `systemd`, currently I don't know how it works. And will add this information to mongoclient documentation.

Thanks again :)

**Comment by rsercano** [comment]
Hi again @HLFH 

how is this supposed to work, I really don't know much about `systemd` sorry. Could you please explain more ?

I'll add this to documentation if I get your point :)

**Comment by rsercano** [comment]
Okay, I've read more @HLFH  and added systemd to mongoclient documentation as you've described, thanks for your contribution. 

Documentation will be live as soon as 2.0.0 gets released in two weeks.

**Comment by HLFH** [comment]
@rsercano Great! Thank you so much!
