### ISSUE TITLE
Save connections in settings.json

### ISSUE THREAD

**Issue by HLFH** [nosqlclient/nosqlclient#345]
Hi,

With Mongoclient 1.6.0, I was losing the details of my connections sometimes.
Could you add the feature to save the connections within the settings.json of Mongoclient using its WebUI?

Thank you,

**Comment by rsercano** [comment]
Hello @HLFH 

there's a section for this, [check here](https://mongoclient.com/docs/user_manual.html#mongoclient_data) . Let me know if you can't import or export your data.
It's version 2.0.0 :)
