### ISSUE TITLE
[Docker] Couldn't connect: [dstPort not set]

### ISSUE THREAD

**Issue by DaxServer** [nosqlclient/nosqlclient#347]
## Expected Behaviour

The app should connect to remote Mongo instance.

## Current Behaviour

I have provided all the details required for SSH and the correct remote's local IP and port, but I get this error! I have tried the same with RoboMongo and it worked fine!

## Your Environment

* Docker (latest: Should be 2.0.0) on Kitematic 0.13.0
* macOS 10.12.3

**Comment by DaxServer** [comment]
The same issue with OS X portable! What am I missing?

**Comment by rsercano** [comment]
Hello @SrihariThalla 

are you trying to connect to your **mongod** instance with SSH tunnel ?  
Could you please make sure there's nothing working for that mongod's port and try again ?

If it won't work could you please share your logs ?

Thanks

**Comment by rsercano** [comment]
Hello @SrihariThalla 

it was a bug, and have been resolved in the current master branch. Docker automated build is running currently and will be available in 10-15 minutes. You can pull **latest** tag and start using SSH feature. 

Sorry for the inconvenience. 
Thanks for the feedback.

**Comment by DaxServer** [comment]
Thanks @rsercano
