### ISSUE TITLE
Loading libssl.1.0.0 fails

### ISSUE THREAD

**Issue by faraz5040** [nosqlclient/nosqlclient#348]
I'm trying to run the portable linux-x64 2.0.0 version and it gets stuck on the please wait screen.
I get the following error when running from terminal:
```
[MONGOCLIENT] [MONGOD-STDERR] /home/myuser/linux-portable-x64/resources/app/bin/mongod: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

[MONGOCLIENT] [MONGOD-EXIT] 127
```
I'm using fedora 25 with openssl 1.0.2k installed.
I tried linking libssl.so.1.0.0 to libssl.so with no success.

## Possible Solution
Also is it possible to make mongoclient use my systems running mongod instead of running it's own mongod?

## Your Environment):
portable linux-x64 2.0.0 version electron app
Fedora Linux 25 with openssl and openssl-devel 1.0.2k

**Comment by rsercano** [comment]
Hello @alireza4050 

thanks for the feedback, could you please try to set **MONGO_URL** environment variable and set an external MongoDB before starting **Mongoclient** just as a workaround.

In the meantime, I'll investigate this further.

Thanks again.

**Comment by rsercano** [comment]
Hi @alireza4050 

could you please kindly try again by following the answer [from here](https://askubuntu.com/questions/339364/libssl-so-10-cannot-open-shared-object-file-no-such-file-or-directory), and let me know if that works for you ?

**Comment by rsercano** [comment]
I'm closing this for now @alireza4050 please let me know if something wrong goes for you.

I'll consider using a legacy mongodb for the mongoclient's internal database to support all type of linux distributions thank you
