### ISSUE TITLE
[Docker] Couldn't connect: [listen EADDRINUSE 127.0.0.1:27017]

### ISSUE THREAD

**Issue by DaxServer** [nosqlclient/nosqlclient#349]
## Expected Behavior
The app should connect to remote Mongo instance (via SSH tunnel).

## Current Behavior
Cannot connect to remote Mongo and fails with error `Couldn't connect: [listen EADDRINUSE 127.0.0.1:27017]`

## Your Environment
* Environment name: Docker :latest (published yesterday)
* Operating System and version: MacOS 10.12.4

### Info
* This issue arises after #347 
* From the error message, it seems, the MongoClient is trying to connect to localhost and is not connecting via SSH (as the error is instant and that SSH would take a second or two before failing to connect to mongod)

Thanks!

**Comment by rsercano** [comment]
Hello @SrihariThalla 

I was able to connect using SSH tunnel with the latest published docker build, I'm quite sure there should be a configuration error on your side, could you please share your configuration with me (censor necessary fields) so that I can check it.

**Comment by DaxServer** [comment]
Here is the config, @rsercano 

## Connection

* Host `10.0.3.24` - The container here has Mongo
* Port `27017`
* Database `admin`

## Authentication

`None`

## SSH

* Hostname `remote IP address`
* Port `22`
* Destination Port `27017`
* Local Port `left blank`
* Username `username`
* Certificate & Passphrase

## SSL

`None`

## Options

`Defaults`

---

Here is the expected flow:

`Mac` -> `SSH to remote on 22` -> `Connect to Mongo at 10.0.3.24:27017 (LXC)`

**Comment by rsercano** [comment]
Hello @SrihariThalla 

could you please try to set a free port to **Local Port** field and also same port to first tab. (Connection)

Please let me know if it works for you.

**Comment by DaxServer** [comment]
Hi @rsercano 

Another error this time:

```
2017-04-17T13:28:42.587Z - error:  MongoError: failed to connect to server [10.0.3.24:37017] on first connect [MongoError: connection 5 to 10.0.3.24:37017 timed out]
    at [object Object].<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodbcore/lib/topologies/server.js:327:35)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodbcore/lib/connection/pool.js:274:12)
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodbcore/lib/connection/connection.js:187:10)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
```

I have set `Connection Timeout` and `Socket Timeout` to 30 each. Set the port on the first tab and Local port on SSH tab to `37017`.

**Comment by rsercano** [comment]
And your destination port is correct right ? Did you expose your mongod's port correctly in the other docker ?

**Comment by rsercano** [comment]
By the way @SrihariThalla 

here's what I can do to connect via SSH:

## First Tab (Connection)
**host**: localhost
**port**: 33333 (a random free port)
**database**: myDB

## Fourth Tab (SSH)
**host**: remote ip
**port**: 22
**destination**: 27017 (remote mongod's port)
**local port**: 33333 (same as first tab)
**username**: my_username
**password**: my_password

And I'm able to successfully connect my mongodb instance, Mongoclient uses **33333** as local port for forwarding btw.

**Comment by rsercano** [comment]
Hi @SrihariThalla 

did you make any progress on this ? I've tried SSH with a few my other colleagues as well and there was no problem to us. 

I would like to close this if you've handled your issue ?

**Comment by DaxServer** [comment]
Hey, I was a little bit preoccupied today. I'll try your config tomorrow!

**Comment by DaxServer** [comment]
@rsercano It didn't work 😕 

This is a screenshot from Robomongo. It's working, though!
![screenshot 2017-04-19 17 08 44](https://cloud.githubusercontent.com/assets/7479937/25178368/2e01c976-2523-11e7-84d3-ff37475a10f5.png)

**Comment by DaxServer** [comment]
BTW, the remote Mongod is inside an LXC container. The port is exposed via `10.0.3.24:27017`.

**Comment by rsercano** [comment]
That's quite strange @SrihariThalla,

I'll investigate it further asap

**Comment by rsercano** [comment]
by the way could you please try to connect a few times with your latest configuration @SrihariThalla sometimes it throws timeout exception that comes from an internal module before a successful connection ?

**Comment by DaxServer** [comment]
Sure!

**Comment by rsercano** [comment]
I assume this can be closed @SrihariThalla hope your issue is fixed, I'm planning to release for this fix at this weekend. Please let me know if something is broken or not working for you.

Thanks
