### ISSUE TITLE
Impossible to import monclient backup data from 1.5 to 2.0

### ISSUE THREAD

**Issue by jkeruzec** [nosqlclient/nosqlclient#351]
I export my preferences from MongoClient 1.5 to import them into new MongoClient 2.0, but I have an error. 
Import is correctly done but when I open "Connect" menu, I have this :

![image](https://cloud.githubusercontent.com/assets/3499632/25737499/7df9d1ce-3178-11e7-8645-af5740609372.png)

Can you help on this ?

Regards,

**Comment by rsercano** [comment]
Hi @jkeruzec 

would you please share additional details such as what distribution you're using, what OS you're on etc. ? 

And are you using **Import/Export Mongoclient Data section** that's placed in **More** button,  or using docker to bind same data volume ?
Thanks

**Comment by rsercano** [comment]
Actually we had no problem during this migration, but we've used Import/Export feature that comes built-in in Mongoclient

**Comment by jkeruzec** [comment]
For your information, I'm using Windows 10 and portable version of Mongo Client EXE.

And I'm using the "More" button functionality.
Also, It could be usefull to add a button to search for the folder here ;)

**Comment by rsercano** [comment]
> Also, It could be usefull to add a button to search for the folder here ;)

Definitely was in queue, will do for the next version :) Will investigate this further, thanks for the information.

**Comment by jkeruzec** [comment]
Ok hope it helps !
Waiting for this version :)

**Comment by rsercano** [comment]
Hello @jkeruzec 

I guess I've fixed the issue, but not yet released. If you're using docker the build will be done in half an hour and you can pull it. 

Apart from that if you wait the next release and use it, please make sure you've cleaned up the data directory of electron application before using **import feature** where Mongoclient keeps its data on. 

- *Windows*
`%APP_DATA%/Mongoclient/db`
- *OSX*
`%HOME%/Library/Preferences/Mongoclient/db`
- *Linux*
`%HOME%/var/local/Mongoclient/db`

**Comment by jkeruzec** [comment]
Hello @rsercano,

Thank you for reactivty, I just tested the docker version and it works well. Good to have the import button too.

Regards,

**Comment by rsercano** [comment]
Hi @jkeruzec 

Glad to hear that, thanks for the feedback
