### ISSUE TITLE
Cannot open in Firefox with Auth information

### ISSUE THREAD

**Issue by yuchting** [nosqlclient/nosqlclient#357]
I downloaded the 2.0.0 mongoclient and started with Auth information:

#!/bin/sh
export MONGOCLIENT_AUTH=true
export MONGOCLIENT_USERNAME=yuchting
export MONGOCLIENT_PASSWORD=*********

but it cannot be opened by Firefox (53.0.2 (32-bit)), it can be opened by Chrome.
I am a old user of mongoclient, it's OK for former version, 1.5.0

Another question here:
where's my database configure files? 
I download new version mongoclient and run, but there is not my database list after I click connect button.
I grep my database keyword for searching in my old mongoclient fold, cannot find any useful information.

Thanks!

**Comment by rsercano** [comment]
Hi @yuchting 

how are you trying to run **Mongoclient**, via docker or something else (distribution, heroku deployment etc...) ? I can answer other question with only that information :)

Cheers

**Comment by yuchting** [comment]
@rsercano 
Sorry for my lack of information, I run mongoclient in web compiling way, in centos, meteor run with nodejs, no docker, no heroku.

**Comment by rsercano** [comment]
@yuchting 

Alright I'll check auth asap, furthermore if you're using compile way, you should provide **MONGO_URL** environment variable, for the internal MongoDB of Mongoclient. 

Therefore you should set data path to mongodb of your application. Just set it as same and 2.0.0 may migrate your data to 2.0.0

**Comment by rsercano** [comment]
I would recommend you to download latest source code just in case.

**Comment by rsercano** [comment]
Hi again @yuchting 

I got a chance to try that just now, and it seems to be working on firefox/chrome/opera.  I guess this can be related with your extensions, do you use any extension to modify headers on firefox ? 

Because as you may know, basic authentication sends a request header with the key **Authorization** and a value that starts with **Basic**

Please feel free to re-open this issue if you find out something

**Comment by yuchting** [comment]
@rsercano 
Thanks for your help to test in these browser, I just found where the problem is.
It's AD blocker,
![snipaste20170512_161530](https://cloud.githubusercontent.com/assets/1817716/25989372/6750f2a2-372e-11e7-8ed6-b498d0732645.png)
If I disable this AD blocker, it will show.  This blocker website is https://adblockultimate.net/ , I think it's not bug of mongoclient, but as a developer, you may have interesting to know why :stuck_out_tongue_closed_eyes:

Further, you may misunderstanding my meaning, before I upgrade mongoclient, I will backup old folder and then download new version code and compile with meteor, but my all mongodb configs is gone:
![snipaste20170512_162548](https://cloud.githubusercontent.com/assets/1817716/25989776/0778323a-3730-11e7-9ab2-3cc2f239dfec.png)
When I run old folder, there are back, so I just believe these configs must be in folder of mongoclient, but I don't know where....
Need  I add all db configs (database name, password, URL...) after I upgraded mongoclient? It may bad user experience. If possible, I want to pay for a new feature that it can be upgraded automatically, such as WordPress. 
Another suggestion: would you mind add a document to indicate how to upgrade mongoclient? I just find how to install.

Thanks!

**Comment by rsercano** [comment]
Hi @yuchting 

thanks for your great opinions, gotta write that documentation for the next release.  
Let me summarize what you can do, if you're using `meteor` command

1. You can copy old `.meteor/local/db` folder into `Mongoclient 2.0.0/.meteor/local/db` and Mongoclient may migrate your data to its system. (Before that please clear all data in the `Mongoclient 2.0.0/.meteor/local/db`)

2. If you're using `meteor build` and then `node` then you can set `MONGO_URL` environment variable and setup your own mongodb, therefore you'll lose nothing.

3. Apart from all options, you can use [Import/Export Mongoclient](https://mongoclient.com/docs/user_manual.html#mongoclient_data) data feature, that makes it possible to use your old data regardless of the system or deployment.

Furthermore, we're working on professional edition, currently it's not completely ready. It has a lot more features than community edition. If you're interested you can subscribe to Mongoclient from inside of application or from inside of [demo](https://mongoclient.com/demo), so you'll be aware whenever it gets ready :)

Thanks again.

**Comment by yuchting** [comment]
Thanks for you reply.
I can understand now. I've subscribed mongoclient mail list.
Wish you all the best in your work.

**Comment by rsercano** [comment]
I've also added update section to docs :) https://mongoclient.com/docs/start.html#update-section
