### ISSUE TITLE
Silder bar is not work in mobile browser.

### ISSUE THREAD

**Issue by yuchting** [nosqlclient/nosqlclient#360]
It's me again. 2.0.0 version in Web (compile).
There's not responsible with this button, I test in [mongoclient Demo](https://www.mongoclient.com/demo), the same situation.

![snipaste20170511_100052](https://cloud.githubusercontent.com/assets/1817716/25928893/5908786c-3631-11e7-8484-e6e0f41af026.png)

My mobile browser is chrome and firefox.
Thanks.

PS, I had a problem with mongoclient 1.5.0 version editor in mobile browser too, I cannot input anything, I want to check it in 2.0.0, so I found this issue.
If you fix this issue, please check it.

**Comment by rsercano** [comment]
Hi @yuchting 

will check it asap, thanks for the feedback.

**Comment by rsercano** [comment]
Hi @yuchting 

I've fixed it, but Mongoclient needs minimum 600-700 width to work properly with the current design unfortunately that needs special attention for a later time. 

Apart from that, I'll update demo as well in an hour :)

Thanks for the feedback

**Comment by yuchting** [comment]
@rsercano 
I appreciate you fixed so quick.
Don't worry about the mobile phone screen size, if it has mini width requirement, I can change the direction of screen from portrait to landscape, the size is enough.

Actually, I operate my mongodb by mongoclient in PC usually, only in a special situation without PC, I will use the mobile phone, so the display problem is not very serious. 

But if you want to use this open source project as a commercial one, you must be focus on it.

Thanks!
