### ISSUE TITLE
Cannot scroll down after added 10+ connections

### ISSUE THREAD

**Issue by yuchting** [nosqlclient/nosqlclient#362]
It's me again...
I added 10+ mongodbs, and cannot to click the bottom button:
![snipaste20170515_103036](https://cloud.githubusercontent.com/assets/1817716/26040655/c4525518-3959-11e7-908b-520538ca20b6.png)

I have to zoom out the page to click.

**Comment by rsercano** [comment]
Hi again @yuchting  :)

thanks for the feedback, I gotta check asap.

Cheers

**Comment by rsercano** [comment]
Hi @yuchting 

I've tried this and I'm able to scroll, would you mind sharing your browser and height information with me ?

Thanks

**Comment by yuchting** [comment]
@rsercano 
It's a simple bug, I just test before few minutes ago, please click "Create New" button and close the creating dialog box, then you cannot scroll the page.

**Comment by rsercano** [comment]
Oh I see now, thanks for the follow up, gotta fix that asap @yuchting

**Comment by rsercano** [comment]
Hi @yuchting 

it's fixed in the current master branch
