### ISSUE TITLE
2.1.0 authentication failed

### ISSUE THREAD

**Issue by HLFH** [nosqlclient/nosqlclient#363]
Hi,

2.0.0 is working fine.
With 2.1.0, I have authentication failed, when I want to switch to another database. 
I can then only be connected to the admin db.

So, I am now using 2.0.0 again.

**Comment by rsercano** [comment]
Hello @HLFH 

could you please be more specific ? What error do you get, what authentication type did you use ?

Thanks

**Comment by HLFH** [comment]
**Authentication type:** _SCRAM_SHA_1_
**Error: MongoError:** _Authentication failed_

> May 15 11:29:08 GLB-0001 meteor[8872]: I20170515-11:29:08.970(1)? 2017-05-15T10:29:08.969Z - info: [connect] mongodb://username:password@127.0.0.1:27017/?connectTimeoMay 15 11:29:08 GLB-0001 meteor[8872]: W20170515-11:29:08.993(1)? (STDERR) 2017-05-15T10:29:08.993Z - error: { [MongoError: Authentication failed.]

**Comment by rsercano** [comment]
I see @HLFH but that seems to be not related with Mongoclient are you able to connect via version 2.0.0 ? Also could you please check your connection's **databaseName** and **authenticationDatabase** after switching database from right upper corner **Connect** button

p.s. you have to disconnect first to see your connections.

**Comment by HLFH** [comment]
1. I am able to connect via version 2.0.0
2. I added admin as Authentication DB and it now works in 2.1.0.

Thank you sir.

**Comment by rsercano** [comment]
I'm glad your issue is fixed :)

**Comment by neitanod** [comment]
Is this issue documented anywhere else?
Being a novice it took me an hour trying different things to switch to a different database with the admin user.
It would be nice to have a little clue for this in the connection edit screen.  Right now it says 

>  Authentication DB: "Specify if user is defined in a different DB"

But my connection uses "admin" DB by default so this condition is false, and it fails when I switch DBs, not on first connection.

**Comment by rsercano** [comment]
Have you checked [here](https://www.nosqlclient.com/docs/user_manual.html#authentication_tab) @neitanod ?

**Comment by neitanod** [comment]
Yes.  There it says:  "Username, password and authentication database. Authentication DB is the database where the user was created, and together with the user’s name, serves to identify the user. You can leave it empty if user is defined in the database that you wish to connect"
The problem for novices like me is that many of us come from the MySQL world where switching database does not mean reconnecting.
The admin user I was using had the *AnyDatabase permissions, so I assumed I could authenticate and then switch.
My suggestion for you is to clarify the tip text a bit to make it clearer for us novices.  Again, just a suggestion of course.
Thanks for your support and such a superb program.

**Comment by rsercano** [comment]
Thanks a lot @neitanod I see your point, nosqlclient focuses on a single database, instead of connecting a server and "double click switching". That's an old behaviour actually, but I'll change the placeholder anyway just to be more clear.

Thanks :)

**Comment by neitanod** [comment]
It would have saved me a lot of time if it said something like:

> Authentication DB: "Specify if user is defined in a different DB _or intending to switch between databases_"
