### ISSUE TITLE
Export as downloadable file and import to somewhere else or db sync?

### ISSUE THREAD

**Issue by xyx2011** [nosqlclient/nosqlclient#366]
first of all, thanks for providing such a great tool, I had some pain point with how import&export works in mongo client.

## Expected Behavior
dump the database, so it can be downloaded and store somewhere else
and later you can restore with this file to a different database
or be able to monitor different database and sync between them.

## Current Behavior
it doesn't allow user take the dump and go restore that database somewhere else.
users have to import json file, which is different than dump file, and import sometimes will fail.

## Possible Solution
using mongoexport and mongorestore under the hood and let user download the exported file and restore into different database. 

## Steps to Reproduce (for bugs)
N/A, this's a feature request.

## Context
sync / restore databases

**Comment by rsercano** [comment]
Hello @xyx2011 

thanks for the feedback, I'm glad you like Mongoclient, as described in the docs (https://mongoclient.com/docs/user_manual.html#dump_restore_import) the only part in the Mongoclient that can't be used for production purposes is the dump section, I'm planning to improve this section really soon as you've mentioned mongo tools will be used probably.

I'll keep this issue as a commit tracker for the requested feature.

Thanks again.

**Comment by xyx2011** [comment]
@rsercano awesome! thanks!

**Comment by rsercano** [comment]
resolved with #372 will be released as 2.2.0 in a few weeks.
