### ISSUE TITLE
Updating records seems to escape stored HTML strings

### ISSUE THREAD

**Issue by cmseaton42** [nosqlclient/nosqlclient#367]
When I update a record in the client, HTML that I have stored is escaped which is not ideal and backlashes are added before quotes 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Mongoclient version used:
* Environment name (e.g. chrome 39, portable, docker):
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12):

**Comment by rsercano** [comment]
Hello  @cmseaton42 

thanks for the feedback, gotta check asap, would you mind sharing which version of mongoclient you're using right now ?

**Comment by cmseaton42** [comment]
I am using v2.1.0.  Do you need any other information?

**Comment by rsercano** [comment]
@cmseaton42 that's enough thank you so much, will check asap

**Comment by rsercano** [comment]
Hello @cmseaton42 

I couldn't reproduce this properly, it puts **\n** for line breaks, is that what you mean ? If not could you please share an example document ?

**Comment by rsercano** [comment]
I assume that's a won't fix issue please feel free to reopen it if you have an issue.
