### ISSUE TITLE
Prompt for user and password

### ISSUE THREAD

**Issue by ghost** [nosqlclient/nosqlclient#374]
Hi,

This is a feature request. It would be nice if we could configure a new connection with authentication enabled but leaving Mongoclient asking for the user and password at each connection (without saving them in meteor DB).

This behaviour is interresting when you have many users and you want to let them access the differents MongoDB servers using their own MongoDB credentials.

Thanks.

**Comment by rsercano** [comment]
Hello @nasskach 

that's an interesting idea, thanks for sharing I'm going to evaluate this for sure. 

Thanks again !
