### ISSUE TITLE
Error creating SSH Tunnel: Timed out while waiting for handshake

### ISSUE THREAD

**Issue by mhillebert** [nosqlclient/nosqlclient#375]
When setting up ssh connection using FQDN of local VM, I got the error "Error creating SSH Tunnel: Timed out while waiting for handshake" on macOS

I changed the SSH host from develop.local to the corresponding IP address and it connected without issue. Note: the IP is listed in /etc/hosts

my configurations were:
Hostname: localhost
Port: 27017
Authentication: None
SSL: Off
SSH Tunnel: Use Password
SSH Hostname: develop.local       <--- changed this to IP and it connects
SSH Tunnel Port: 22
SSH Username: vagrant
SSH Password: *******

This issue is more of a "just to let you know", "you may want to address this" and/or a solution for anyone else that might get stuck with a similar issue using Compass.

**Comment by rsercano** [comment]
Hello @mhillebert 

thanks for the feedback, which distribution are you using, desktop or docker ? I'll investigate this further asap.

Thanks

**Comment by mhillebert** [comment]
desktop

**Comment by rsercano** [comment]
Hi again @mhillebert 

sorry for late response, as I've checked the defaullt readyTimeout was 20 seconds which I think should be enough, but I've changed it to 99 seconds though just in case. 

Also found a suggestion which you may apply to your server to make connections faster. [Here you can check it](https://github.com/mscdex/ssh2/issues/142#issuecomment-45640875)

Feel free to re-open if you encounter anything
