### ISSUE TITLE
If I try to save even the slightest of change, I get an error toast saying the JSON is broken.

### ISSUE THREAD

**Issue by exogenesys** [nosqlclient/nosqlclient#376]
This error is not occuring on some collections. The only differences I can figure out is that ones with no error are small. I know, that's probably of no help.

The error messages says

> Syntax error, can not save document: Broken JSON object body near

And then returns the entire document and overflows the toast.

Otherwise, mongoclient suits us perfectly. Help would really be appreciated. :)

**Comment by rsercano** [comment]
Hello @exogenesys 

I'm glad you liked Mongoclient :) But I need to know how are you trying to save ? Using find query and save button or doing an update query ?

Also which distribution are you using, windows, linux, osx or docker ? And which version of mongodb are you using ?

Thanks

**Comment by exogenesys** [comment]
I'm updating using find query and the save button. I'm using Ubuntu 16.04 and MongoDB is a remote mlab instance which is 3.2.12.

**Comment by rsercano** [comment]
Could you please switch to **Code** mode of json editor from **Tree** and check if you've an error on editor ?

**Comment by rsercano** [comment]
Hello @exogenesys I tried this in all distributions (linux, osx, windows) as well as docker deployment but couldn't reproduce. I've tried this with MongoDB 3.2 and 3.4.

If you encounter again please share an example document or demonstration and reopen the issue, thanks again.
