### ISSUE TITLE
Import function does not import all collections

### ISSUE THREAD

**Issue by ArcanoxDragon** [nosqlclient/nosqlclient#377]
## Expected Behavior

When taking a dump of an existing database and importing the dump into a separate empty database, all collections should be imported and the data in both databases should be identical.

## Current Behavior

When importing a dump of my populated database into an empty one, only one collection is imported, even though both collections appear in the dump's `.tar` file.

## Possible Solution

I don't have enough data to determine which collections would or would not be imported. The first collection alphabetically is the only one being imported for me, but it is also the only collection of two that uses the default `_id` field generated by Mongo. The other collection uses a manually populated `_id` field, which is numeric instead of alphanumeric.

## Steps to Reproduce (for bugs)

1. Create a database with two or more collections
2. Populate all collections with data. Try a mixture of default indexing and custom indexing.
3. Take dump of database
4. On a different database, attempt to import newly created dump
5. Not all collections will be imported

## Your Environment

* Mongoclient version used: 2.1.0 (open source edition)
* Environment name (e.g. chrome 39, portable, docker): portable
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): Windows 10 x64

**Comment by rsercano** [comment]
Hello @briman0094 

unfortunately as of version Mongoclient 2.1.0 dump section is not usable for production environments which has been stated [here](https://mongoclient.com/docs/user_manual.html#dump_restore_import)

But in new version (currently on `master` branch) dump section has been completely reworked, as soon as I release that version (2.2.0) you'll be able to use **mongo** binaries for dump/restore/export/import.

Sorry for the inconvenience and please be patient for the next version which will be released in a  few weeks. 

Thanks

**Comment by dannysood** [comment]
@rsercano Hey. Any update on this? When can we expect 2.2 to drop. Thanks for an awesome product by the way.

**Comment by rsercano** [comment]
Hi @dannysood 

thanks for your kind opinions, 2.2.0 uses mongo binaries, you can think it like a helper/wrapper. Hopefully next week, I'll do release, and you'll get an in-app notification :)

Cheers
