### ISSUE TITLE
Can't connect to a replica set

### ISSUE THREAD

**Issue by yulianovdey** [nosqlclient/nosqlclient#383]
Hello Mongoclient team,

Mongoclient has been awesome to use on my local Mongo instance! Thanks for this tool. I'm here because I tried to add a second connection pointing to a replica set and couldn't.

## Expected Behavior
MongoClient should be able to connect to a replica set.

## Current Behavior
I can't connect using the following URL (actual credentials and host omitted):

`mongodb://user:password@host:port/db?authSource=admin&replicaSet=production&readPreference=secondary`

After a few seconds, I get the following error:

`Couldn't connect: failed to connect to server on first connect...`

The same result if I manually populate the relevant config fields.

I would think this is an issue with our server, but **I tried the same URL using RoboMongo and mongoose** and was able to connect successfully.

## Your Environment

* Nosqlclient version used: 2.1.0
* Environment name (e.g. chrome 39, portable, docker): osx-portable
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): osx 10.12.5

**Comment by rsercano** [comment]
Hello @yulianovdey 

thanks for details. Is your replica 2 hosts only ? Is there anything else that I have to know to reproduce the issue ?

I'll check this as soon as possible.

**Comment by rsercano** [comment]
Hi again @yulianovdey 

I'm able to connect my replica set properly. Could you please try to set **authenticationDatabase** option too ? 

Feel free to re-open this issue if you encounter an error.

**Comment by yulianovdey** [comment]
Hi @rsercano,

Thank you for your reply! My connection string above does have `authSource`, which populated the authentication database option successfully.

What does the replica set you tested with look like? I'll try to reproduce the issue from scratch with a couple of Docker containers and get back to you if I still get an error without the extra variables involved in our production setup.

**Comment by rsercano** [comment]
I arranged a very simple replica set with two instances, I would appreciate that, thanks.
