### ISSUE TITLE
Browsing large collection throws timeout error for distinct fields

### ISSUE THREAD

**Issue by masumsoft** [nosqlclient/nosqlclient#387]
## Expected Behavior
No errors should be thrown. If finding distinct for large collections is a costly operation, then provide an option to disable it in the settings or automatically disable it for large collections.

## Current Behavior
I have a collection with ~186M rows in it. When I browse the collection, I get an error message saying:

`Couldn't fetch distinct fields: connection 410 to 127.0.0.1:27017 timed out.`

## Steps to Reproduce (for bugs)
1. Connect to a database
2. Goto Collections tab
3. Select a collection that has many rows (millions) in it.
4. Wait a few seconds to see the error message

## Context
Trying to browse a large collection

## Your Environment
* Nosqlclient version used: 2.2.0
* Ubuntu 14.04 Server running the nosqlclient app
* Accessed from Google Chrome in  MacOS Sierra

**Comment by rsercano** [comment]
Hi there,

nosqlclient automatically scans for randomly found given the number of documents for auto complete. This can be changeable from [settings](https://www.nosqlclient.com/docs/user_manual.html#settings), set auto complete samples count to 0 to disable it completely or try a small number first.

Let me know if that works for you.
