### ISSUE TITLE
Improve mongodump experience

### ISSUE THREAD

**Issue by cncolder** [nosqlclient/nosqlclient#388]
## Expected Behavior

nosqlclient@2.2.0 in docker

Try new feature mongodump.

## Current Behavior

When I'm trying setup 'Mongo binaries path'. First I exec `which mongodump` in docker container but return nothing. Until I read [.docker/install-mongo.sh](https://github.com/nosqlclient/nosqlclient/blob/master/.docker/install-mongo.sh) I find that path is `/opt/mongodb/bin`

Then I open 'Management - Dump/Restore/Import' page and click 'Execute' button in 'Mongodump' panel. It seems success but I don't know where going my dump. Util I exec `find / -name "dump"` I find the dump folder stay in `/opt/meteor/dist/bundle/programs/server/dump`

## Possible Solution

I think it's better writing `/opt/mongodb/bin` into setting page.

And give `mongodump --out` a default value?

## Your Environment

* Nosqlclient version used: 2.2.0
* Environment name (e.g. chrome 39, portable, docker): docker
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12):  osx 10.12

**Comment by rsercano** [comment]
Hi @cncolder 

thanks for the feedback, actually as far as I remember I was setting mongo binaries path by default, but will double check now. 

Apart from that you can put `out`  argument and write whatever you want to it.

**Comment by rsercano** [comment]
For new setups of nosqlclient, mongo binary path is being set as mentioned properly. Please re-open this if you need anything else. [ref](https://github.com/nosqlclient/nosqlclient/blob/master/server/imports/internal/startup.js#L134)
