### ISSUE TITLE
OSX Zip unable to expand

### ISSUE THREAD

**Issue by gabma** [nosqlclient/nosqlclient#39]
Just downloaded the osx-portable.zip file for testing.
I’m unable to unzip it. The file might be broken ?

**Comment by rsercano** [comment]
Hello, could you please try downloading from this link: https://drive.google.com/file/d/0B6AHuAYWMJwIZmp6NFdtVk03ekk/view?usp=sharing

**Comment by gabma** [comment]
Much better, worked.

But now saying : 
"Check with the developer to make sure Mongoclient works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.”

Running 10.11.4

Anyways I’ll try to host it on a server instead :)
Thx!

**Comment by rsercano** [comment]
Thanks for the pointing mac distribution issue I will fix the main download link. I will re-check the mac version as well thanks again !
