### ISSUE TITLE
(Question) UUID Encoding

### ISSUE THREAD

**Issue by habibialkaff** [nosqlclient/nosqlclient#390]
Hi,

Does nosqlclient support default UUID Encoding like Robo 3T does?

![untitled](https://user-images.githubusercontent.com/1284550/30470162-31db68fe-9a26-11e7-95cf-eab82f758a7e.png)

**Comment by rsercano** [comment]
Hi @habibialkaff 

would you please share an example ?

**Comment by habibialkaff** [comment]
In Mongo C# Driver, if I store a GUID "347709be-3257-47a1-88f4-fab8f1356fdd" in "_id" property, nosqlclient query result will show this as:
`"_id": {
      "$binary": "vgl3NFcyoUeI9Pq48TVv3Q==",
      "$type": "03"
    },`

But in Robo 3T, if I select ".Net Encoding" from the option above, the query result will show:
`"_id" : NUUID("347709be-3257-47a1-88f4-fab8f1356fdd"),`


There's already a helper which I can use to convert the BinData to the GUID string (https://github.com/mongodb/mongo-csharp-driver/blob/master/uuidhelpers.js). But I'm not sure how I can use this in nosqlclient. What I need is whenever I do query on any document in my DB, instead of BinData, it will return the GUID string.

Thanks

**Comment by rsercano** [comment]
I see, unfortunately that's currently not supported, nosqlclient uses [extended json](https://docs.mongodb.com/manual/reference/mongodb-extended-json/) for all BSON types as located in [the documentation](https://www.nosqlclient.com/docs/user_manual.html#extended_json)
I'll keep this issue open for the further reference and will try to implement this for a next version.

Sorry for the inconvenience.

**Comment by rsercano** [comment]
No high popularity on this, `tagging` with rewrite to implement within rewrite process.
