### ISSUE TITLE
SSH Tunnel via Bastion Host

### ISSUE THREAD

**Issue by alexilievski** [nosqlclient/nosqlclient#395]
Hi

Is it possible to connect to a mongodb instance via a SSH bastion host? I tried setting the host to the internal DNS of our mongos instance but I get the following error when trying to connect.

Couldn't connect: failed to connect to server [mongos01.mongos.mongodb.internal:27017] on first connect [MongoError: getaddrinfo ENOTFOUND mongos01.mongos.mongodb.internal mongos01.mongos.mongodb.internal:27017]

It looks like the host is checked before a SSH connection is made.

- Alex

**Comment by rsercano** [comment]
Hi @alexilievski 

all SSH connections are made through tunnel-ssh npm module. If there's such check that should be made by them, apart from that you may check [here](https://www.nosqlclient.com/docs/user_manual.html#ssh_tab), you may have a wrong configuration to connect through a tunnel. 

Let me know if you need anything else

**Comment by rsercano** [comment]
please re-open if your issue persists.
