### ISSUE TITLE
tunnelssh not found

### ISSUE THREAD

**Issue by sinnlosername** [nosqlclient/nosqlclient#397]
## Expected Behavior
Start normally.

## Current Behavior
It spam's the following error on start: https://hastebin.com/obihelusog.hs

## Steps to Reproduce (for bugs)
I've just installed it by source as you explained it on your website

## Context
I really don't have any idea, as I know nearly nothing about nodejs. If you need anything, just ask

## Your Environment
* Nosqlclient version used: latest master.zip
* Environment name (e.g. chrome 39, portable, docker): meteor-version from source
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): Ubuntu 16.04

**Comment by rsercano** [comment]
Hello @sinnlosername 

this happens on some environmentes randomly, I couldn't find a proper way to pass it. But the easiest solution is;

`cp -R 'nosqlclient-master/.meteor/local/build/programs/server/npm/node_modules/tunnel-ssh'  'nosqlclient-master/.meteor/local/build/programs/server/npm/node_modules/meteor/modules-runtime/node_modules/'));`

So you basically should copy tunnel-ssh folder from `nosqlclient-master/.meteor/local/build/programs/server/npm/node_modules/tunnel-ssh` into `nosqlclient-master/.meteor/local/build/programs/server/npm/node_modules/meteor/modules-runtime/node_modules/`

I'll add this to documentation as well, thanks !
