### ISSUE TITLE
Reverse-Proxy

### ISSUE THREAD

**Issue by sinnlosername** [nosqlclient/nosqlclient#398]
## Expected Behavior
Load the site normally

## Current Behavior
Doesn't load, just grey

## Possible Solution
It works if I don't use nginx as reverse proxy, but I want to use it to get a normal vhost subdomain.

## Steps to Reproduce (for bugs)
Just do an nginx reverse proxy to nosqlclient. Here's the nginx config:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name nosql.my.tld;

    include snippets/ssl.conf;

    location / {
        proxy_pass http://127.0.0.1:8068;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $http_CF-Connecting-IP;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $http_CF-Connecting-IP;
    }

}
```

## Context
I'm using nginx as reverse proxy. I'm also using cloudflare, but I've enabed websockets in cloudfare and it work, so it's relted to nosqlclient or nginx.

## Your Environment
* Nosqlclient version used: Latest master
* Environment name (e.g. chrome 39, portable, docker): Meteor version from source
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): Ubuntu 16.04

**Comment by rsercano** [comment]
Hi @sinnlosername 

actually that should be described in the [docs](https://www.nosqlclient.com/docs/start.html#compile). You need to set an environment variable before starting your app;

`export ROOT_URL=http://www.nosqlclient.com/demo`

Also may I suggest you to use docker ? It's pretty easier than compiling nosqlclient every time. 

p.s. [Nosqlclient demo ](https://www.nosqlclient.com/demo) actually uses nginx and docker.

**Comment by sinnlosername** [comment]
I've added the env variable, but it didn't help. I'm getting no errors on terminal, but there is an error in the javascript console:

`There is no route for the path: /`

**Comment by sinnlosername** [comment]
You might take a look on it here: http://bit.ly/2ziGKbc

**Comment by rsercano** [comment]
But how did you set `ROOT_URL` ? In docker I'm using this as its value:  

`http://localhost/demo`

If you're not using docker, [checkout here](https://www.digitalocean.com/community/tutorials/how-to-deploy-a-meteor-js-application-on-ubuntu-14-04-with-nginx)

**Comment by sinnlosername** [comment]
Okay, seems to work now. Maybe I've failed something yesterday. Thanks
