### ISSUE TITLE
External links clicked from within Mongoclient opens up internally

### ISSUE THREAD

**Issue by biphobe** [nosqlclient/nosqlclient#40]
An example of that can be "mongoclient.com" link from the app's footer - if clicked, it won't open externally in the browser on the outside, instead, it will open in the MongoClient and will replace the whole application. The only way to go back is to restart the client.

**Comment by rsercano** [comment]
Hello, since application has been built by electron for the desktop portables you are right, I'm going to find a workaround for it but currently it's a minor issue in the list. Thanks for the contributin
