### ISSUE TITLE
Cannot find module tunnel-ssh

### ISSUE THREAD

**Issue by lopugit** [nosqlclient/nosqlclient#406]
I'm having the same issue as over here:
https://github.com/nosqlclient/nosqlclient/issues/205

Where can you download that latest version?

I'm getting the same error when cloning the git repo and running meteor

**Comment by rsercano** [comment]
Hello,

[here](https://github.com/nosqlclient/nosqlclient#distributions) you can download latest distribution but if you want to compile with meteor, now you have to follow here #401 I'll write this to documentation asap.
