### ISSUE TITLE
Failure to launch on OSX 10.11.13

### ISSUE THREAD

**Issue by nmcclay** [nosqlclient/nosqlclient#41]
Fresh download of 1.0 version from github page, permissions are set to launch any application, however on launch this error is displayed:

![image](https://cloud.githubusercontent.com/assets/913988/14228405/a89ef1f0-f8e1-11e5-87d4-04ae8aafad80.png)

**Comment by rsercano** [comment]
Hello I'm aware of this issue, and going to fix, upload correct portable as soon as possible.

**Comment by nmcclay** [comment]
cool, much appreciated

**Comment by rsercano** [comment]
Could you please retry from the same link ? App name will be **my-electrified-app**

**Comment by nmcclay** [comment]
yep that works!

**Comment by rsercano** [comment]
Great, closing issue for now, I need to package for OsX with a better icon and name soon :)
