### ISSUE TITLE
[Mongo 3.6] Coudn't execute query: The cursor option is required, except for aggregate with the explain argument

### ISSUE THREAD

**Issue by yuricamara** [nosqlclient/nosqlclient#419]
## Expected Behavior
Running aggregate.

## Current Behavior
It is not possible to run aggregate. When I try it, it appears the following message:
"Coudn't execute query: The cursor option is required, except for aggregate with the explain argument"

## Steps to Reproduce (for bugs)
1. Update MongoDb to version 3.6
2. Run any aggregate operation.

## Context
Aggregate works with MongoDB version 3.4.

## Your Environment
* Nosqlclient version used: 2.2.0
* Environment name (e.g. chrome 39, portable, docker): chrome 63 64 bits.
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): Windows 10

**Comment by rsercano** [comment]
Hello @yuricamara unfortunately we can't support 3.6 before this summer, you can read more about it from [here](https://medium.com/mongoclient/were-having-a-break-for-a-short-time-a845ac70ebd6)

**Comment by yuricamara** [comment]
Ok! Thank you for your reply

**Comment by rsercano** [comment]
@yuricamara with the master branch you now should be able to execute aggregation queries.
