### ISSUE TITLE
oid do look strange for one DBRef, but do look ok in an array of DBRefs?

### ISSUE THREAD

**Issue by mrohnstock** [nosqlclient/nosqlclient#42]
I'm using mongoclient 1.0.0 linux portable x64 with mongodb 3.2.3. I've many documents with `DBRef`s, which reference to a different document. The `oid` in the `DBRef` get's displayed like this:

```
{
  "_id": "5358e37f3d78591c418b4567",
  "createdBy": {
      "_bsontype": "DBRef",
      "namespace": "user",
      "oid": {
        "_bsontype": "ObjectID",
        "id": "O}\u0000èOÓKZ\u0000\u0000\u0000"
      },
      "db": "test"
    },
}
```

but should get displayed like:

```
{
  "_id": "5358e37f3d78591c418b4567",
  "createdBy": {
      "_bsontype": "DBRef",
      "namespace": "user",
      "oid": "5358d7193d78591e308b4567",
      "db": "test"
    },
}
```

This only happen with a single DBRef, not with an array of DBRefs.

**Comment by rsercano** [comment]
I've reproduced same error at my local storage, sorry for the inconvenience, will fix this asap.

**Comment by rsercano** [comment]
fixed you can use it through meteor after downloading zip of source code or after 1.1.0 release. Thanks for understanding

**Comment by mrohnstock** [comment]
Thanks, I really appreciate your work :)!

**Comment by rsercano** [comment]
Thank you more features are incoming very soon :)
