### ISSUE TITLE
can't name collection

### ISSUE THREAD

**Issue by Calvix-Xu** [nosqlclient/nosqlclient#424]
Sometimes when creating a collection ,I can't click on the name input area,so couldn't input name in the area.This problem also happens when rename a collection. 
## Expected Behavior

The name and rename area should be able to edit.
## Current Behavior

Sometimes when creating a collection ,I can't click on the name input area,so couldn't input name in the area.This problem also happens when rename a collection. 
## Possible Solution

Fix the bug,thanks!~
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Nosqlclient version used: 2.2.0
* Environment name (e.g. chrome 39, portable, docker):
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12):windows 10

**Comment by rsercano** [comment]
Hello @Calvix-Xu 

thanks for informing us about this, do you encounter with this with any other areas ?

**Comment by rsercano** [comment]
Tried this on a few environments and couldn't reproduce, please let us know if this happens again with the details of environment that you're using nosqlclient
