### ISSUE TITLE
Required permissions for database stats

### ISSUE THREAD

**Issue by elisiariocouto** [nosqlclient/nosqlclient#425]
Hello,

I'm setting up a nosqlclient container to connect to an auth-enabled Mongo instance. I need to provide a user and a password on the `MONGO_URL` environment variable. I've tried creating a user with the `clusterMonitor` role but nosqlclient says that it cannot delete on the shell_commands collection. What are the minimum permisions to connect succesfully to an auth-enabled Mongo instance?

**Comment by rsercano** [comment]
Hello,

you can simply provide your **MONGO_URL** and connect to your instance from nosqlclient, I recommend you to [read here](https://nosqlclient.com/docs/user_manual.html#connection_name_url_tab) and let me know if you can manage to connect.

**Comment by elisiariocouto** [comment]
Hello @rsercano, I understand the `MONGO_URL` variable but my question is the minimum required permissions to connect to an auth enabled mongo instance. I don't want nosqlclient to connect with full privileges to my mongo instance, so I need to know the minimum required permissions in order to create a user for nosqlclient.

**Comment by rsercano** [comment]
I see @elisiariocouto as described [here](https://nosqlclient.com/docs/user_manual.html#db_stats) nosqlclient executes [serverStatus ](https://docs.mongodb.com/manual/reference/command/serverStatus/) query so you need a user who can execute this query.
