### ISSUE TITLE
Shell command doesn't work

### ISSUE THREAD

**Issue by p4scu41** [nosqlclient/nosqlclient#430]
I'm trying to execute a command on shell but i doesn't work.

I compiled the project as Meteor Application (WEB) (Meteor 1.6.0.1)

I have MongoDB 2.6.10, and create a user as follow:

```
use mydb;
db.createUser({
  "user": "admindb",
  "pwd": "password",
  "roles": ["read", "readWrite", "dbAdmin", "dbOwner",
    {"role": "backup", "db": "admin"}, 
    {"role": "restore", "db": "admin"},
    {"role": "read", "db": "admin"}
  ]
});
```

I connect on terminal successfully.

I connect on Nosqlclint with the url mongodb://admindb:password@127.0.0.1:27017/mydb

I can navigate through the collections and see the data, but when I try to execute a command on shell I get this error:

```
W20180311-19:29:04.293(-6)? (STDERR) 2018-03-12T01:29:04.292Z - error: uncaughtException: read ECONNRESET {"date":"Sun Mar 11 2018 19:29:04 GMT-0600 (CST)","process":{"pid":1968,"uid":1000,"gid":1000,"cwd":"/var/www/html/nosqlclient/.meteor/local/build/programs/server","execPath":"/home/adminetl/.meteor/packages/meteor-tool/.1.6.0.1l0odv6.2wbx++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node","version":"v8.8.1","argv":["/home/adminetl/.meteor/packages/meteor-tool/.1.6.0.1l0odv6.2wbx++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node","/var/www/html/nosqlclient/.meteor/local/build/main.js","program.json"],"memoryUsage":{"rss":82874368,"heapTotal":47329280,"heapUsed":41991800,"external":44145079}},"os":{"loadavg":[62.8408203125,63.45166015625,62.40869140625],"uptime":250525},"trace":[{"column":11,"file":"util.js","function":"_errnoException","line":1024,"method":null,"native":false},{"column":25,"file":"net.js","function":"Pipe.onread","line":618,"method":"onread","native":false}],"stack":["Error: read ECONNRESET","    at _errnoException (util.js:1024:11)","    at Pipe.onread (net.js:618:25)"]}                                                                       
=> Exited with code: 1
I20180311-19:29:11.177(-6)? 2018-03-12T01:29:11.176Z - info: [insert-default-settings]
I20180311-19:29:11.183(-6)? 2018-03-12T01:29:11.183Z - info: [migrate-connections]
=> Meteor server restarted
```

* Nosqlclient version used:
2.2.0
* Environment name (e.g. chrome 39, portable, docker):
Google Chrome Versión 65.0.3325.146 (Build oficial) (64 bits)
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12):
Ubuntu 16.04 LTS x64

**Comment by rsercano** [comment]
Thanks for sharing will investigate asap but it won't possible to solve this till end of this month due to [this](https://medium.com/mongoclient/were-having-a-break-for-a-short-time-a845ac70ebd6) Sorry for the inconvenince @p4scu41

**Comment by rsercano** [comment]
Hello @p4scu41 

I just checked this and your mongodb version is too old, and it's not supported anymore. Even MongoDB will unsupport 3.2 very soon, it's impossible to support that much old versions, would you please try to set your mongodb instances (2.6) from settings and try again ?

If it doesn't work would you please tell me if that's working with newer versions of mongodb ?
