### ISSUE TITLE
Docker: unexpected docker host user owns the mongoclient's internal mongodb process 

### ISSUE THREAD

**Issue by khelkun** [nosqlclient/nosqlclient#433]
This is probably not related to the mongoclient Docker image but I've been looking into to the nosqlclient sources to figure out what's going on and I'd really need some help to find a possible root cause.

## Expected Behavior
I launch mongoclient/mongoclient docker container from DockerHub latest image.  I did declare the `/data/db` of the container as a bind mount volume that points to `/mnt/mongoclient_datadb` on my the Docker Host filesystem. I pre-created the `/mnt/mongoclient_datadb` directory with 'myuser' who belongs to the 'docker' group.
I've done that on 2 distinct Docker hosts. 
On one docker host the `/mnt/mongoclient_datadb` is populated with the mongodb data files created by 'myuser' that runs the "docker run" command. This seems fair and when I look at the htop on the Docker host, I see that `dockercontainerd` process for the mongoclient container is owned by the 'root' user and it has a child-process `node main.js` owned by 'myuser'. The `node main.js` process has a child-process `mongod --storageEngine=wiredTiger` also owned by 'myuser'.

## Current Behavior
On another docker host  the `/mnt/mongoclient_datadb` is populated with another Linux user 'anotheruser' of the Docker host who's not 'myuser' who runs the "docker run" command. This 'anotheruser' also owns the `node main.js` and  `mongod --storageEngine=wiredTiger` child processes of the `dockercontainerd` process still owned by the 'root' user.

## Your Environment
* Nosqlclient version used: mongoclient/mongclient:2.2.0 DockerHub image 
* Environment name: docker 17.12.1-ce
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): Ubuntu 17.10 artful

**Comment by khelkun** [comment]
Nevermind I think I figured it out and it has nothing todo with the mongoclient/mongoclient DockerHub image
Apparently 'myuser' on the first host has UID 1000 and 'anotheruser' on the second host has the exact same UID 1000.
The point is I indeed used mongoclient/mongoclient:latest from DockerHub on the first hsot but then I used `docker commit` on the first host container to create a new mongoclient image that I pushed to my own Docker Private Registry. Then I pulled this new image on the second host and created a container from this image. So forth I guess the my new image from my Docker Private Registry has setup the node user UID to be 1000 whatever is the user who create the container.
Please close the issue

**Comment by khelkun** [comment]
I figured it out
Apparently the 'node' user in the container has UID 1000
So on my first host the 'myuser' who runs the container has the UID 1000 but on the second host 'myuser' has UID 1005 and the UID 1000 is owned by 'anotheruser'

**Comment by rsercano** [comment]
Hello @khelkun I'm glad you've got it
