### ISSUE TITLE
Are there plans to release a Windows docker image?

### ISSUE THREAD

**Issue by leighghunt** [nosqlclient/nosqlclient#436]
Attempt to pull the docker image on Windows gives the following error:

```
PS C:\Windows\system32> docker pull mongoclient/mongoclient
Using default tag: latest
latest: Pulling from mongoclient/mongoclient
image operating system "linux" cannot be used on this platform
PS C:\Windows\system32> docker pull mongoclient/mongoclient:2.2.0
2.2.0: Pulling from mongoclient/mongoclient
image operating system "linux" cannot be used on this platform
PS C:\Windows\system32>
```

## Expected Behavior

Hoping that image might be made available for Windows.

## Current Behavior

Docker image is based off `debian:jessie`, and won't execute on Windows.

## Steps to Reproduce (for bugs)

1. On a Windows server, run the following in an administrative PowerShell:
`docker pull mongoclient/mongoclient`

## Your Environment

* Nosqlclient version used: Running mongodb in a container
* Environment name (e.g. chrome 39, portable, docker): Docker 17.06.2-ee-6
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): Windows Server 2016 Datacenter
```
PS C:\Windows\system32> docker info
Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 49
Server Version: 17.06.2-ee-6
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2035.amd64fre.rs1_release_inmarket.180110-1910)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 14GiB
Name: ATGEEDEV02
ID: XAMQ:L53P:TUUH:7VPS:O6FD:ZXQX:4TNF:BJXZ:CFJW:EJQU:BEUG:BCS5
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: eagleaisfeed
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by rsercano** [comment]
Thanks @leighghunt we'll investigate this and will try to make it work on windows too asap.

**Comment by rsercano** [comment]
Hello @leighghunt, as I now able to try this, I managed to make it work with no issues. I managed to work with nosqlclient on windows machines. Can't you use linux type containers ?

**Comment by leighghunt** [comment]
Hi @rsercano, not on this particular project, no unfortunately - stuck with Windows containers, as the host is Windows Server 2016 Datacenter, which I don't believe supports LCOW?

**Comment by rsercano** [comment]
@leighghunt just saw [such an article](https://www.deploycontainers.com/2017/10/31/run-linux-containers-windows-server-2016-version-1709/) but can be experimantal, didn't read carefully,  in the end I can't guarantee that we'll implement a windows docker container since we got a lot to do and has not really much time :(

**Comment by leighghunt** [comment]
Completely understand - Windows containers has certainly been a bit of a frustration for me too! Suspect medium term solution for my use-case is to wait for first-class LCOW support in Windows, or just move my workload to a Linux host, as most issues I've had with Docker have been Windows specific.

Thanks for your time and considering this issue.

**Comment by rsercano** [comment]
Thank you for your understanding !
