### ISSUE TITLE
Using it as a webapp?

### ISSUE THREAD

**Issue by dpacmittal** [nosqlclient/nosqlclient#44]
Is it possible to use mongoclient as a webapp for administration and monitoring of DB on the server? I find this far better than mongo-express but I'm not sure if it can be used through chrome.

**Comment by rsercano** [comment]
Yes, it's absolutely possible to use mongoclient as web application. You can examine the wiki section [Compile From Source](https://github.com/rsercano/mongoclient/wiki#31-compile-from-source-browser-edition)

To summarize:
1. Install [MeteorJS](https://www.meteor.com/) (It supports all platforms)
2. Download [latest source of Mongoclient](https://github.com/rsercano/mongoclient/archive/master.zip)
3. Unzip and navigate into **mongoclient-master**
4. Execute command `meteor --port 3000` (Port is optional)
5. Navigate **localhost:3000** from your browser 

Everything should work, thanks for your opinions :)
