### ISSUE TITLE
Support for MongoDB 4.0

### ISSUE THREAD

**Issue by Pete-PlaytimeSolutions** [nosqlclient/nosqlclient#447]
Is there any plans to support MongoDB V4.0 of the app, anytime soon?

**Comment by rsercano** [comment]
Yes it does, we're just arranging our development again, soon it'll be better (faster development as usual).

Thanks for your interest, will keep this open for further reference.

**Comment by lolclark** [comment]
Cheers for this, been lost since moving to mongoDB 3.6 and no UI. Keep up the great work ! ;)

**Comment by rsercano** [comment]
Thx @Torquin hopefully I'm planning to opt in more than ever this weekend :)
