### ISSUE TITLE
Make "/healthcheck" accessible without authorization

### ISSUE THREAD

**Issue by oskorokhoda** [nosqlclient/nosqlclient#451]
Currently, if you enable authorization in Nosqlclient the health endpoint "/healthcheck" is secured as well. Therefore, to check the health you have to add "Authorization" header with basic authorization.

The downside of it is that you have to expose credentials to a third party to be able to check the health. It would be great if the "/healthcheck" is accessible without authorization even if it is enabled.

**Comment by rsercano** [comment]
Hello @oskorokhoda we'll check that out, seems considerable.
