### ISSUE TITLE
After connecting to database certain values not populated

### ISSUE THREAD

**Issue by daniyel** [nosqlclient/nosqlclient#454]
## Expected Behavior
Login into replica set. Go to **Management > Admin Queries**. Under **Admin Query** the dropdown is populated with various options.

## Current Behavior
Login into replica set. Go to **Management > Admin Queries**. Under **Admin Query** the dropdown is empty. **User Management** as well empty. After hitting Refresh button. Nothing happens. After few times refreshing and connecting, sometimes it works and sometimes it does not at all. On **Database Stats** I can see graphs populated with data.

![Image](https://image.ibb.co/dxqoSp/Screen_Shot_2018_08_31_at_11_15_33.png)

## Possible Solution
At least some error message, if there are some connection problems. At the moment there is sometimes just timeout error. 

## Steps to Reproduce (for bugs)
1. AWS EC2 instance (t2.small, Ubuntu 16.04 LTS) with public IP
2. MongoDB installed inside same EC2 instance, bind ip set to 0.0.0.0
3. nosqlclient run as `sudo docker run -d -p 80:3000 -e MONGO_URL=mongodb://172.17.0.1:27017 -e MONGOCLIENT_AUTH=true -e MONGOCLIENT_USERNAME=myusername -e MONGOCLIENT_PASSWORD=mypassword -v /data/nosqlclient/db:/data/db mongoclient/mongoclient`

## Context
I am trying to create users and on some replica sets it is working and on this particular one it does not.

## Your Environment
* Nosqlclient version used: 2.2.0 (Docker)
* Environment name: Chrome Version 68.0.3440.106 (Official Build) (64-bit), docker:
* Operating System and version: osx 10.13.3:

**Comment by rsercano** [comment]
Thanks for the detailed explanation, would you please try with the `latest` docker image and see if you can reproduce this ?

**Comment by daniyel** [comment]
Hi. I am using latest tag, just i wrote 2.2.0 for better reference.

**Comment by daniyel** [comment]
Hm. now I restarted the docker container because the old one was in exited state and I can now see the Admin Query options, I can see the already existing users in User Management etc.

**Comment by rsercano** [comment]
Oh okay, I'm glad your issue is fixed @daniyel, feel free to reopen this issue if the issue occurs again.
