### ISSUE TITLE
Can't connect to external db via docker-compose

### ISSUE THREAD

**Issue by dszymczuk** [nosqlclient/nosqlclient#456]
## Expected Behavior
I should connect to external mongodb.

## Current Behavior
At now, I can't connect to mongodb . I've got error:

> {"error":{"name":"MongoNetworkError","message":"failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.27.0.3:27017]"},"level":"error","message":"uncaughtException: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.27.0.3:27017]\nMongoError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.27.0.3:27017]\n    at Pool.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:505:11)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:329:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","stack":"MongoError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.27.0.3:27017]\n    at Pool.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:505:11)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:329:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","exception":true,"date":"Sun Oct 28 2018 12:29:18 GMT+0000 (UTC)","process":{"pid":1,"uid":1000,"gid":999,"cwd":"/opt/meteor/dist/bundle/programs/server","execPath":"/opt/nodejs/bin/node","version":"v8.4.0","argv":["/opt/nodejs/bin/node","/opt/meteor/dist/bundle/main.js","program.json"],"memoryUsage":{"rss":111525888,"heapTotal":80977920,"heapUsed":62010640,"external":20809311}},"os":{"loadavg":[0.08642578125,0.056640625,0.056640625],"uptime":8495},"trace":[{"column":11,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js","function":null,"line":505,"method":null,"native":false},{"column":13,"file":"events.js","function":"emitOne","line":115,"method":null,"native":false},{"column":7,"file":"events.js","function":"Pool.emit","line":210,"method":"emit","native":false},{"column":12,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js","function":null,"line":329,"method":null,"native":false},{"column":30,"file":"events.js","function":"Object.onceWrapper","line":318,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"emitTwo","line":125,"method":null,"native":false},{"column":7,"file":"events.js","function":"Connection.emit","line":213,"method":"emit","native":false},{"column":50,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js","function":null,"line":245,"method":null,"native":false},{"column":30,"file":"events.js","function":"Object.onceWrapper","line":316,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"emitOne","line":115,"method":null,"native":false},{"column":7,"file":"events.js","function":"Socket.emit","line":210,"method":"emit","native":false},{"column":8,"file":"internal/streams/destroy.js","function":"emitErrorNT","line":64,"method":null,"native":false},{"column":11,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":138,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js","function":"process._tickDomainCallback","line":218,"method":"_tickDomainCallback","native":false}]}
=> Starting app on port 3000...
{"error":{"name":"MongoError","message":"command delete requires authentication","ok":0,"errmsg":"command delete requires authentication","code":13,"codeName":"Unauthorized"},"level":"error","message":"uncaughtException: command delete requires authentication\nMongoError: command delete requires authentication\n    at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:593:63\n    at authenticateStragglers (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:516:16)\n    at Connection.messageHandler (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:552:5)\n    at emitMessageHandler (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:309:10)\n    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:452:17)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at addChunk (_stream_readable.js:266:12)\n    at readableAddChunk (_stream_readable.js:253:11)\n    at Socket.Readable.push (_stream_readable.js:211:10)\n    at TCP.onread (net.js:585:20)","stack":"MongoError: command delete requires authentication\n    at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:593:63\n    at authenticateStragglers (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:516:16)\n    at Connection.messageHandler (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:552:5)\n    at emitMessageHandler (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:309:10)\n    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:452:17)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at addChunk (_stream_readable.js:266:12)\n    at readableAddChunk (_stream_readable.js:253:11)\n    at Socket.Readable.push (_stream_readable.js:211:10)\n    at TCP.onread (net.js:585:20)","exception":true,"date":"Sun Oct 28 2018 12:29:28 GMT+0000 (UTC)","process":{"pid":1,"uid":1000,"gid":999,"cwd":"/opt/meteor/dist/bundle/programs/server","execPath":"/opt/nodejs/bin/node","version":"v8.4.0","argv":["/opt/nodejs/bin/node","/opt/meteor/dist/bundle/main.js","program.json"],"memoryUsage":{"rss":196075520,"heapTotal":165859328,"heapUsed":136960224,"external":56461545}},"os":{"loadavg":[0.146484375,0.0712890625,0.0615234375],"uptime":8505},"trace":[{"column":63,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js","function":null,"line":593,"method":null,"native":false},{"column":16,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js","function":"authenticateStragglers","line":516,"method":null,"native":false},{"column":5,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js","function":"Connection.messageHandler","line":552,"method":"messageHandler","native":false},{"column":10,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js","function":"emitMessageHandler","line":309,"method":null,"native":false},{"column":17,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js","function":null,"line":452,"method":null,"native":false},{"column":13,"file":"events.js","function":"emitOne","line":115,"method":null,"native":false},{"column":7,"file":"events.js","function":"Socket.emit","line":210,"method":"emit","native":false},{"column":12,"file":"_stream_readable.js","function":"addChunk","line":266,"method":null,"native":false},{"column":11,"file":"_stream_readable.js","function":"readableAddChunk","line":253,"method":null,"native":false},{"column":10,"file":"_stream_readable.js","function":"Socket.Readable.push","line":211,"method":"push","native":false},{"column":20,"file":"net.js","function":"TCP.onread","line":585,"method":"onread","native":false}]}

## Steps to Reproduce (for bugs)
1. Use docker-compose.yml:

```
version: '3'

volumes:
  mongodbdb:
  redis:

services:
  mongodb:
    image: mongo
    networks:
    - dw
    volumes:
    - mongodbdb:/data/db
    ports:
    - ${MONGO_PORT}:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

networks:
  dw:
```

2. Use docker-compose-dev.yml:

```
version: '3'
volumes:
  mongoclient:

services:
  mongoclient:
    image: mongoclient/mongoclient
    networks:
    - dw
    depends_on:
    - mongodb
    volumes:
    - mongoclient:/data/db
    ports:
    - ${MONGOCLIENT_WEB}:3000
    environment:
    - MONGO_URL=mongodb://mongodb:${MONGO_PORT}/meteor

networks:
  dw:
```

3. Use `.env` file:

```
MONGO_PORT=27017

### dev
MONGO_INITDB_ROOT_USERNAME=root
MONGO_INITDB_ROOT_PASSWORD=root
```

4. Run:

`docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d`

## Context
I would like to run mongoclient.

## Your Environment

* Nosqlclient version used: latest
* Mongodb version used: 4 (4.0.3)
* Environment name (e.g. chrome 39, portable, docker): docker
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): osx 10.14

**Comment by dszymczuk** [comment]
I've removed from docker-compose.yml:

```
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
```

And it works.

**Comment by rsercano** [comment]
I'm glad your issue is fixed @dszymczuk

**Comment by rizkysyazuli** [comment]
sorry to wake up an old issue. but i got a similar error.

not creating a root mongo user just doesn't seem safe to me. so I tried to add the username & password using one of these two environment variables. but none seems to work.

    MONGO_URL=mongodb://someuser:Th3P4ssw0rd!@mongo:27017/
    MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://someuser:Th3P4ssw0rd!@mongo:27017/

any advise on how to enable authentication in mongo and still make this run?

**Comment by rsercano** [comment]
Hi @rizkysyazuli,

you can actually use UI to create a new connection and it's super simple to use whatever authentication type you want. 

**MONGO_URL**  environment variable is for mongoclient to use a database, and **MONGOCLIENT_DEFAULT_CONNECTION_URL** is for a default connection for startup, so you don't have to actually use both.
