### ISSUE TITLE
Communicators sometimes don't work

### ISSUE THREAD

**Issue by Michaelhoooo** [nosqlclient/nosqlclient#457]
When I used the Communicator to get the data, I found that the Communicator did not work, did not get the data, and did not report an error, or did not execute at all.

**Comment by Michaelhoooo** [comment]
![image](https://user-images.githubusercontent.com/18457848/47638927-fe23b680-db9a-11e8-8fe0-4f32209c3321.png)

When I clicked the Switch Database button several times, the above code was not executed, and the console would say nothing，Or the code is not executed。

![image](https://user-images.githubusercontent.com/18457848/47639078-683c5b80-db9b-11e8-9cf3-27fe1312ff18.png)

The server is also not executed.

**Comment by rsercano** [comment]
Hello @Michael199315 which version or system are you using mongoclient on ? I'll try to check that

**Comment by Michaelhoooo** [comment]
> Hello @Michael199315 which version or system are you using mongoclient on ? I'll try to check that

version": "2.2.0",

**Comment by rsercano** [comment]
@Michael199315 would you please try with the latest **master** branch ?

**Comment by Michaelhoooo** [comment]
@rsercano I'm using the latest branch。
I want to ask, under what circumstances would Communicator not work？

**Comment by Michaelhoooo** [comment]
@rsercano 
Like this,
![image](https://user-images.githubusercontent.com/18457848/47694343-3fb66f00-dc38-11e8-99fc-c8d8b410567a.png)

No data return, no error, callback is not executed, and the console is not printed

**Comment by rsercano** [comment]
@Michael199315 I see, actually I'm using latest branch too and it's working properly, couldn't reproduce your issue. Communicator should work on any circumstances, but why don't you put a database name on the screen you mentioned, would you please try with a proper database name in the screen ?

**Comment by Michaelhoooo** [comment]
@rsercano 

Look at my figure, there is no data in the popup window of the database, because when the client calls the listDatabases method to get the data, the Communicator is not executed and the entire callback is not executed, so the popup window has nothing and the button is always in the loading state.

It's just that sometimes, in most cases, it's normal.

**Comment by Michaelhoooo** [comment]
WebSocket is already in CLOSING or CLOSED state.

![image](https://user-images.githubusercontent.com/18457848/47702156-03ded200-dc57-11e8-93b3-b3745d4c86eb.png)

**Comment by rsercano** [comment]
@Michael199315  Hmm, that can be related with meteor build, are you compiling from source ?

**Comment by Michaelhoooo** [comment]
@rsercano  yes

**Comment by rsercano** [comment]
Okay I'll check that again @Michael199315

**Comment by Michaelhoooo** [comment]
Thank you for your reply

**Comment by Michaelhoooo** [comment]
![image](https://user-images.githubusercontent.com/18457848/47710434-bc177500-dc6d-11e8-9ff3-cd1a43f454dd.png)

@rsercano I don't know what the problem is。

**Comment by rsercano** [comment]
I tried various methods and operating systems to reproduce this but it seems like somehow your system blocks the websocket call and close it before the execution, that's why you see no log either on server or on client

**Comment by Michaelhoooo** [comment]
@rsercano 
Yes, it should be caused by the disconnection of websocket, but it's not just my computer, it's my friend's. Websocket will always be disconnected for no reason.
It was when I clicked on the socket many times, or after sending the socket request many times, that it suddenly broke.

Anyway, thanks for your reply.

My computer is the Mac book pro 2018. The system is: MAC OS 10.13.6
My friend's computer is the Mac book pro 2016

**Comment by rsercano** [comment]
Will check that as soon as possible @Michael199315 no worries

**Comment by Michaelhoooo** [comment]
@rsercano 
Thank you. If you find the reason, please let me know.
Thank you very much

**Comment by Michaelhoooo** [comment]
@rsercano 
![image](https://user-images.githubusercontent.com/18457848/47830575-6951d080-ddc7-11e8-902a-5b87c3ca7ed1.png)

This is a service-side exception, All Exceptions caught

**Comment by rsercano** [comment]
I tried on a few machines to reproduce this but no luck @Michael199315, unfortunately I don't have a mac (osx), and noone around has it.

**Comment by rsercano** [comment]
Have you solved your problem @Michaelhoooo  ?

**Comment by rsercano** [comment]
closing this as outdated and cannot reproduce.
