### ISSUE TITLE
Connectionstring is logged

### ISSUE THREAD

**Issue by wiegandf** [nosqlclient/nosqlclient#459]
Hi,

even if nosqlclient is not thought to be used in production environments, it would be nice if the connection strings (or passwords) would not be logged. 

An option could be to set the log level via environment variables. Is that possible?

**Comment by rsercano** [comment]
Sure thing, and actually I wonder why do you think it's not considered to be a good idea to use it on production ? I'm actually using it on production with no issues

**Comment by rsercano** [comment]
Hello @wiegandf I've changed log level to `debug` for connection string logging, the default log level is `debug` you can change it by environment variable: `MONGOCLIENT_LOG_LEVEL`
