### ISSUE TITLE
Docker Default Connection

### ISSUE THREAD

**Issue by unattended-user** [nosqlclient/nosqlclient#460]
Using Docker image with MONGOCLIENT_DEFAULT_CONNECTION_URL env variable throws an error that causes the container to not start.

Thrown error (exception):
```
uncaughtException: Connection.parseUrl is not a function\nTypeError: Connection.parseUrl is not a function
    at Connection.tryInjectDefaultConnection (server/imports/core/connection/index.js:246:35)
```
https://github.com/nosqlclient/nosqlclient/blob/db883cc691e6213e1d0b732837c2ffe66ddf8d30/server/imports/core/connection/index.js#L246

I believe that removing "Connection." from the given line might fix an issue

**Comment by rsercano** [comment]
Thanks for sharing @unattended-user I'm on it.
