### ISSUE TITLE
Where is the repo with the strings?

### ISSUE THREAD

**Issue by dandv** [nosqlclient/nosqlclient#466]
I saw a typo on the welcome screen, and wanted to submit a PR. But where exactly are the string resources? [Searching this repo for "Auto complete is enabled by default"](https://github.com/nosqlclient/nosqlclient/search?q=Auto+complete+is+enabled+by+default&unscoped_q=Auto+complete+is+enabled+by+default) didn't find the correct file.

![image](https://user-images.githubusercontent.com/33569/50720461-68a51700-1062-11e9-8a3f-6f3b7a1ae4ab.png)

**Comment by rsercano** [comment]
Hello @dandv 

thanks for your contribution request, we've removed what's new popup on master branch completely it's a part of `2.2.0` tag. 

But feel free to contribute with anything else, we would be more than happy to accept :)
