### ISSUE TITLE
aggregate query doesn't work?

### ISSUE THREAD

**Issue by alienbat** [nosqlclient/nosqlclient#47]
Hi does aggregate query work? I try to put in the following aggregation JSON in but only get a syntax error.
![screen shot 2016-04-09 at 11 21 33 pm](https://cloud.githubusercontent.com/assets/1157265/14403815/d3c8fb5a-fea9-11e5-80ef-afe9e4b47cbe.png)

**Comment by rsercano** [comment]
Hello unfortunately currently only a full valid JSON is supported, therefore you need to wrap your `$match`, `$group`and all other words with double quotes, then it should work. As soon as possible I will change the query execution with a better way.

**Comment by tinkusam** [comment]
I will also appeal for this feature.

**Comment by rsercano** [comment]
Hello @tinkusam 

here's the related issue:  #125, currently you need to provide a valid JSON.

Cheers
