### ISSUE TITLE
How do you $unset fields?

### ISSUE THREAD

**Issue by dandv** [nosqlclient/nosqlclient#470]
I'm trying to unset a field, so I've changed the Query type to `updateMany`. The dialog changes to a `Select` field, and a `Set` field. After entering the `$unset` expression, I get this error when executing the query:

> Couldn't execute query: the dollar ($) prefixed field '$unset' in '$unset' is not valid for storage

![image](https://user-images.githubusercontent.com/33569/51183363-d2ed6100-1885-11e9-8ce2-e8a51f481eec.png)

How do I *$unset* field(s)? Per [the API docs](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#updateMany), the currently-named "Set" field should be called "update", and should take [update operators](https://docs.mongodb.com/manual/reference/operator/update/), including $set, but also $unset, $inc etc.

**Comment by rsercano** [comment]
Hello @dandv,

You're certainly right, and that's already implemented in the `master` branch, don't you use docker ? You can just pull the `latest` tag to get it. Probably we're going to release it soon and package with electron for desktop distributions but if you're already using docker please just use `latest` tag.  

![123](https://user-images.githubusercontent.com/3640368/51183998-47022600-18d3-11e9-97b5-c09b65cf2c26.png)


Let me know if that suits to you and I can close this one.

**Comment by hisuwh** [comment]
I've recently installed the desktop distribution of this and still doesn't seem to be implemented

**Comment by rsercano** [comment]
Hi @hisuwh unfortunately desktop distributions are not supported anymore, please try with docker's **latest** image.
