### ISSUE TITLE
Docker image: exec node not found

### ISSUE THREAD

**Issue by fauzie** [nosqlclient/nosqlclient#472]
# ./entrypoint.sh: line 25: exec: 'node': not found

Just pulled today, and running container.

## Expected Behavior
Running container normally without error from docker log.

## Current Behavior
Docker log shown:
```
[-] External MONGO_URL not found. Starting local MongoDB...
,
,=> Starting app on port 3000...
,./entrypoint.sh: line 25: exec: 'node': not found
```

## Possible Solution
none.

## Steps to Reproduce (for bugs)
1. Pull latest image
```
Digest: sha256:dc06a56e56cd9f11f6a5986a5e6eddca65bed9eeebc79cb68b5726bf884110fe
Status: Downloaded newer image for mongoclient/mongoclient:latest
```
2. Create container with ```mongoclient/mongoclient:latest``` image
3. Add volume from my mongoDB data to /data/db container
4. Set port mapping to 3000
5. Waiting container to run, and watching docker log

## Your Environment
* Nosqlclient version used: docker latest tag
* Environment name: Portainer v1.20.0
* Operating System and version: linux x86_64 Alpine Linux v3.8 Docker 18.03.1-ce (API: 1.37)

**Comment by rsercano** [comment]
Thanks @fauzie I'm checking that today.

**Comment by rsercano** [comment]
I just tried to reproduce this @fauzie but seems to be working to me. I've updated the meteor version just in case, and will push in a few minutes, in the meantime could you please ensure that `NODE` is installed properly during docker startup ?

Nosqlclient installs required dependencies one by one, the only logical explanation to this is; in your environment somehow docker failed to download `NODE`.
