### ISSUE TITLE
Checking for newer version of the nosqlclient

### ISSUE THREAD

**Issue by dolgikhLex** [nosqlclient/nosqlclient#474]
From your Quick Start guide:
> Nosqlclient checks newer versions each time you select a collection from left panel. It's main cause is forcing people to update the newest version all the time.

But if I don't have access to github I'll get an error in nosqlclient and functionality won't work during request. 

![screenshot from 2019-02-14 16-52-44](https://user-images.githubusercontent.com/17898524/52791518-2e279480-307a-11e9-9cbf-3e8b2df0e495.png)

**Solution**:
Give user a chance to disable auto checking for newer version of the nosqlclient.

**Comment by rsercano** [comment]
Good point @dolgikhLex, I'll get this done this weekend.
