### ISSUE TITLE
Make it possible to pre-load connection information from some json file

### ISSUE THREAD

**Issue by andrewnazarov** [nosqlclient/nosqlclient#475]
## Expected Behavior
I'm using nosqlclient to connect to different mongo instances. What I would find handy is the ability to define all my connection settings in a file, say, servers.json. Then I could mount this file to a nosqlclient container and have all the information about known connections and databases set. Also this helps to keep the information about connections persistent during restarts.

So, it's pretty much the same as dockerized pgadmin4 works.

## Current Behavior
I should create connections manually.

## Your Environment
* Nosqlclient version used: 2.2.0
* Environment name (e.g. chrome 39, portable, docker): docker
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12):

**Comment by rsercano** [comment]
An interesting another idea, thank you @andrewnazarov we'll integrate this too asap. Btw connections are persistent already if you give the corresponding volume to the docker. 

Also there's a way to define a **single** connection currently with an environment variable (`MONGOCLIENT_DEFAULT_CONNECTION_URL`) but I'll still implement this

**Comment by rsercano** [comment]
This has been implemented, you need to set a file path via `MONGOCLIENT_CONNECTIONS_FILE_PATH` environment variable. It should contain a json array with the below schema;
```
[
  {
    "name": "test",
    "url": "mongodb://mongodb0.prod.com:27017/admin"
  },
  {
    "name": "test2",
    "url": "mongodb://mongodb0.test.com:27017/admin"
  }
]
```

Within docker you only need to set a volume to container path for json file; `/opt/meteor/dist/predefined_connections.json`

**Caution**; This removes all connections which has been created previously if you set a correct connections json file.

Hopefully after 4.0.0 release I'll write those down to the official documentation.

**Comment by andrewnazarov** [comment]
Wow, that was fast, thank you).

Is this feature available in the latest Docker image?

**Comment by andrewnazarov** [comment]
Nevermind. I've consulted the latest Dockerfile and seen it's there.

**Comment by rsercano** [comment]
Great to hear it's useful to you ^^
