### ISSUE TITLE
Cannot save document with odd number of escaped quotes

### ISSUE THREAD

**Issue by RoMaNiAsHkA** [nosqlclient/nosqlclient#488]
Cannot save document with odd number of escaped quotes.
{
  "_id" : ObjectId("af4..."),
  "field" : "BLAH \\"BLAH\\" cannot \\"  BLAH"
}

If i delete one of this quotes, document will be saved.

Is it feature or bug?

**Comment by rsercano** [comment]
Hello @RoMaNiAsHkA actually quotes should be escaped, but I'm on it now, checking.

**Comment by rsercano** [comment]
Okay you need to escape inline double quotes @RoMaNiAsHkA  like this;

```
[
  {
    "field": "BLAH \"BLAH\" cannot \" BLAH"
  }
]
```
Otherwise it's not a valid JSON

**Comment by RoMaNiAsHkA** [comment]
This JSON 
[
  {
    "field": "BLAH \\"BLAH\\" cannot \\" BLAH"
  }
]

is valid by RFC 4627, RFC 7159, ECMA-404, see on https://jsonformatter.curiousconcept.com/

But in NoSQL client it is not valid, only if i delete one escaped quote

**Comment by rsercano** [comment]
In your first edit they weren't escaped. I see that you've changed it actually that's what I'm saying if you escape inline double quotes they're valid. Please tell me when do you encounter this issue ? Do you encounter it while saving a result set or in a query ? @RoMaNiAsHkA

**Comment by RoMaNiAsHkA** [comment]
Sorry, I didn't notice that github uses backslashes for escaping :)
I first encountered this a few weeks ago: I could not save the document when I clicked 'save' button.
Then i'v got red error popup with text like this: 'Syntax error, can not save document.Broken JSON near...and my document here'
My version of NoSQL Client 2.2.0 OpenSource edition

**Comment by rsercano** [comment]
Oh I see, actually that's fixed within #478 if you're using docker would you please update to the latest image ? We're planning to release 4.0.0 when we get more coverage with the [tests](https://github.com/nosqlclient/nosqlclient/issues/480)

**Comment by RoMaNiAsHkA** [comment]
Well, if the bug is already resolved in # 478, then I close this one? At the moment I don't have opportunity to upgrade container to the latest version :( I’m waiting for 4.0.0. Thanks for the quick reply!

**Comment by rsercano** [comment]
sorry for the inconvenience :/
