### ISSUE TITLE
Auth fails

### ISSUE THREAD

**Issue by shaniqwa** [nosqlclient/nosqlclient#49]
Hi, 
i'm trying to connect to my db and getting auth fails with all credentials ok (i'm using mViewer and its connecting ) what can i possibly do wrong here ?

thanks

**Comment by rsercano** [comment]
Hello,

could you please share what error do you exactly get ?
_p.s. If you are using as a web application you can share logs as well._

**Comment by rsercano** [comment]
Since the demo application works with authentication I can't get your problem's details. What rights do you have on your database ?

**Comment by shaniqwa** [comment]
sorry for the delay :) thats working  great now thank you
