### ISSUE TITLE
bug while saving number of scientific notation with v2.2.0 mac os x

### ISSUE THREAD

**Issue by Diamond0728** [nosqlclient/nosqlclient#494]
There is a big bug!!!
when there is a number field A, and it is 0.0000001, it will be 1e-7, that is ok. But if I change another field B ( never change A ), and I click "save", field A will be save as "1" instead of "1e-7," hope u can fix it, or if u had fixed it, please tell me which version it is. thank u!

## Expected Behavior
when there is a number field A, and it is 0.0000001, it will be 1e-7, that is ok. But if I change another field B ( never change A ), and I click "save", field A should be saved as "1e-7",

## Current Behavior
 Field A will be saved as "1" instead of "1e-7"

## Context
it affected me so much.... but its a business secret

## Your Environment
* version: 2.2.0
* client
* osx 10.12

**Comment by rsercano** [comment]
Please calm down, **we instantly try to fix** any bug we've encountered or learned. Sorry for any inconvenience we've gave to you, we're trying to improve coverage to prevent this kind of errors within #480  Would you please try this within `latest` docker image ? In the meantime I'll try to reproduce this

**Comment by rsercano** [comment]
Hello @Diamond0728 

I've fixed this by implementing JSON5 which is a better spec than the current one; https://spec.json5.org/
Also extended tests for #480 for this case.

Sorry for the inconvenience, you can pull `latest` docker image in approx. 15 minutes.
Thanks for reporting this.

**Comment by Diamond0728** [comment]
Thanks so much~
