### ISSUE TITLE
Unnecessary dependency on linux portable, libffmpeg

### ISSUE THREAD

**Issue by dandv** [nosqlclient/nosqlclient#495]
Just noticed libffmpeg.so in the 2.2.0 release for Linux. Why is that MPEG library necessary for a DB admin app?

**Comment by rsercano** [comment]
Hello @dandv 

I strongly recommend you to use [latest docker image](https://cloud.docker.com/repository/docker/mongoclient/mongoclient) there're [lots of fixes & features](https://github.com/nosqlclient/nosqlclient/milestone/12?closed=1) which are not yet released.

Apart from that, where did you see the **libffmepg** ?

**Comment by dandv** [comment]
I tried Docker, but the UI often spins forever:

![image](https://user-images.githubusercontent.com/33569/55739106-06a3d700-59ee-11e9-9dff-86fd16364591.png)

libffmpeg is in the [Linux x64 portable release](https://github.com/nosqlclient/nosqlclient/releases/download/2.2.0/linux-portable-x64.zip):

![image](https://user-images.githubusercontent.com/33569/55739158-1f13f180-59ee-11e9-89e2-681ec40b701d.png)

**Comment by rsercano** [comment]
`libffmpeg.so` should be related with some kind of electron scaffold, I'll keep this issue open to ensure it won't be in the 4.0.0. 

But docker should work tho, these console errors can be ignored, do you see any error on `docker logs` ?

**Comment by rsercano** [comment]
Just tested docker again and it seems to be working @dandv

**Comment by dandv** [comment]
I've been using Docker, and the buttons keep spinning forever most of the time, but not always.

Continuing discussion on #498.

**Comment by rsercano** [comment]
Portables are not being supported now, only docker builds.
