### ISSUE TITLE
Editing a connection loses its background color

### ISSUE THREAD

**Issue by dandv** [nosqlclient/nosqlclient#497]
## Steps to Reproduce (for bugs)
1. In the list of connections, right click a connection
2. Choose a different background color and click Save
3. Click the "edit"/pencil button of the connection, but don't change anything

The color of the connection will be lost.

Using the latest Docker image in Chrome 73.

**Comment by rsercano** [comment]
Hello @dandv,

it's actually intended, every selected row becomes gray, and clicking **edit/clone** or such action buttons would select the line so would make the color gray. 
If you click back to another connection in the grid you'll see that color is there. 

Issue is safe to close @dandv
