### ISSUE TITLE
Use URI for connection

### ISSUE THREAD

**Issue by mickaelgervais** [nosqlclient/nosqlclient#50]
Hi, 

Is it possible to use the MongoDB URI format to create connection?

Thanks.

Mickaël

**Comment by rsercano** [comment]
Hello,

unfortunately it's not possible right now but will add it to the 1.1.0, since it internally creates a connection url, this is no problem to implement. 

Sorry for the inconvenience for the version 1.0.0.

Regards,
Sercan

**Comment by thuantran** [comment]
Would appreciate this as well as it seems I can't use ssl secured mongodb at the moment, or is there some other way for this use case now?

**Comment by rsercano** [comment]
SSL wasn't supported in mongoclient 1.0.0 but will add connecting by a key in 1.1.0 as well.

Thanks for your interest and support

**Comment by vala84no** [comment]
Any idea how long before SSL support will be available? Mongoclient looks awesome, but I absolutely cannot use it until there's SSL support as all our mongo servers force SSL. Now that newer versions of Robomongo seem to have removed the SSL support (did they place it behind a paywall or something?) I'd love to switch to something else.

**Comment by rsercano** [comment]
Thanks for your opinions. this feature will be added at [release 1.1.0](https://github.com/rsercano/mongoclient/milestones/v1.1.0) which will take place at 1 May, if everything goes as planned.

**Comment by vala84no** [comment]
That's excellent. Thank you very much.
