### ISSUE TITLE
HTML in result causes save to fail

### ISSUE THREAD

**Issue by rsercano** [nosqlclient/nosqlclient#503]
This's a followup of #498

**Comment by nicohell** [comment]
Here it is : 
`<div ng-if=\"!fieldEditMode\" ng-controller=\"RTEFieldControllerasrteFieldCtrl\" class=\"ng-scope\">\n        <rubedo-custom-template template=\"<h2>Dépannageetaideàl'utilisation</h2>\n\n<h4 style=&quot;border:1px solid rgb(204,204,204);padding:5px 10px;background:rgb(238,238,238);&quot;>Adresse: </h4>\n\n<address style=&quot;border:1px solid rgb(204,204,204);padding:5px 10px;background:rgb(238,238,238);&quot;>7 rue de l'industrie<br/>\nCASTANETTOLOSAN<br/>\n31320<br/>\nFrance</address>\n\n<p></p>\n\n<divstyle=&quot;background:#eee;border:1pxsolid#ccc;padding:5px10px;&quot;><strong>E-mail:</strong><ahref=&quot;mailto:sav@icm-services.fr&quot;>sav@icm-services.fr</a><br/><strong>Téléphone:</strong>0562260306<br/><strong>Portable:</strong>0621606502</div>\n\n<p></p>\n\n<divstyle=&quot;background:#eee;border:1pxsolid#ccc;padding:5px10px;&quot;><strong>Horaires:</strong><br/>\nPartéléphone:dulundiauvendredi9hà18h<br/>\nEndehorsdeceshoraires,contactez-nousparemailselonlesconditionsdevotrecontrat.</div>\n\n<p></p>\n\n<divstyle=&quot;background:#eee;border:1pxsolid#ccc;padding:5px10px;&quot;>SiteInternet:<ahref=&quot;http://www.icm-services.fr/&quot;>http://www.icm-services.fr</a></div>\n\n<p></p>\n\" class=\"ng-scope\"><h2 class=\"ng-scope\">Dépannage et aide à l'utilisation</h2>\n\n<h4 style=\"border:1pxsolidrgb(204,204,204);padding:5px10px;background:rgb(238,238,238);\" class=\"ng-scope\">Adresse: </h4>\n\n<address style=\"border:1pxsolidrgb(204,204,204);padding:5px10px;background:rgb(238,238,238);\" class=\"ng-scope\">7 rue de l'industrie<br>\nCASTANET TOLOSAN<br>\n31320<br>\nFrance</address>\n\n<p class=\"ng-scope\"> </p>\n\n<div style=\"background:#eee;border:1pxsolid#ccc;padding:5px10px;\" class=\"ng-scope\"><strong>E-mail:</strong>     <a href=\"mailto:sav@icm-services.fr\">sav@icm-services.fr</a><br><strong>Téléphone:</strong>     05 62 26 03 06<br><strong>Portable:</strong> 06 21 60 65 02</div>\n\n<p class=\"ng-scope\"> </p>\n\n<div style=\"background:#eee;border:1pxsolid#ccc;padding:5px10px;\" class=\"ng-scope\"><strong>Horaires:</strong><br>\nPar téléphone : du lundi au vendredi 9h à 18h<br>\nEn dehors de ces horaires, contactez-nous par email selon les conditions de votre contrat.</div>\n\n<p class=\"ng-scope\"> </p>\n\n<div style=\"background:#eee;border:1pxsolid#ccc;padding:5px10px;\" class=\"ng-scope\">Site Internet :<a href=\"http://www.icm-services.fr/\">http://www.icm-services.fr</a></div>\n\n<p class=\"ng-scope\"> </p></rubedo-custom-template>\n    </div>`

**Comment by rsercano** [comment]
Thanks @nicohell I've found the issue, below regex shouldn't match with the given result, but it does. Will fix this accordingly.

```
:\/.*?([^\\]\/.*?(,|}|]))+
```

**Comment by rsercano** [comment]
Hello @nicohell sorry for the inconvenience, a fix is on the way !! ~15 mins for automated docker build.
