### ISSUE TITLE
Unabe to run web version.

### ISSUE THREAD

**Issue by Betalos** [nosqlclient/nosqlclient#504]
well when i try to run the master branch with metor of event after building with this cmd:
`cmd /c "set ROOT_URL=http://127.0.0.1:3000 && set MONGO_URL=mongodb://192.168.1.222:27017/local && node main.js"``

I get this error:
`{"error":{"driver":true,"name":"MongoError"},"level":"error","message":"uncaughtException: database names cannot contain the character ' '\nMongoError: database names cannot contain the character ' '\n    at Function.create (C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server\\npm\\node_modules\\meteor\\npm-mongo\\node_modules\\mongodb-core\\lib\\error.js:43:12)\n    at validateDatabaseName (C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server\\npm\\node_modules\\meteor\\npm-mongo\\node_modules\\mongodb\\lib\\operations\\db_ops.js:728:24)\n    at new Db (C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server\\npm\\node_modules\\meteor\\npm-mongo\\node_modules\\mongodb\\lib\\db.js:181:3)\n    at MongoClient.db (C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server\\npm\\node_modules\\meteor\\npm-mongo\\node_modules\\mongodb\\lib\\mongo_client.js:268:14)\n    at packages/mongo/mongo_driver.js:186:25\n    at runWithEnvironment (packages\\meteor.js:1286:24)","stack":"MongoError: database names cannot contain the character ' '\n    at Function.create (C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server\\npm\\node_modules\\meteor\\npm-mongo\\node_modules\\mongodb-core\\lib\\error.js:43:12)\n    at validateDatabaseName (C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server\\npm\\node_modules\\meteor\\npm-mongo\\node_modules\\mongodb\\lib\\operations\\db_ops.js:728:24)\n    at new Db (C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server\\npm\\node_modules\\meteor\\npm-mongo\\node_modules\\mongodb\\lib\\db.js:181:3)\n    at MongoClient.db (C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server\\npm\\node_modules\\meteor\\npm-mongo\\node_modules\\mongodb\\lib\\mongo_client.js:268:14)\n    at packages/mongo/mongo_driver.js:186:25\n    at runWithEnvironment (packages\\meteor.js:1286:24)","exception":true,"date":"Mon May 06 2019 18:36:18 GMT+0000 (Maroc)","process":{"pid":2308,"uid":null,"gid":null,"cwd":"C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v8.11.3","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\main.js","program.json"],"memoryUsage":{"rss":97652736,"heapTotal":75235328,"heapUsed":48852264,"external":22708983}},"os":{"loadavg":[0,0,0],"uptime":36151.6750023},"trace":[{"column":12,"file":"C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server\\npm\\node_modules\\meteor\\npm-mongo\\node_modules\\mongodb-core\\lib\\error.js","function":"Function.create","line":43,"method":"create","native":false},{"column":24,"file":"C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server\\npm\\node_modules\\meteor\\npm-mongo\\node_modules\\mongodb\\lib\\operations\\db_ops.js","function":"validateDatabaseName","line":728,"method":null,"native":false},{"column":3,"file":"C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server\\npm\\node_modules\\meteor\\npm-mongo\\node_modules\\mongodb\\lib\\db.js","function":"new Db","line":181,"method":null,"native":false},{"column":14,"file":"C:\\Users\\thour\\Documents\\web-projects\\client-bundle\\programs\\server\\npm\\node_modules\\meteor\\npm-mongo\\node_modules\\mongodb\\lib\\mongo_client.js","function":"MongoClient.db","line":268,"method":"db","native":false},{"column":25,"file":"packages/mongo/mongo_driver.js","function":null,"line":186,"method":null,"native":false},{"column":24,"file":"packages\\meteor.js","function":"runWithEnvironment","line":1286,"method":null,"native":false}]}`

**Comment by rsercano** [comment]
Hello @Betalos 

first of all if you're not thinking of a new feature or bugfix PR you don't have to build it. You can use docker pull and master branch would be ready to use. Otherwise would you please send me what command did you execute to build ?

The command you've executed is not a build command as far as I understood.

**Comment by Betalos** [comment]
Hello @rsercano. 
well I used the standard meteor build cmd: 
`meteor build path/to/master`

I'm also facing this issue using `meteor` cmd.

**Comment by rsercano** [comment]
Did you execute `meteor npm install` first ?

**Comment by Betalos** [comment]
Yes i followed all the steps. But i'm ending with the same error

**Comment by rsercano** [comment]
I suspect that the error is related with windows encoding, would you please try to encapsulate your `MONGO_URL` value with quotes ?

The exact command works perfectly fine within unix.

**Comment by Betalos** [comment]
Weah i confirm it's working (try it on linux). I will try to build it for windows and see if it would work.
Thank you for your quik reply.
