### ISSUE TITLE
Connect to client with DNS SRV record hostname

### ISSUE THREAD

**Issue by raugaral** [nosqlclient/nosqlclient#505]
I received the following URL from a client: 
`mongodb+srv://username:password@company-bdoii.mongodb.net/databasename?retryWrites=true`

When I tried to connect using that url it doesn't works. 

I have looked at the mongo documentation what srv means.

> In order to leverage the DNS seedlist, use a connection string prefix of mongodb+srv: rather than the standard mongodb:. The +srv indicates to the client that the hostname that follows corresponds to a DNS SRV record. 

https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format

## Expected Behavior

Paste the connection url on his text field and than the aplication take  all parameters correctly and allow to connect with this server.

## Current Behavior

When the connection url is pasted, the application take `mongodb+srv` as authentication username.
As usual, it can not connect.

But if I correct the authentication parameters, don't connect anyway. 

I thing the aplication don't allow connection with SRV url.

## Possible Solution

The SRV connection url are allowed by Mongodb since version 3.6. May be the dependences are obsolete... 

## Your Environment

* Nosqlclient version used: Version 2.2.0
* Environment name (e.g. chrome 39, portable, docker): Portable
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): osx 10.14.4

**Comment by rsercano** [comment]
Hello @raugaral 

I'll check that asap, in the meantime would you please retry without DNS resolution ? Apart from that, MongoDB says;

> The mongodb+srv option will fail if there is no available DNS with records that correspond to the hostname identified in the connection string. In addition, use of the +srv connection string modifier automatically sets the ssl option to true for the connection. You can override this behavior by explicitly setting the ssl option to false with ssl=false in the query string.

**Comment by rsercano** [comment]
Btw. I think the real issue in here is parsing URL wrong by putting **mongodb:srv** into username field. Otherwise it seems okay to me after you've corrected it, it should connect if you have the correct DNS records.

**Comment by rsercano** [comment]
Changed URL parser to `mongodb-url` and seems to be working now, thanks for reporting this @raugaral and sorry for the inconvenience. 

While connecting the DNS error you've encountered is related with your configuration.
