### ISSUE TITLE
Remove field only in GUI not in Mongo

### ISSUE THREAD

**Issue by nicohell** [nosqlclient/nosqlclient#508]
## Expected Behavior
Selecting option "remove" on a field should remove the field from mongo;

## Current Behavior
Selecting option "remove" on a field, remove the field in GUI but not in mongo; After removing, collection refresh displays field again.

## Steps to Reproduce (for bugs)
Here is screen GIF 
![nosqlclient_remove](https://user-images.githubusercontent.com/7948533/59187213-3a79b500-8b75-11e9-88e5-6e3612d1fa1e.gif)

## Your Environment
* Nosqlclient version used: 2.2.0
* Environment name (e.g. chrome 39, portable, docker): Opera 60.0.3255.70
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): CentOS Linux release 7.6.1810 (Core)
* MongoDB server version: 4.0.9

**Comment by rsercano** [comment]
Hello @nicohell thanks for the detailed explanation, are you using `latest` docker image ?

**Comment by rsercano** [comment]
Nice catch @nicohell, but fyi. now the updated document will be written into database with `replaceOne` command.

**Comment by nicohell** [comment]
Looks like working fine now, thanks @rsercano for your reactivity
