### ISSUE TITLE
Backup tools don't work in latest docker image

### ISSUE THREAD

**Issue by dshoot** [nosqlclient/nosqlclient#510]
## Expected Behavior

Mongorestore must work i.e. must accept host and dir parameters

## Current Behavior

Currently "args" parameter which is sent via web socket is always empty, despite that corresponding fields are filled in.
That leads always to the following logs if one tries to restore mongo dump:

2019-06-13T15:34:50.003+0000	using default 'dump' directory
2019-06-13T15:34:50.004+0000	see mongorestore --help for usage information
2019-06-13T15:34:50.004+0000	Failed: mongorestore target 'dump' invalid: stat dump: no such file or directory

It basically means that no arguments were passed to mongorestore utility.

## Steps to Reproduce (for bugs)

1. connect to any mongo server
2. go to Management -> Backupt Tools
3. Enter valid backup folder and mongo host
4. Press execute button

## Your Environment

* Nosqlclient version used: latest docker image
* Environment name (e.g. chrome 39, portable, docker): docker
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): ubuntu 16.04

**Comment by rsercano** [comment]
In fact I've realized it too @dshoot thanks for reporting, I'll take care of it asap.
