### ISSUE TITLE
Test against nodejs 12

### ISSUE THREAD

**Issue by Betalos** [nosqlclient/nosqlclient#512]
## Expected Behavior
Being able to build agains node 12.

## Current Behavior
The issue is that when i build i get an issue with fibers (3.1.1 not suported by node 12), i got around it by forcing the server the 4.0.1 version.
But when I run the main.js i get an exception that stops the process.

## Steps to Reproduce (for bugs)

1. (build using) meteor build path/to/archive
2. cd path/to/archive/programs/server
3. npm i fibers@4.0.1 --save // to force latest fibers as a hack
[stack.txt](https://github.com/nosqlclient/nosqlclient/files/3297657/stack.txt)

## Your Environment
* latest
* Debian 9

**Comment by rsercano** [comment]
Hello @Betalos 

I believe this's related with the meteor version we're using currently. Fibers is an internal dependency in meteorjs. 

I'll check that

**Comment by Betalos** [comment]
Hi @rsercano, thanks again on the quik reply.
That what I tought also, but the stack shows also an error in mongo's bson library (check the atached stack file)

**Comment by rsercano** [comment]
Alright, thanks for the detailed explanation, I will check it

**Comment by Betalos** [comment]
Hi @rsercano.
Well after a bit of digging I found out that meteor@1.9 is the version that supports node@12.
Thread in meteor repos: https://github.com/meteor/meteor/pull/10527

**Comment by rsercano** [comment]
Oh I see, @Betalos I guess this's not publicly released yet, also every minor release is a big step for meteor unfortunately... As soon as they release it publicly I'll upgrade nosqlclient.

**Comment by Betalos** [comment]
Hi @rsercano. Well i got mongoclient to work with node 12 by updating meteor to 1.9-alpha.6 using the cmd:  `meteor update --release 1.9-alpha.6`, and also updating bson lib to 4.0.2 and after that the run of the project succeded with no notable issues (not in dept testing).

**Comment by rsercano** [comment]
@Betalos thanks for letting me know, I rather to wait their stable release tho

**Comment by Betalos** [comment]
@rsercano, I would like to annonce that meteor@1.9 is released officially.

**Comment by rsercano** [comment]
Thanks mate, I'll hopefully give a few days to nosqlclient to get over current issues and I'll upgrade it @Betalos

**Comment by rsercano** [comment]
Meteor version has been updated to 1.10.2
