### ISSUE TITLE
Where is the checksum for releases

### ISSUE THREAD

**Issue by valamorgon** [nosqlclient/nosqlclient#518]
For security concerns I'd like to compare sha256sum, where is it for the releases? If not exists can you please add it?

**Comment by rsercano** [comment]
Hello @valamorgon this makes sense for distributions, but nosqlclient is mostly being used on docker and for that reason I didn't even try to release 4.0.0 for so long. I suggest you to use docker with `latest` tag, so you can use latest features. 

But that's actually a nice suggestion and I'll keep this open.

**Comment by rsercano** [comment]
Closing as only docker builds are supported now.
