### ISSUE TITLE
Cannot use shell when connecting to mongo:latest

### ISSUE THREAD

**Issue by stephanGarland** [nosqlclient/nosqlclient#521]
## Expected Behavior
Shell in nosqlclient should connect and function

## Current Behavior
Shell does not connect, container loop restarts.

## Possible Solution
Upgrade bundled mongo.

## Steps to Reproduce (for bugs)
1. docker pull mongo && docker pull mongoclient/mongoclient
2. Set up and run containers to connect.
3. Attempt to run shell in nosqlclient

## Context
Cannot use official mongo server image.

## Your Environment
Debian Buster, docker, latest versions of mongo and mongoclient, latest Chrome on Mac and PC.

**Comment by rsercano** [comment]
fixed by #520

**Comment by garyx** [comment]
Yes I can use the same credentials/parameter and host settings in an older version and that works fine. 

This doesn't seem to be the same issue with #520 
In my case I can start up the docker image, I am not pulling a separate mongodb image. I am just running the mognoclient/mongoclient image in docker and hosting the db folder in a local folder.
