### ISSUE TITLE
Latest: Docker image error getaddrinfo ENOTFOUND cannot connect to server

### ISSUE THREAD

**Issue by garyx** [nosqlclient/nosqlclient#522]
I set up the connection identically from an old app setup I have of the client. 

## Current Behavior
I'm getting an error with the latest docker image created two days ago. (Image ID 7ede6e936207) 

`[1007] getaddrinfo ENOTFOUND server-host-01.domain server-host-01.domain:27018
`

## Steps to Reproduce (for bugs)
Simply try connecting to any servers using x509 in my case. Don't have an instance of mongod running with any other auth setup to test. 

## Your Environment
The client/app says it's version 2.2.0 but it has been doing that for such a long time, only indication of what version I am using can be found in the image id above.

**Comment by rsercano** [comment]
Yes you're right we haven't released 4.0.0 for a very long time due to lack of any type of resources... 

This can be related with #521, I'll check it in detail, in the meantime could you please tell me were you be able to connect with same conditions before that image ?

**Comment by kulheim** [comment]
Could your container resolve server-host-01.domain ?
docker exec -ti nosqlclient ping server-host-01.domain

**Comment by rsercano** [comment]
Hello @kulheim that's up to your docker network actually not related with nosqlclient as far as I know

**Comment by kulheim** [comment]
It could be related. In replica set mongoclient connects to a server defined in connect string, but then uses addresses of other members from obtained replica set config.
I had the same problem "[1007] getaddrinfo ENOTFOUND server-host-01.domain".

**Comment by rsercano** [comment]
Please feel free to reopen if the issue persists.
