### ISSUE TITLE
Docker environment variable not automatically creating connection

### ISSUE THREAD

**Issue by progowl** [nosqlclient/nosqlclient#524]
The environment variable does not automatically create a connection to MongoDB

## Expected Behavior
Using the environment variable is supposed to create a connection to the MongoDB described by the URL, and this also prevents the creation of a default MongoDB required for meteor to work.

## Current Behavior
The client does not create a default MongoDB for meteor, it appears to recognize the database described by the URL as valid, and it does not create a connection to the database provided with the URL. This connection has to be set up manually.

## Steps to Reproduce (for bugs)

1. Use the YAML provided below within a Kubernetes Cluster, adjusting the URL for your environment.
2. Use a docker command supplying the URL as an Environment variable.
## Context
It is possible to connect to the MongoDB manually, but I am trying to set up an environment with as little manual work as possible. If I need to recreate the environment I just want to be able to apply the YAML files to the Kubernetes cluster and have those handle all of the work.
## Your Environment
- Nosqlclient version used: Latest Docker Version
- Running on an Kubernetes Cluster deployed on AWS.
- Below is the deployment YAML file I am currently using for Nosql Client. I wonder if the issue could be in my URL, but the same URL can be used for manually creating the connection with no issues (apologies I could not get the code to format properly).

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-deployment
  labels:
    app: mongo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-client
  template:
    metadata:
      labels:
        app: mongo-client
    spec:
      containers:
      - name: mongo-client
        image: mongoclient/mongoclient
        ports:
        - containerPort: 3000
        env:
        - name: "MONGO_URL"
          value: mongodb://100.69.142.61:27017/admin

**Comment by rsercano** [comment]
Thanks @ProgOwl I was suspecting something about that, I'll check it when I get some spare time.

**Comment by rsercano** [comment]
Can you confirm it's still not working ? @ProgOwl

**Comment by rsercano** [comment]
Should be fixed within current release.
