### ISSUE TITLE
Prevent the users from saving credentials

### ISSUE THREAD

**Issue by MarkusKepert** [nosqlclient/nosqlclient#525]
A settings flag that can be enabled and that prevents the user from saving the SHA credentials in Database connection dialog. The current possibility is fine, but when running nosqlclient as docker image, a user can save all connection properties (include username & password). That is not very helpful and my preference would be to prevent saving the credentials. Maybe this behaviour can be enabled by a environmental switch.

## Expected Behavior
Connection dialog is available and usable, but the security tab prevents the user of entering username and password. This behaviour should not be the default, but can be enabled by settings or environment switch.

## Current Behavior
User can save complete connection with authentication in connection dialog. This is available for all users. So, also non-admin users are able to connect as admin, when someone accidentially save the admin/root credentials.

## Context
Running nosqlclient as (semi) public docker image.

## Your Environment
Kubernetes, but doesn't care i think.

**Comment by rsercano** [comment]
Hello @MarkusNeviadomski this seems like a valid thought, but currently if you leave credentials empty nosqlclient is asking you about credentials if you try to connect, isn't it sufficient ?

**Comment by MarkusKepert** [comment]
Hello @rsercano 
for my first thought it was also OK. But if you  have a larger team and can not ensure that everyone follows the working guidelines, i prefer to actively disable the input elements for username and password. "Save credentials" is a so common action for most people, but normally this is stored on the local machine. But here it can have very huge impact if someone does it accidentially.

**Comment by rsercano** [comment]
Hopefully in a spare time I'll take care of it, thanks.

**Comment by cromatikap** [comment]
I think I'm looking for the same solution than @MarkusNeviadomski, although I don't understand where the credentials are stored. I'm trying the Docker image and it seems to be on the client side but I don't see anything relevant with the dev tools. 
Could you be more precise about how the db credentials are handled?

**Comment by rsercano** [comment]
Hello @bidetaggle it's actually well described in the documentation as far as I remember, they're all being saved to MongoDB, so nosqlclient has it's own database behind the scenes

**Comment by cromatikap** [comment]
I have Default (preconfigured) 127.0.0.1:27017, no credential needed to connect. As I see this one is used by nosqlclient. If I create a connection to a remote database, the credentials will be stored on the localhost mongo?

It seems that there is no authentication method on the client side. 
Therefore I thought about using a [http basic access auth](https://en.wikipedia.org/wiki/Basic_access_authentication) to access nosqlclient, is it a viable idea?

**Comment by rsercano** [comment]
Actually there's such an option in the nosqlclient;

export MONGOCLIENT_AUTH=true
export MONGOCLIENT_USERNAME=****
export MONGOCLIENT_PASSWORD=*********

use the above environment values to enable basic auth.

**Comment by cromatikap** [comment]
Ah ok, I see it in the doc.
Then, a solution for @MarkusNeviadomski to have a multi-user access would be at the http server level with 1 running container of nosqlclient + 1 dedicated mongodb per user. 
Nothing is kept by the browser except the session cookie.
Do I picture it well?

**Comment by rsercano** [comment]
Exactly, in fact there's no session on mongoclient (I mean in the meaning of you described), it's a single page application and one refresh loses the connection. So I strongly encourage to use disconnect button instead of refreshin to end connection pools.

**Comment by MarkusKepert** [comment]
Thanks! @rsercano  Those env parameter will help me a lot to improve my setup! Thanks! From my point, we can close the issue as resolved!

**Comment by rsercano** [comment]
Thanks a lot after a while it's satisfying to close an issue :D
