### ISSUE TITLE
Space management

### ISSUE THREAD

**Issue by nicohell** [nosqlclient/nosqlclient#526]
Trying to add space in text field returns message "Nothing to save..." 

## Expected Behavior

Save record with new text including space 

## Current Behavior

We discover once that some spaces were missing (probably after NoSQLclient modifications) 

## Your Environment

* Nosqlclient version used: 2.2.0
* Environment name : systemd installation
* Operating System and version :  up to date Centos 7 (Kernel 5.1.10-1.el7.elrepo.x86_64)

![nosqlclient](https://user-images.githubusercontent.com/7948533/65152408-28d36380-da28-11e9-84f2-e7ae7b4f8557.gif)

**Comment by rsercano** [comment]
Thanks for the detailed explanation, from version 4.0.0 I'm planning to give up on desktop distributions. Would you please try this with the `latest` docker image?

**Comment by nicohell** [comment]
Installed docker mongoclient/mongoclient:latest today and issue sill occuring. 

Further more, spaces are removed on all string fields (nested too) when we make modifications.

In the video attached the confirm prompt window says that 2 document will be updated even though we modify only one. 

All these issues occur in docker and with systemd installation. 

![nosqlclient](https://user-images.githubusercontent.com/7948533/65513965-a42b8e00-dedc-11e9-9ee9-46a109a6bc2e.gif)
.

**Comment by rsercano** [comment]
Alirhgt, let me check it @nicohell in the meantime would you please send me a data example ?

**Comment by nicohell** [comment]
[data_sample.txt](https://github.com/nosqlclient/nosqlclient/files/3648081/data_sample.txt)

**Comment by rsercano** [comment]
Fixed, please wait a few moments for the new docker image build, then it should be fixed, sorry for inconvenience.

**Comment by nicohell** [comment]
Updated docker and everything lokks fine. 

Thanks a lot Sercan !
