### ISSUE TITLE
Bug: Trying to find data

### ISSUE THREAD

**Issue by joernfechner** [nosqlclient/nosqlclient#527]
## Expected Behavior

I created this example with just a single JSON in it to show the issue. 
When I have configured the query as shown below I would like to receive data.
![grafik](https://user-images.githubusercontent.com/44359859/68480959-4b1e7c00-0236-11ea-9d14-e47a7c97322b.png)

## Current Behavior

If the received data is less than the given limit in the query the calculation of maximum allowed size(3MB) has a bug. It seems like the size gets multiplicated with the limit. and I receive following error.
![grafik](https://user-images.githubusercontent.com/44359859/68481545-cf253380-0237-11ea-8108-0d2d7ad9b08c.png)

## Possible Solution

Debug the calculation

## Steps to Reproduce (for bugs)

1. Use a Querey where the limit is higher as the result will be
2. The size of the dataset, that should be returned, has the be more than 3 MB when it gets multiplicated with the limit.
3. Receive Error

## Context

I wanted to receive a data-set of max 50. The result was less than 3MB but I got the Error. 

## Your Environment

* Nosqlclient version used: mongoclient/mongoclient:2.2.0 from dockerHub
* Environment name (e.g. chrome 39, portable, docker): docker
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): Windows 10

## Further Question
Can I increase the maximum allowed size to receive data bigger than 3 MB?

**Comment by rsercano** [comment]
Hello @joernfechner thanks for submitting this, did you check settings? There's a setting there which makes it available to make max allowed size infinitive 😉

Or you can increase of course.

**Comment by joernfechner** [comment]
Thank you for the quick response! I found it in the settings now, thank you 👍 
For my case this will do the job. Your decision if you want to fix it anyway. 

Have a nice weekend!
