### ISSUE TITLE
Website: Github, try demo & Learn more buttons disappear on wide screens

### ISSUE THREAD

**Issue by ajmas** [nosqlclient/nosqlclient#528]
There is an issue with the website whereby if the window is wider than a certain number of pixels the buttons for github and learn more get chopped. I have attached two screen shots that illustrate the issue.

Tried  with both Safari and Chrome on macOS 10.5.

wide window in chrome:
![Screenshot 2019-11-08 at 13 12 43](https://user-images.githubusercontent.com/682269/68500384-9b431180-0229-11ea-92de-6ca83b0562d7.png)

narrow window in chrome:
![Screenshot 2019-11-08 at 13 12 52](https://user-images.githubusercontent.com/682269/68500385-9bdba800-0229-11ea-8fad-95c3fe6af148.png)

**Comment by rsercano** [comment]
Thanks for reporting ☺️

**Comment by rsercano** [comment]
fixed
