### ISSUE TITLE
IS it possible to use this client for a remote mongodb that I need to ssh into ?

### ISSUE THREAD

**Issue by waiholiu** [nosqlclient/nosqlclient#53]

**Comment by rsercano** [comment]
Hello,

you need to connect via SSH first then have to open a tunnel for the mongodb port and you are good to go. You can have a look at [here](http://serverfault.com/questions/597765/how-to-connect-to-mongodb-server-via-ssh-tunnel)

Additionally if your host (where you connect via SSH) open the corresponding port for the mongodb, again you are good to go.

**Comment by waiholiu** [comment]
Hi,

I'm aware of that I would need to create an SSH tunnel but I'm wondering if it is possible to do it inside your app? In Robomongo, there is actually an SSH tab when I'm creating a connection.

**Comment by rsercano** [comment]
Oh, not yet but can do in a further release unfortunately its impossible to make it happen in upcoming release. Maybe in the next one I can plan it.

**Comment by kaue** [comment]
+1 for SSH connection feature
