### ISSUE TITLE
Can't select and copy filed value by double click in query results

### ISSUE THREAD

**Issue by wxb2dyj** [nosqlclient/nosqlclient#530]
## Expected Behavior
After excute a query, I want  to copy a field value.

## Current Behavior
After I double-click filed content I can't select and copy it.

## Possible Solution
Change editor mode to "Code" can solve this problem, but that's too odd.

## Steps to Reproduce (for bugs)
1.connect and choose a list and excute default query;
2.click a document below with editor mode "Tree", you can copy filed's content by double click;
3.change editor mode from "Tree" to any other mode(except "Code")
4.you can not copy filed's content by double click, even change it back to "Tree" mode

## Context
I want to just select and copy filed value with long string with double click like other in web pages.

## Your Environment
* Nosqlclient version used: mongoclient/mongoclient:2.2.0 from dockerHub:
* Environment name (e.g. chrome 39, portable, docker):docker, chrome version 71.0.3578.98
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12):Ubuntu 16.04.3

**Comment by rsercano** [comment]
Alright @wxb2dyj, I'll check that would you please try this with `latest` tag ?

**Comment by wxb2dyj** [comment]
@rsercano thanks, I'll try.

**Comment by rsercano** [comment]
Couldn't reproduce on latest.
