### ISSUE TITLE
Does nosqlclient supports connection to Mongodb Atlas?

### ISSUE THREAD

**Issue by gicat** [nosqlclient/nosqlclient#531]
## Expected Behavior

Connection to MongoDb
## Current Behavior

Connections fails with message 'Authentication failed'
## Steps to Reproduce (for bugs)

1. Create connection using url provided by Atlas
2.Connect
3.Authentication failed
4.

## Your Environment

* Nosqlclient version used: Open Source Edition - Version 2.2.0
* Environment name (e.g. chrome 39, portable, docker): docker
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): 

Here is the log from the container:

{"connectionUrl":"mongodb+srv://xxxx:yyyy@cluster0-xyz.azure.mongodb.net/?retryWrites=true&replicaSet=Cluster0-shard-0","options":{"useNewUrlParser":true,"authSource":"test"},"sessionId":"2Lx7spbnpKTt65WR5","level":"debug","message":"[connect]"}
{"externalError":"Authentication failed.","sessionId":"2Lx7spbnpKTt65WR5","connectionOptions":{"useNewUrlParser":true,"authSource":"test"},"level":"error","message":"[connection-error]"}

**Comment by gicat** [comment]
I have successfully authenticated, instead of using the url provided by Atlas I configured each authentication step by hand. Then after authenticating the application does not work, there are multiple errors on log. I suspect that Atlas is not supported.

**Comment by rsercano** [comment]
Actually we support any type of MongoDB connections, I'm glad you figured it out.
