### ISSUE TITLE
docker image misses libcrypto.so.1.1

### ISSUE THREAD

**Issue by drummer3333** [nosqlclient/nosqlclient#535]
when starting the current latest image with local mongoDB it can't start mongo. 
Error is 
`mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`
and subsequently nosqlclient can't start because auf the missing DB conection.

## Possible Solution
update openssl in image

## Steps to Reproduce (for bugs)
1. run `docker run mongoclient/mongoclient`

## Your Environment

* Nosqlclient version used: latest docker image
* Environment name (e.g. chrome 39, portable, docker): docker
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): Ubuntu and windows 10

**Comment by rsercano** [comment]
I was expecting such an issue @drummer3333 thanks for reporting this I'll fix asap.

**Comment by rsercano** [comment]
Committed already, hopefully it fixes.

**Comment by rsercano** [comment]
It should be fixed, could you please re-pull ? @drummer3333

**Comment by drummer3333** [comment]
yes, all running again.
