### ISSUE TITLE
Docker container stops on run command

### ISSUE THREAD

**Issue by prashanth-sams** [nosqlclient/nosqlclient#537]
## Current Behavior
When I run the below cli command in terminal, it stops the docker container immediately and the status goes `exited`
```
docker run -d -p 7000:3000 -v /data/db:/data/db mongoclient/mongoclient
```
## Your Environment
* Nosqlclient version used: mongoclient/mongoclient:2.2.0
* Environment name: docker
* Operating System: OSX 10.14

**Comment by rsercano** [comment]
Hello mate you're trying to create a volume on /data/db, is there such folder? If so docker should have write permissions on it

**Comment by rsercano** [comment]
Also please use **latest** tag
