### ISSUE TITLE
New version release (including docker tags)

### ISSUE THREAD

**Issue by rohit-gohri** [nosqlclient/nosqlclient#540]
## Expected Behavior

The last release is 2.2.0 which is 3 years old almost. And almost 350 commits before. I would like to pin the docker image to a fixed version to get consistent behaviour on different installs on different systems.

## Current Behavior

Currently all new releases point to `latest` tag on docker so there is no tag to install a specific release.

## Possible Solution

Just release a new version and a new tag for the docker image.

## Context

I installed the 2.2 release thinking that was the last stable version and then couldn't figure out why aggregations were not working.

## Your Environment

* Nosqlclient version used: 2.2
* Environment name (e.g. chrome 39, portable, docker): docker
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): centos 7

**Comment by rsercano** [comment]
Good point! :)

**Comment by rsercano** [comment]
I was actually planning to do nowadays lets do this.

**Comment by rsercano** [comment]
Docker will be automatically built and tagged.

**Comment by rohit-gohri** [comment]
Great! Thanks

**Comment by rsercano** [comment]
Seems like there's a small issue on builds I'll fix it today or tomorrow
