### ISSUE TITLE
Add global credentials

### ISSUE THREAD

**Issue by erosval** [nosqlclient/nosqlclient#548]
It would be useful to have general credentials for the application so that no one can access or see the configured connections.

## Expected Behavior
On the home page, users must add their credentials before viewing saved connections

## Current Behavior
No credentials are required to access the application

## Possible Solution
On the home page, add the prompt for credentials before viewing saved connections

## Steps to Reproduce (for bugs)
N.A.

**Comment by erosval** [comment]
I found the answer by myself by looking at these links:
- https://www.nosqlclient.com/docs/start.html#compile
- https://github.com/nosqlclient/nosqlclient/issues/398

**Comment by rsercano** [comment]
Hello @erosval glad you solved your problem, let me know if you need anything else.
