### ISSUE TITLE
TTL indexes are created with "expireAfterSeconds" as String not Int

### ISSUE THREAD

**Issue by alexandre-slp** [nosqlclient/nosqlclient#549]
When I create an index with TTL through the web interface and inspect it, the parameter "expireAfterSeconds" 
has its value as String no Int. This causes that docs that should be deleted are not. 

## Expected Behavior
Use the web interface to create an Index with TTL and inspect it, the "expireAfterSeconds" should be an Int.

You should see something like this:
```
{
   "v": 2,
   "key": {
      "date": 1
   },
   "name": "date",
   "ns": "db.test",
   "expireAfterSeconds": 10 <---
}
```

## Current Behavior
Use the web interface to create an Index with TTL and inspect it, the "expireAfterSeconds" and its a String.

You will see something like this:
```
{
   "v": 2,
   "key": {
      "date": 1
   },
   "name": "date",
   "ns": "db.test",
   "expireAfterSeconds": "10" <---
}
```

## Steps to Reproduce
1. Go to UI path to create the index: Management > Index Management
2. Click "add Index"
3. In "General", fill in the parameters: "index name", "field name" and "time to live"
5. Click "save"
6. To inspect the index just click on the "leaf" (Show Raw Json)

## Context
Docs that should be deleted after the TTL are not.

## Your Environment
* Nosqlclient version used: 2.2.0
* Environment name: Docker

**Comment by alexandre-slp** [comment]
If you create the index through "Collections" and select "createIndex", the index is created correctly.

**Comment by rsercano** [comment]
Thanks for reporting this @alexandre-slp I don't know how such a bug couldn't be found earlier. Also interestingly MongoDB nodejs driver accepts it as a string somehow 🤔 

Fixed, as soon as build finished I'll also prepare the hotfix release.
