### ISSUE TITLE
How use selector filter return field?

### ISSUE THREAD

**Issue by yale8848** [nosqlclient/nosqlclient#553]
How to use nosqlclient to achieve `find({},{b:0})` in selector?

**Comment by rsercano** [comment]
Hi @yale8848 this's called projection in MongoDB and in nosqlclient there're options below selector you can see projection there.
https://docs.mongodb.com/manual/reference/operator/projection/positional/

https://www.nosqlclient.com/docs/user_manual.html
![image](https://user-images.githubusercontent.com/3640368/102317072-052efe00-3f88-11eb-823e-d4c2cb9dca42.png)
