### ISSUE TITLE
how can i listen :: by set env

### ISSUE THREAD

**Issue by mengkaibulusili** [nosqlclient/nosqlclient#556]
i can use express listen ip6 like this:
docker run -d --net=mynet --ip=172.30.10.11  -e VCAP_APP_HOST="::" -e ME_CONFIG_MONGODB_SERVER="172.30.10.10" -p 8081:8081 mongo-express

 -e VCAP_APP_HOST="::" 

how can i use mongoclient like this

**Comment by rsercano** [comment]
Hi @mengkaibulusili I'm really confused, what **VCAP_APP_HOST** is doing actually?

**Comment by mengkaibulusili** [comment]
in other mongo-express , it listen ip4 default. you can set VCAP_APP_HOST="::" to enable ip6.
in this project , how to open ip6 by set some-one env.

**Comment by mengkaibulusili** [comment]
@rsercano thank you, answer me so quick

**Comment by rsercano** [comment]
No worries @mengkaibulusili try below:

`
BIND_IP="::"
`

If it doesn't work try without quotes or with single quotes.

**Comment by mengkaibulusili** [comment]
let me try @rsercano  , thanks again

**Comment by mengkaibulusili** [comment]
it work! thansyou @rsercano 
my full cmd like this. i like fellow
`
docker run -it  --net=mynet  --ip=172.30.10.12  -p 36000:3000 -e BIND_IP="::"   -e MONGO_URL="mongodb://172.30.10.10:27017"  -v   mongoclientdata:/data/db  --name=mongoclient1  --restart=always  mongoclient/mongoclient 
`

**Comment by rsercano** [comment]
I'm glad your issue is resolved @mengkaibulusili 👍

**Comment by mengkaibulusili** [comment]
i think This project is better to use and better to look  than  mongo-express
