### ISSUE TITLE
Option to turn off transitions

### ISSUE THREAD

**Issue by ssipos90** [nosqlclient/nosqlclient#557]
Hi,
Cool app.

How can I turn off in app transitions? They are slowing the app down, slow me down by increase time to interactive. We are using your app in a docker container.

Thanks!

**Comment by rsercano** [comment]
Hi @ssipos90 thanks :) Unfortunately I dont understand what you mean by "transitions", if you mean the CSS based transitions, these are coming from theme itself, and no way that it's reducing the process performance actually. And there's no way to disable them so far, sorry about that

**Comment by ssipos90** [comment]
Hi. yea, the CSS transitions.

They are slowing me down and breaking my workflow by increasing the time to interactive and visual strain. The animation time is way to high (relatively speaking), what's up with that?

I didn't say it's reducing performance (?!)

If there's no way, I'm gonna sed them out in a Dockerfile.

Thanks.

**Comment by rsercano** [comment]
That's the actually first time I receive such a feedback @ssipos90 I'm sorry if they cause trouble for you, unfortunately it's not possible right now
