### ISSUE TITLE
Both windows install zips are corrupt

### ISSUE THREAD

**Issue by cmdprompt1911** [nosqlclient/nosqlclient#59]
Both windows install zips are corrupt.

Repairing either, copying to directory and running app,nothing happens.  Two electron processes show up in task manager.  navigating to localhost:3000 == connection refused.

**Comment by rsercano** [comment]
Hello,

I've tried windows x64 distribution in a virtualbox, and it's working. Please try to run as administrator and just wait a bit at the first opening. First opening can take a while.

![ss](https://cloud.githubusercontent.com/assets/3640368/14908526/76766de6-0dd8-11e6-99a1-8764b21c582c.png)

Additionally you can try to navigate localhost:11237 which's electron's port.

Best Regards
