### ISSUE TITLE
User Management: display

### ISSUE THREAD

**Issue by dfanchon** [nosqlclient/nosqlclient#63]
The message "Select a role or resource or privilege to see the details" is showing in front of the user tree view.
![capture d ecran 2016-05-02 a 10 26 14](https://cloud.githubusercontent.com/assets/1841848/14950287/dc687b06-1050-11e6-856e-600b93cb62b9.png)

**Comment by rsercano** [comment]
I guess there's something wrong with the resolving database name from the connection URI. As I mentioned #64 could you please share your connection URI without credentials and server info

**Comment by rsercano** [comment]
This error comes from the #64, since db name isn't resolved correctly.
