### ISSUE TITLE
 Extracting the Windows portable packages results in errors due to file paths being too long.

### ISSUE THREAD

**Issue by rsercano** [nosqlclient/nosqlclient#65]
Feedback:

> Extracting the Windows portable packages results in errors due to file paths being too long.
> However it seems the application works correctly regardless.
> Tested on Windows 10 Professional

**Comment by HolyThunder** [comment]
Unable to open Windows x64 .zip file. Reports that it's invalid.

**Comment by rsercano** [comment]
Hello @HolyThunder default windows zip archiver is not capable of unzipping long path names, could you please retry with winrar as mentioned in the #81

**Comment by HolyThunder** [comment]
Ah, excuse me, @rsercano. I was under the impression I was using 7-zip while I was actually using the default windows zip utility. Works fine with 7-zip.

**Comment by rsercano** [comment]
No problem at all. I'm glad your issue is fixed :)

**Comment by rsercano** [comment]
Much effort to solve on electron side, 7zip and winrar works fine.

**Comment by ghost** [comment]
I tried extracting 1.2.2 using winrar and 7zip and both are giving me the same path too long error (windows 10). Please help

**Comment by rsercano** [comment]
They are just warnings, after extraction can't you use mongoclient ?

**Comment by ghost** [comment]
The warnings are coming when copying the files from the zip file, meaning those files are **not** copied, Even when I extract the zip file to the root of C: (if I copy to an inner folder then more files have this warnings and are not copied).

I didn't try to use it but I guess the missing of those files can affect it in some way.

**Comment by rsercano** [comment]
Could you please try it like that and if you encounter anything open an another issue ?

**Comment by ghost** [comment]
I will try later when I'm home though I don't know which part may be affected because of those missing files.

**Comment by jeimz143** [comment]
i am having the same issue now. please help thank you :(

**Comment by rsercano** [comment]
@jeimz143 Would you please try on a shorter path like `C:` currently we couldn't find a better way to handle this, mongoclient is being used mostly on docker and we can't find enough time to spend on portables unfortunately, you can try to use docker version as well.
