### ISSUE TITLE
Bug with latest version of chrome and iron middleware

### ISSUE THREAD

**Issue by Dixeet** [nosqlclient/nosqlclient#67]
There is known bug with chrome and meteor that breaks mongoclient once you are connected. More precisely with iron middleware.

http://stackoverflow.com/questions/36031706/middleware-stack-js31-uncaught-error-handler-with-name-route-already-exists

I fixed it by doing as someone said on the thread:
`meteor update iron:middleware-stack`

It seems that didnt break anything :)

**Comment by rsercano** [comment]
Thanks for sharing. I was about to create a FAQ section on wiki, will add this asap. Also after migrating 1.3+ #37. I guess this issue will be fixed automatically since it doesn't use iron router :)

**Comment by Dixeet** [comment]
Yes it should. Well being in version 1.2 is good for me since i use phpstorm and the debugger seems to be broken with the latest version of meteor :p

**Comment by rsercano** [comment]
Oh I see :) Meteor 1.3 has a lot issues, I'm waiting a stable version to migrate

**Comment by Dixeet** [comment]
I'm totally new with meteor and nodejs driver. I have a question, if i understand right for each command you are opening a new connection?

**Comment by rsercano** [comment]
Yeah, that's correct, that's how drivers work. There's a connection pool that mongodb lets you to allow take one or more and then you have to close this connection to prevent further issues

**Comment by Dixeet** [comment]
Oh ok when you make a `Meteor.npmRequire('mongodb').MongoClient` if there is already a connection to this mongodb service then the driver will return you this connection instead of creating a 'real' new connection.

**Comment by rsercano** [comment]
Let's keep this talk on [gitter](https://gitter.im/rsercano/mongoclient) :)

**Comment by rsercano** [comment]
Added to [compile from source section](https://github.com/rsercano/mongoclient/wiki#31-compile-from-source-browser-edition)
