### ISSUE TITLE
Support for a base URL

### ISSUE THREAD

**Issue by krische** [nosqlclient/nosqlclient#68]
I want to run the web application behind a proxy (apache, nginx, etc.) and not at the root level (like `/mongoclient` instead of `/`). If I do this now, it tries to load all of the CSS, JavaScript, etc. files from `/` and so nothing works.

So could some kind of base URL configuration setting be added?

**Comment by rsercano** [comment]
Hello,

could you please try to setting `ROOT_URL` environment variable. If it doesn't work, could you please try to change `Meteor.startup` function that is placed in `mongoclient/server/internal/startup.js` by following [here](http://docs.meteor.com/#/full/meteor_absoluteurl)

Let me know if it works for you.

Warm Regards

**Comment by krische** [comment]
That worked! I just set `ROOT_URL` to `http://localhost:3000/mongoclient`. I also set `ROOT_URL_PREFIX_PATH` to `/mongoclient` but I don't know if that was necessary. Then I was able to setup my proxy with `/mongoclient`.

**Comment by rsercano** [comment]
I'm glad it worked :) will add this information to wiki, thank you.
