### ISSUE TITLE
Unable to unzip 1.1.0 release for windows

### ISSUE THREAD

**Issue by azizuysal** [nosqlclient/nosqlclient#69]
When I download the https://github.com/rsercano/mongoclient/releases/download/1.1.0/windows-portable-x64.zip file, I get an error message that says the compressed folder is invalid. I'm using Windows 10. I get the same error for x86.32 zip file too.

**Comment by rsercano** [comment]
Hello,

as mentioned in the #65, I will take care of it but it seems to be working in windows 10 as well, so ignore the errors and try to open application. I will try to find a way to shorten directory names, therefore need to deep dive on electron. You can keep tracking this issue on #65. Thanks for sharing.

Warm Regards
