### ISSUE TITLE
insertMany bug: dotted string value inserted with incorrect data type

### ISSUE THREAD

**Issue by stennie** [nosqlclient/nosqlclient#73]
With MongoClient 1.0.1 and MongoDB 3.2.6, inserting a field with a dotted string value can produce unexpected results. I haven't tested earlier versions of MongoDB, but this seems to be a client side bug changing some strings with dotted values to different types on insertion.

insertMany of:

```
{webscale":"192.168.1.94"}
```

... results in the `webscale` string created as an ObjectID (checked via `mongo` shell):

```
{
  "_id": ObjectId("572ba076f5e431b52061d68d"),
  "webscale": ObjectId("3134342e32392e31302e3934")
}
```

insertMany using an array of strings:

```
[{"ip":"192.168.1.94"}, {"ip":"172.29.11.154"}]
```

... results in the following documents (checked via `mongo` shell):

```
{
  "_id": ObjectId("572ba227f5e431b52061d69d"),
  "ip": ObjectId("3139322e3136382e312e3934")
}
{
  "_id": ObjectId("572ba227f5e431b52061d69e"),
  "ip": "172.29.11.154"
}
```

Originally reported at: http://stackoverflow.com/questions/37055525/mongodb-changes-string

**Comment by rsercano** [comment]
Hello,

that's an expected behaviour unless you uncheck the `valid ObjectID conversion` checkbox which placed at upper right corner at queries.

But I didn't know valid IP addresses are also valid ObjectIDs. I'll investigate this further. Currently you can simply uncheck the mentioned checkbox before inserting a document. 

Warm Regards

![1](https://cloud.githubusercontent.com/assets/3640368/15066132/ed26d08c-1366-11e6-9fa9-3b25f805ea03.png)

**Comment by vnicolet** [comment]
Hi,

I do not have this checkbox (using windows x64 last version 1.1)
How come?

Thanks

**Comment by rsercano** [comment]
@stennie comment in the link you mentioned is really interesting:

> Another interesting thing is that it does not happen on all ip addresses. for example this one : {"ip":"172.29.11.154"} works

will investigate this further as I said.

I'm glad @vnicolet 's issue is fixed.

**Comment by rsercano** [comment]
I guess there's a some sort of bug in nodejs mongodb driver, you can keep tracking this issue from here: https://jira.mongodb.org/browse/NODE-702

**Comment by stennie** [comment]
@rsercano Thanks for investigating! I would suggest turning off "valid ObjectID conversion" as a default (particularly given it can unexpectedly change types). Perhaps it can be a user preference to enable as default?

**Comment by rsercano** [comment]
I will add a notification text under selectors, thanks for the suggestion :) @stennie
