### ISSUE TITLE
Update to gridfs file metadata

### ISSUE THREAD

**Issue by bischofs** [nosqlclient/nosqlclient#80]
When I use the editor to update files by adding fields they don't persist after I close the box. Am I doing something wrong?

**Comment by rsercano** [comment]
Hello,

could you please write step by step what have you done so far ? If possible could you please share a screenshot ?

Best Regards

**Comment by rsercano** [comment]
Currently mongoclient is not capable of updating file metadata, you can only create it once while uploading. Will add capability of editing metadatas of files in next version.
