### ISSUE TITLE
Windows Distribution .zip files are reporting they are invalid

### ISSUE THREAD

**Issue by alsoicode** [nosqlclient/nosqlclient#81]
When I attempt to unzip either of the Windows portable .zip archives, I get an error from Windows stating the archives are invalid on Windows 8.1 Professional.

**Comment by rsercano** [comment]
Hello,

thanks for using mongoclient. In current windows portables, there's an erorr like this because of the long path names, but you should be able to open zip and execute mongoclient, just ignore the warnings and try to open it and let me know.

Best Regards

**Comment by alsoicode** [comment]
Unfortunately, I can't even open the archive to manually copy out mongoclient... at least not with the default Windows zip archive handler. Is there one you recommend?

**Comment by rsercano** [comment]
I'm currently able to unzip it with winrar, could you please try with it ? If you can't I'll re-package it asap

**Comment by alsoicode** [comment]
That's got it. Thanks!

**Comment by rsercano** [comment]
I'm glad your issue is fixed :) duplicate issue of #65
