### ISSUE TITLE
special character in auth causes connection to fail

### ISSUE THREAD

**Issue by ThrowsException** [nosqlclient/nosqlclient#83]
I think special characters in passwords will cause the connection to fail. in particular one of my passwords contains an '@' and cannot connect while another user on the database without any special characters can connect. Let me know if there are any additional details I can provide.

**Comment by rsercano** [comment]
Hello,

thanks for contributing, I will have a look at this issue asap.

Cheers

**Comment by rsercano** [comment]
Thanks for sharing it's fixed in current source, 1.2.0 will be released soon (as soon as I get some time to work on mongoclient)

**Comment by ThrowsException** [comment]
Thanks. I'll try to build from source for now to check it out.

**Comment by HLFH** [comment]
@rsercano Hi. With quite the same special characters, I had the same issue. The workaround is to remove the special characters within the password. Are you sure that your commit https://github.com/mongoclient/mongoclient/commit/488085bb0904444722e9642c01c0f0b36cf83c8d is fixing this issue globally?
