### ISSUE TITLE
help me in connection to mongodb

### ISSUE THREAD

**Issue by lakshmanavaradhan** [nosqlclient/nosqlclient#88]
how to connect my mongo machine using  URI method and what is mean by connection name ?

**Comment by rsercano** [comment]
Hello,

in version 1.1.0, you can simply write your URL to third tab (as far as I remember) and save it, and then simply you can choose to connect it. Url connection name is just like a tag for you to show it on main view. So its a mongoclient specific name, you can put there a text like **My Test Connection** etc. 

Regards
