### ISSUE TITLE
Connect Mongoclient to remote server through a certificate (.pem)

### ISSUE THREAD

**Issue by androidan** [nosqlclient/nosqlclient#93]
Hello,

I'm using MongoClient to manage my local instance of Mongo and it's work like a charm!

I'm wondering if is possible to use it to connect to a remote server that has auth certificates (for example amazon aws with .pem...)

or however are you planning to introduce this feature later?

thanks for you excellent work

**Comment by rsercano** [comment]
Hello,

this feature is already implemented in version 1.2.0, (#53) I'm planning to release this version as soon as I'm done with the #62, thanks for your kind opinions :)

Cheers
